### ISSUE TITLE
I can't change of class

### ISSUE THREAD

**Issue by Tapiaplay** [pa1nki113r/Project_Brutality#1012]
I'm playing whit the mod bring you own class but I can't change of class. And I tried change of class in the console but it was useful

**Comment by JMartinez9820** [comment]
Which version of PB are you playing? PB no longer has other classes to play as, as the other two were removed.

**Comment by JMartinez9820** [comment]
Then this bug report is for another mod. I will be closing this issue as invalid. Please report to the origin of that mod please.
