### ISSUE TITLE
VM execution aborted error when throwing shotgun meatshield

### ISSUE THREAD

**Issue by Someone65** [pa1nki113r/Project_Brutality#102]
![console screenshot](https://vgy.me/EGkLAk.png)

Using Jan. 24 cacobranch build.

**Comment by MekBoss** [comment]
Scripts error
https://forum.zdoom.org/viewtopic.php?f=7&t=63457&p=1089349&hilit=garbage#p1089349
Shotgun guy destroys by GC when it runs script. Need to add some null checks.

**Comment by JMartinez9820** [comment]
This issue can now be closed as it has been fixed.
