### ISSUE TITLE
Using melee causes you to frequently get stuck

### ISSUE THREAD

**Issue by Someone65** [pa1nki113r/Project_Brutality#103]
At least that's what I think is going on. If you kill enemies with punch and kick combos (and not weapons or sharp weapons) it's possible to permanently get stuck in one spot. Doesn't happen when not fighting enemies so I know it has something to do with corpses. Happens at least 80% of the time if you fight unarmed in close quarters. Try punching pinkie demons with your back against a corner with a very low ceiling above.

**Comment by MekBoss** [comment]
Corners in starting area of E1M1 is trigger bug?

**Comment by Someone65** [comment]
It often happens beside walls. I tried testing if merely fighting enemies causes it but I haven't been able to replicate it that way yet. It seems to happen when I KILL enemies. I tried using different corners without fighting enemies to get stuck but it really seems to require that you kill an enemy. It happens consistently enough that I have to make a conscious effort not to get backed up against a wall when doing bare fist combos or I'll almost always get stuck after killing enemies.

**Comment by MekBoss** [comment]
I suspect this is bug with hitbox system.
If this happens with melee weapons only and with all enemy types, not just with some dark zombie pinky with chaingun in mouth, but with cyberdemon baron and etc, try this fork.
https://github.com/MekBoss/Project_Brutality_zscript
You can download this as zip, under clone or donload button, and just drop it on gzdoom, he know how handle zip archives as packs. Run it in last gzdoom version.

Also, try to find situation which trigger bug with 101% chance, to make it easier to investigate.

**Comment by Someone65** [comment]
One thing I made sure of with the Cacobranch version is that it seems to only work with fists. I've tried other melee weapons and ranged weapons and they didn't cause this to occur. What you can do to replicate it is create an ordinary room, fill it with pinkie demons and start punching away while your back is against the wall until they're all dead. It usually only takes one to get you  stuck but you can be absolutely sure it will always occur with lots of them. It usually happens to me when I'm fighting only 1 enemy (since those are the only situations when I'd want to use fists instead of other melee weapons anyway).

**Comment by Someone65** [comment]
I found the cause of the issue! It doesn't require corpses or walls at all. One of kick attacks in the fist combos (I haven't narrowed down which one it is but I'm 100% SURE it's a kick in a combo) disables your movement. You can get around this by doing an ordinary kick (fists don't seem to help) which will reset your stuck state. I guess whatever kick move disables your movement forgets to set it back again so you can get stuck literally anywhere while doing it.

**Comment by MekBoss** [comment]
Okay, I replicate bug. In the same way as you I believe, randomly pressing left/right mouse with a kick button.
To me unstucks happens when I press two times kick button in quick sequence, before animations of first kick fade away.

This is acs bug which checks for combo items in player inventory to decide what attack sequence it must execute. I believe that before combo sequence actually plays it animations, randomly pressed kick button interrupt acs flows and decorate weapon actor plays kick animation taking away necessary to acs items from player.
I dont want to "have a big and clear as tear love" with debugging acs gameplay related scripts, since we have a more powerful, in all senses, zscript so it will be fixed in fully zscript...zscriptied....zscriptified version of PB.

**Comment by MekBoss** [comment]
I think I fixed it.
Try this one dev build. Place it in the same folder as painkiller PB build. If you switch extension of PB pack from zip to pk3 turn it back to zip, gzdoom handle zip archive as pk3 packs.
After it drop on gzdoom/zdl/other launcher pack you downloaded, it load all resources automatically.
Dont pay attention on broken sprite animations and bunch of "ERROR ACTOR CLASS ALREADY EXIST!!!!!!111 AAAAAAAAAAAAAAAAAAA" while gzdoom loads. This is dev build so it allow to do so. It must load without problem, unless I change dev build too much comparing to painkiller version.

**Comment by Someone65** [comment]
Sorry for taking EXTREMELY long to respond, @MekBoss . I Didn't have notifications on at the time. The file you provided no longer works considering how much PB Dev has been updated unfortunately so I'm not able to test your file. All I know is that this bug is still relevant considering how melee doesn't seem to have been touched since I last tried this.

**Comment by scaryred24** [comment]
Unless you can add onto this if it ever comes up again, consider this closed.
