### ISSUE TITLE
Hey man 

### ISSUE THREAD

**Issue by Somie98** [pa1nki113r/Project_Brutality#1032]
Hey man  i found this error in Master Build "Execution could not continue.

Fatal: unknown event handler class PB_FootstepsInit" can you tell me  how to fix this ?

**Comment by JMartinez9820** [comment]
@Somie98 
If you're using add-ons, please using Staging or my build (JMartinez-OfficialBranch) instead. Bugs with add-ons will not be accepted and I will close this.
