### ISSUE TITLE
Grapple hook

### ISSUE THREAD

**Issue by Somie98** [pa1nki113r/Project_Brutality#1035]
Hello JMartinez9820 when i using your build are you remove the Grapple hook and some Armor and bonus item  ???

**Comment by DemonSlayer1997** [comment]
> Hello JMartinez9820 when i using your build are you remove the Grapple hook and some Armor and bonus item ???

This has been removed as it is unnecessary garbage and PB will have brand new stuff (nothing will be that related to BD or Realm 667). PB will have new stuff in the future.
