### ISSUE TITLE
PB (master) extreme lag 

### ISSUE THREAD

**Issue by nzbtuxnews** [pa1nki113r/Project_Brutality#1036]
I have an extreme performance issue with PB (master from Github) which lags to the point of almost freezing (between 1 & 3 fps in large/busy maps), around 120fps in quiet maps/small rooms.

With the same GZdoom version and same maps/addons, etc, Brutal Doom doesnt have any performance issue whatsoever.

Map E2-M8 of Doom with addon "Mapsofchaos-OK" is a good benchmark.  Brutal Doom goes from 120-130fps to around 20fps with lots of action while PB goes down to around 1-2fps.  I noticed only one CORE is busy at 100%.  

I know this is a low end (obsolete, ancient, etc) machine but still, is there something special to do to get this mod running decently on non bleeding edge machines?

Is there a way to get more than one core busy?

Machine specs:
```
System:    Kernel: 5.4.0-144-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 Desktop: Xfce 4.16.0 
           tk: Gtk 3.24.20 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 
CPU:       Topology: Quad Core model: AMD Phenom II X4 965 bits: 64 type: MCP arch: K10 rev: 3 
           L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 sse4a svm bogomips: 27292 
           Speed: 3400 MHz min/max: 800/3400 MHz Core speeds (MHz): 1: 3400 2: 3400 3: 3400 
           4: 3400 
Graphics:  Device-1: NVIDIA GP108 [GeForce GT 1030] vendor: ASUSTeK driver: nvidia v: 525.89.02 
           bus ID: 01:00.0 chip ID: 10de:1d01 
           Display: x11 server: X.Org 1.20.13 driver: nvidia 
           resolution: 1920x1080~60Hz, 3440x1440~60Hz 
           OpenGL: renderer: NVIDIA GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 525.89.02 
           direct render: Yes 
Audio:     Device-1: AMD SBx00 Azalia vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 00:14.2 chip ID: 1002:4383 
           Device-2: NVIDIA GP108 High Definition Audio vendor: ASUSTeK driver: snd_hda_intel 
           v: kernel bus ID: 01:00.1 chip ID: 10de:0fb8 
           Sound Server: ALSA v: k5.4.0-144-generic
```

GZDoom
```
GZDoom 4.10.0 - 2022-12-04 15:23:05 +0100 - SDL version
Compiled on Dec  5 2022
OS: Linux Mint 20.3, Linux 5.4.0-144-generic on x86_64
GZDoom version 4.10.0
```

**Comment by JMartinez9820** [comment]
@nzbtuxnews 
PB is not meant to be played on large maps with tons of monsters. Most of this will likely be fixed with monsters being redone from the ground up, recoded to ZScript and the hitbox overhaul

**Comment by JordanL2** [comment]
> @nzbtuxnews PB is not meant to be played on large maps with tons of monsters. Most of this will likely be fixed with monsters being redone from the ground up, recoded to ZScript and the hitbox overhaul

Is this already happening on the PB_Staging branch? I'm using that branch and the performance definitely seems better (still very slow with 1000+ monsters though).

**Comment by Brugarolas** [comment]
GZDoom is not very well optimized, I can tell you that. And Project Brutality has a lot of scripting. I don't know if Project Brutality works on LZDoom, try it, it might help.
