### ISSUE TITLE
Low health pulse doesn't scale to 21:9

### ISSUE THREAD

**Issue by oblivioncth** [pa1nki113r/Project_Brutality#1039]
Tried searching the existing issues, google, and scouring the in-game settings for something that could affect this but had no luck.

This is in reference to the red pulsing effect that occurs at the edges of the screen when your health is low:
![Scale](https://user-images.githubusercontent.com/24661585/226122231-fbb1e0ae-e6af-439e-ae58-a7832bf13819.png)

Is there anyway to stretch the effect, or at least turn it off completely? It's quite immersion breaking as is.

**Comment by JMartinez9820** [comment]
If you're using an add-on, then I'm closing this. Please look at other closed issues before reporting. Add-on bugs will not be accepted here, please go to the Discord server instead.

**Comment by oblivioncth** [comment]
Terribly sorry, after discovering the discord and then also searching there, it seems that this effect is only part of Draugrak's pack and is oddly under the `DKs Badass Sounds.pkg3` so I didn't think the addons were contributing to this.

https://discord.com/channels/498342220815007779/498363558070059009/987892743554596894
