### ISSUE TITLE
Invisible weapons

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#106]
Some weapons are invisible till you pick them up, the nail gun for example. If you drop it it's invisible again. Is it just me or happening to everybody?

**Comment by MekBoss** [comment]
You have amd videocard? If yes, it can be problem with drivers. Graf and company probably solved this, dont remember exactly.
And give more info, version number of gzdoom, what you run, how, where, when, etc.

**Comment by JMartinez9820** [comment]
I believe this is a sprite pick-up problem. I think they are not in the right place or they are misnamed. Anyways, this build is playable but unstable so expect bugs. We will resolve this issue soon.

**Comment by Emircan34** [comment]
I fixed the bug he forgot to add sprites sprites are missing so i guess it will be fixed

**Comment by JMartinez9820** [comment]
I think this is now fixed. This issue can be closed @TonyH1234
