### ISSUE TITLE
Where offend in new version?

### ISSUE THREAD

**Issue by Igizzzy** [pa1nki113r/Project_Brutality#1066]
Where offend in new version?

**Comment by JMartinez9820** [comment]
@Igizzzy 
Completely removed

**Comment by Igizzzy** [comment]
> @Igizzzy Полностью удален

Why?

**Comment by JMartinez9820** [comment]
1. It wasn't up to standards
2. New approach for Doomguy
3. cluttered keybinds

**Comment by Igizzzy** [comment]
> 

will it be something else?
