### ISSUE TITLE
Everytime I close the game, GZDoom crashes

### ISSUE THREAD

**Issue by aerinoth** [pa1nki113r/Project_Brutality#108]
After changing resolution and going fullscreen GZDoom (3.7.2.0 x64) crashes and my saved data is nowhere to be found. 

[http://i65.tinypic.com/289bexy.jpg](url)

**Keep up the good work!**

**Comment by scaryred24** [comment]
That could be an issue out of our control. Possibly an issue with GZDoom. Have you not beaten the first level? It wont start saving until after that point. Did it create a config file in the root on GZDoom? It should be named something along the lines of [pc account name].ini somewhere along there. Also make sure you don't have GZDoom set to read only. 

> **Keep up the good work!**

I hope you are joking. It did kind of came off sounding a bit sarcastic to me.

**Comment by aerinoth** [comment]
Yeah, I was thinking it well may be GZDoom... 

As soon as I finish the first level it crashes. Thanks for reading.

> I hope you are joking. It did kind of came off sounding a bit sarcastic to me.

None of that!
