### ISSUE TITLE
Can't reload at least 80% of the weapons in stock PB

### ISSUE THREAD

**Issue by ToxicMethASS** [pa1nki113r/Project_Brutality#109]
No matter what i've tried so far i simply can't get the reload binds to works on most of the weapons. Works fine in traditional and v21, but not the main gamemode. It's pretty annoying since I'm used to constantly manually reloading just to be safe for more action. Tried downgrading gzdoom and even tried manually binding "reloader" to keys but no avail.

Tried many releases that include new changes (aka master)

**Comment by JMartinez9820** [comment]
The main PB mode has got it's reloading changed to GZDoom's default "Weapon Reload" keybind. Try mapping your reload key to "Weapon Reload" (should be one of the first options you will see in the Controls settings), and see what happens.

**Comment by ToxicMethASS** [comment]
oml well that was stupid of me but thanks for the help
