### ISSUE TITLE
Plasma Rifle Ammo Problem

### ISSUE THREAD

**Issue by Nodens99** [pa1nki113r/Project_Brutality#1091]
When you reload the normal plasma rifle, all of your cell ammo disappears.

**Comment by JMartinez9820** [comment]
Check if you're using add-ons or if you're loading from a previous save. If that's the case, then remove any add-ons or start a new game. I have no issues so far.

**Comment by Nodens99** [comment]
> Check if you're using add-ons or if you're loading from a previous save. If that's the case, then remove any add-ons or start a new game. I have no issues so far.

okay sorry that does seem to be the issue, loading previous save was the problem. My bad.
