### ISSUE TITLE
Moddb page for "Project Brutality Official" and Patreon?

### ISSUE THREAD

**Issue by skdursh** [pa1nki113r/Project_Brutality#1101]
Is this really you guys?
https://www.moddb.com/mods/project-brutality-official
https://www.patreon.com/doomprojectbrutality

**Comment by iamcarrotmaster** [comment]
no it isnt
dont go anywhere near that shit

**Comment by skdursh** [comment]
@iamcarrotmaster I didn't think so. You guys should reach out to Moddb and Patreon to let them know. Mod theft is such a bizarre way to announce to the world "hey, I'm an absolute scumbag".

**Comment by iamcarrotmaster** [comment]
we are
