### ISSUE TITLE
Can't reload cryo rifle using reload button when empty

### ISSUE THREAD

**Issue by Someone65** [pa1nki113r/Project_Brutality#111]
As the title states, in both fire mods if you get the ammo down to 0 and then press GZDoom's reload button, the gun will not reload as it still uses BD's own reload bind.. You must press fire to get it to reload instead. Not sure how many other guns have a similar issue. Will check.

**Comment by JMartinez9820** [comment]
This is current mapped to Brutal Doom's Reload key when Cyro Rifle is empty. This isn't really a big problem, so clicking works as well. Remember, bugs take time to get fixed. This could get touched on later as PB is still undergoing its Weapon Overhaul phase.

**Comment by JMartinez9820** [comment]
@Someone65 I can confirm that this bug is now officially fixed thanks to the Freeze Rifle overhaul. You can close this issue now. If it comes back up again, then re-open it.
