### ISSUE TITLE
Issues and suggestions from playing with build f7da1fb4b06872d0e38ea6d64671451000b73091

### ISSUE THREAD

**Issue by MusicalDucky** [pa1nki113r/Project_Brutality#113]
Hi,

Thank you for making this amazing mod. I had a lot of fun playing with the last build.

I encountered the following problems while playing. I don't know if they are still in the new build but maybe this information is still useful. There are also some suggestions at the bottom.

1) Occasionally the game would crash. I think it happens when a lot of hit scan weapons are being used. Here is the error message that would pop up if this happens.

![image](https://user-images.githubusercontent.com/48030620/53590980-a5414a80-3b9b-11e9-8bc1-6110c0f79057.png)

2) Sometimes the player's view will stay tilted after either inspecting a weapon (nailgun) and then switching to another weapon.  Here is an example:

https://youtu.be/HIgmEmdT5IM?t=249

3) It does not seem possible to finish some WADs that rely on slow explosive projectiles like the end of the "The ID did WAD" correctly. Maybe the new burrowing grenade launcher can be modified for this? I realise this is very much an edge case. Here is an example:

You are supposed to fire slow projectiles from the platform at 2m06 at the icon, chase them, go through the teleporter and activate the switch before they hit the pillar:

https://youtu.be/y9PBsTsNgyU?t=124

4) It is difficult to aim with the lightning gun, perhaps it can be a bit lower on the screen.

5) [SUGGESTION] There are many weapons in PB which is great but some fill very similar roles. The rocket launcher and contact grenades for instance.  Perhaps contact grenades can be made more interesting by releasing a directed shrapnel blast on impact.

6 [SUGGESTION] The sticky grenades are good for things like Cluster f**k but frequently remain unused in more aggressive play styles. Maybe then can be made more interesting by causing enemies to go berserk and charging the nearest enemy before exploding? (Limited to weaker enemies)

**Comment by MekBoss** [comment]
For first one
https://forum.zdoom.org/viewtopic.php?f=7&t=63450
Just wait new gzdoom release or use +vm_jit 0 in command line before starting gzdoom.

For second, its a known problem, which already fixed in my local build. Use iron sight of any weapon to reset camera roll.

**Comment by JMartinez9820** [comment]
I believe all or most of these problems have since been fixed iirc, Project Brutality now requires at least GZDoom 4.1.3 to run. This issue can be closed now. If any issues rear their ugly heads again, then reopen it.
