### ISSUE TITLE
Lightning Gun Reload

### ISSUE THREAD

**Issue by Nevermore2790** [pa1nki113r/Project_Brutality#114]
Reloading the M2 Plasma Rifle with Lightning Gun on starts and ends with missing sprites (missing turn off, turn on of the Lightning Gun).

**Comment by JMartinez9820** [comment]
If the sprites are just blinking on reload frames when reloading the M2 Plasma Rifle on the Lightning gun mode, then it isn't really a big problem. This will get fixed when the M2 Plasma Rifle gets overhauled.

**Comment by JMartinez9820** [comment]
This issue can now be closed as the M2 Plasma Rifle has now been overhauled and this has been resolved. If this issue comes back at a later point, feel free to reopen this issue.

**Comment by JMartinez9820** [comment]
@Nevermore2790 Because this issue is now resolved, you can now close this issue.

**Comment by scaryred24** [comment]
At this point considering how long this gas been abandoned for, there is no need to pester a user. I'd say after 30-90 days without a response, its to be closed.
