### ISSUE TITLE
How to install on Delta Touch(android)

### ISSUE THREAD

**Issue by TSKERRER** [pa1nki113r/Project_Brutality#1147]
I wanted to install it but,there are just files of the mod,no PK.3 or wad files,what should I do?

**Comment by AresFallen** [comment]
Go Buy the Google Play Store. Go Buy the Classic Doom/Doom II. Then After Downloaded. Now put the Doom wad into the OpenTouch Files and Mod PB into the Mods Files. And don't tell about that one.![0af.png](https://github.com/pa1nki113r/Project_Brutality/assets/122029564/40187d9f-aa46-47b7-84d2-6241271e965a)

**Comment by TSKERRER** [comment]
I can't launch a folder like a pk3 file,I know I am dumb.

**Comment by AresFallen** [comment]
> I can't launch a folder like a pk3 file,I know I am dumb.

Okay..... I only _one_ is gonna said it with you. A **Zip** Files can loaded the GZDoom. Now i should to **Load** Right now. GO!

**Comment by TSKERRER** [comment]
Okay,I am actually dumb,I just renamed Project brutality master from zip to PK.3 and it launched successfully,but only on LZdoom(maybe because I have a low-end phone)

**Comment by AresFallen** [comment]
> Okay,I am actually dumb,I just renamed Project brutality master from zip to PK.3 and it launched successfully,but only on LZdoom(maybe because I have a low-end phone)

And.... Generic. Annihilate the Issues Removed immediately. Only at GZDoom. Even the Master Branch is Too Outdated. Low-end phone doesn't giving your Acceleration. To Staging only.

**Comment by TSKERRER** [comment]
Okay I'll try to load the zip file.

**Comment by AresFallen** [comment]
> Okay I'll try to load the zip file.

Okay.... Don't forget the GZDoom Option. You can set it whenever you Used the Low-End Phone.

**Comment by TSKERRER** [comment]
Thanks,it works on Gzdoom now(and for some reason with more FPS than the original Brutal Doom)is there some kind of test map where I can test all of the content.

**Comment by TSKERRER** [comment]
And also you can recommend some addons

**Comment by TSKERRER** [comment]
Thanks!

**Comment by TSKERRER** [comment]
![Screenshot_2023-07-11-14-41-23-0906409157](https://github.com/pa1nki113r/Project_Brutality/assets/96237754/f024d426-bae1-4548-ba0f-28f8a18f31f9)
And it,doesn't work,because I guess something from staging mod already exists in the PB?

**Comment by generic-name-guy** [comment]
Lots of sprites

**Comment by TSKERRER** [comment]
Aren't there supposed to be vehicles,or I'm wrong?

**Comment by TSKERRER** [comment]
And iddqd doesn't work but I don't care.

**Comment by generic-name-guy** [comment]
No and iddqd definitely works

**Comment by TSKERRER** [comment]
Okay,all my questions have been answered.
