### ISSUE TITLE
Game Crashes When You Throw an Imp

### ISSUE THREAD

**Issue by Davcoll** [pa1nki113r/Project_Brutality#116]
Not sure if this was already mentioned, so I apologize if this has already been reported.

I noticed when you pick up an Imp and use up a full assault rifle mag the game will crash after you throw the Imp.

**Comment by MekBoss** [comment]
Known error.

**Comment by scaryred24** [comment]
Excuse me for not seeing this sooner. Seems to be a common issue among mods derived from Brutal Doom. This was going to rear its ugly head up sooner or later. Will keep this in mind and will look into it.

**Comment by MekBoss** [comment]
Fix. Load after PB.
Ask someone who can rights to merge it in master build.

**Comment by goldenmobster** [comment]
Hmm , Kinda hard to say since the BD code was scrapped [removed]

AFAIK You can only grab Imps when they are bleeding out [Dismembered] , so i'll grab a imp and see if THAT crashes PB or not

**Comment by goldenmobster** [comment]
So I checked if Grabbing a bleeding out Imp crashes PB and it did not crash on me when i grabbed a Imp that was Bleeding out

**Comment by JMartinez9820** [comment]
This issue can be closed as it doesn't crash anymore.
