### ISSUE TITLE
Rocket explosions causing game hang.

### ISSUE THREAD

**Issue by Sir-Wulfrick** [pa1nki113r/Project_Brutality#1162]
I'm running the latest version (as of the date of this post) of Project Brutality with GZDoom 4.10 W64, loaded with Doomloader 1.8.1.

I'm getting an intermittent crash that appears to be cause by rocket explosions. It can happen in any map, either iWAD maps or user created maps, and only ever happens with the rocket launcher. The hang problem is hard to reproduce because it doesn't necessarily happen when I first use the rocket launcher in a map.

When the hang occurs it always happens when a launched rocket impacts an enemy. It MAY be happening more often when a launched rocket impacts an enemy and does splash damage to a number of other enemies, though verifying that is difficult. At the point at which the launched rocket explodes the game (GZDoom) hangs and needs to be manually killed with Windows task manager. GZDoom does not create a cash log and I can't access the game console to read any error messages.

System spec:
AMD 5950X at stock frequency.
NVidia RTX3090 at stock frequencies, running driver number 536.99 - latest version at the time of writing.
32GB RAM at 3.6GHz.
Both GZDoom and PB are running from a 1TB NVMe 4 drive.

**Comment by generic-name-guy** [comment]
fixed in stag
