### ISSUE TITLE
Game freezes and stops responding randomly when hitting an enemy with an attack

### ISSUE THREAD

**Issue by rychschax** [pa1nki113r/Project_Brutality#1168]
I'm afraid I can't provide _full_ system specs at the moment, as I am writing this from my work computer, but here's what I know:

OS: Windows 10
CPU: AMD Ryzen 7 3800X 8-core 3.9GHz
GPU: Nvidia GeForce RTX 2080 Super
RAM: 24~32 GB DDR4

GZDoom version: 4.10.0
PB version: 3.0
IWAD used: DOOM2.wad

The bug:
When playing, the game will randomly freeze (permanently) upon hitting an enemy with a weapon.  Neither the exact enemy (both type and specific instance in a map) nor the weapon used seems to make a difference.  I say that the game _randomly_ freezes because I've yet to find any means of reliably causing the bug to occur.  Sometimes it happens within a minute or two of playing, other times I can play through an entire map without issue.  The bug occurs even if PB is the only extra wad being loaded.

The game runs silky smooth otherwise.  I've tried different renderers to see if maybe that was the issue, but no luck.  The freeze occurs  as soon my first attack on a particular enemy lands.  Of note is the fact that the music continues after the freeze, along with any looping weapon sounds (like the chain gun firing sound).  The game doesn't actually _crash_, so I can't look at logs or anything to see what is happening.

One last thing that may be noteworthy:  I've noticed that it takes _far_ longer to load a map (either via a new game, loading a save, or reloading after death) with PB than it does with _any_ other mod, regardless of the mod's complexity.  It might be nothing, but I thought I'd mention it anyway.

**Comment by generic-name-guy** [comment]
The freezing is fixed in PB_Staging https://github.com/pa1nki113r/Project_Brutality/tree/PB_Staging, please do not use master as it is several months out of date 

For the slow loading: PB uses tons of sprites  for it's smooth weapon animations, to maybe remedy this issue, **disable** "Precache GL Textures" in GZDoom's Texture Options (Options > Display Options > Texture Options).
