### ISSUE TITLE
VM execution aborted: Invalid class PlayerHeavyMachinegun in function call to PlayerPawnBase.StateFunction.0. PlayerPawnBase expected (similar to #715)

### ISSUE THREAD

**Issue by tungstendonn** [pa1nki113r/Project_Brutality#1172]
OS: Linux Mint 21.2, Linux 5.15.0-78-generic on x86_64
GZDoom version 4.10.0

Using video driver x11
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce RTX 2070 Super with Max-Q Design/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 535.86.05 (Core profile)
GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA

Max. texture size: 32768
Max. texture units: 32
Max. varying: 124
Max. combined shader storage blocks: 96
Max. vertex shader storage blocks: 16
Resolution: 640 x 480

Mods used: 
Project_Brutality-master.zip
hellonearthstarterpack.wad (OG Extermination day wad)
ExtraTextures.wad (bundled with HOE starter kit)

------------------------
Hey guys, looks like's there's a scripting issue within the latest version of Project Brutality, which causes the came to crash  back to menu when the player attempts to use a mounted heavy machine gun:

M execution aborted: Invalid class PlayerHeavyMachinegun in function call to PlayerPawnBase.StateFunction.0. PlayerPawnBase expected
Called from PSprite.Tick at gzdoom.pk3:zscript/actors/player/player.zs, line 2650
Called from PlayerPawn.TickPSprites at gzdoom.pk3:zscript/actors/player/player.zs, line 504
Called from PlayerPawn.PlayerThink at gzdoom.pk3:zscript/actors/player/player.zs, line 1654
Called from overlay state PlayerPawnBase.0 in PlayerHeavyMachinegun
Called from PSprite.SetState [Native]

Looks very similar to issue listed on #715.

Additionally, when loading project brutality into GZDoom, I'm seeing this pop up:

Script warning, "hellonearthstarterpack.wad:HMG" line 193:
Unknown class name 'HeavyMachinegunHUD' of type 'Inventory'
Script warning, "hellonearthstarterpack.wad:HMG" line 289:
Unknown class name 'PressedJump' of type 'Inventory'

Let me know if you need anymore info and I'll try to snag it for you.

Thanks!

**Comment by tungstendonn** [comment]
@generic-name-guy hmmm. same issue with the PB staging version. Figured that was probably what was going on. Some weird scripting stuff in that wad.

Not a huge deal, just would prefer the full extermination day experience.

On a side note, not sure if there's SM4 released any newer versions of Extermination Day for gzdoom after that. The wads here don't seem to load up on gzdoom https://allfearthesentinel.com/zandronum/wads.php?order=date_desc&name=eday. Even with just the edaymaps.wad file.

Thank for the input though!

**Comment by generic-name-guy** [comment]
Here's a version of EDay that should be compatible with the latest version of PB, i haven't tried though, as this mapset runs poorly on my machine.

https://drive.google.com/file/d/1p617GfeW60-oZhVw9DBg-lgZTis2AAYT/view
