### ISSUE TITLE
Weapon and monster sprites from pwad appears to "override" sprites from PB, despite being lower in load order

### ISSUE THREAD

**Issue by tranquilcarbon** [pa1nki113r/Project_Brutality#1176]
**Issue Description:**
When playing a WAD with custom weapon graphics or enemy sprites, it appears to override the ones specified by Project Brutality. I have demonstrated this with the supplied video, which shows me firing the M1 Plasma Rifle, which has the original sprites from Doom overriding it, resulting in the animation flashing between both during firing.
**Load Order**
doom2.wad
Project-Brutality-Master.zip (latest as of 31/08/23)
hell2pay.wad (Hell To Pay by WizardSoft)
**Recreation**
1. Download GZDoom 4.10.0, it is likely that this issue also occurs on later versions, if they exist.
2. Download the latest release as specified by the date
3. Download Hell2Pay.wad, or another pwad that features custom sprites for weapons or enemies.
4. give yourself all weapons and there should be one from doom's original arsenal that conflicts.

**Comment by generic-name-guy** [comment]
Load the map before PB.

Unrelated but [download Staging](https://github.com/pa1nki113r/Project_Brutality/archive/refs/heads/PB_Staging.zip), it's more up to date.
