### ISSUE TITLE
Monster Weapons

### ISSUE THREAD

**Issue by AvrasMitilineos** [pa1nki113r/Project_Brutality#1177]
Hello! Recently, I faced an issue with Project Brutality. I realized that I can't have a Normal BFG and Mancubus Dual Flame Cannons at the same time. Each time I tried to load BFG9000 or BFG10K and Mancubus Dual Flame Cannons at the same time, BFG is disabled. Because I want to kill each enemy with his own weapon (or a similar equivallent), I can't use BFG to kill a Baron of Hell or a Hell Knight, because I don't have a BFG. I tried to load BFG9500, which is more powerful. I noticed that Mancubus Dual Flame Cannon has been disabled. This means I can't kill Mancubus with his own weapon. Can you tell me if there is a way to have both BFG9000 or BFG10K and Mancubus Dual Flame Cannon at the same time?

**Comment by generic-name-guy** [comment]
These weapons no longer exist in the latest version https://github.com/pa1nki113r/Project_Brutality/archive/refs/heads/PB_Staging.zip

**Comment by JMartinez9820** [comment]
This seems like an addon bug rather than PB. This should be closed as invalid

**Comment by generic-name-guy** [comment]
> This seems like an addon bug rather than PB. This should be closed as invalid

true i didn't notice lol
