### ISSUE TITLE
A couple of bugs in rev 105c76384307fbbfdb4834f2b17a9e31e7946e47

### ISSUE THREAD

**Issue by tunbridgep** [pa1nki113r/Project_Brutality#118]
Hey. Mod is pretty good so far!

I have noticed a bunch of bugs with the latest revision. I would be more than happy to try to fix these bugs, although I do not know exactly how this mod runs or what sort of procedure it uses to vett/verify bugs, so I will leave it up to commenters to let me know if these are good things to try and fix.

1. When dual-wielding the rifle, reloading the weapon without having any ammo left for reload will make only 1 rifle appear again

2. The SMG is missing it's pickup sprite

3. Many other objects are missing sprites as well, such as the SmartScavenger Box of Bullets

4. With weapon sway turned ON, looking down will frequently show visible gaps at the bottom of many weapon sprites. The Carbine is probably the most egregious example

5. Many "Dual Wield" weapons have incorrect selection/deselection sprites, which will show the original non-dual-wielded version. For example, switching from the dual-wield rifle to the shotgun, the rifle will instantly appear at the bottom of the screen before being hidden, as if you were deselecting a single rifle.

6. Setting a crippled enemy on fire makes them stand up and run around like they normally would. Not sure if this is a bug or intended behaviour.

7. The "Enable stimkits" option (the one that allows health kits in the players inventory) doesn't seem to work, at least I haven't found any health kits that behave that way

8. If player view bob is turned off, he will still bob when reloading the carbine

9. The player makes no sound when taking damage from fire, such as from dragons breath rounds, and there is no screen effect. The only way to tell this is happening is to watch your health go down.

10. When reloading but having no reserve ammo, the "CLICK" sound will play endlessly on repeat until you release the key.

11. Setting a caco on fire with the dragons breath rounds makes him go a weird, tutti-fruity color

Also, not a bug, but am I the only person who VASTLY prefers the ole carbine sprites?

**Comment by scaryred24** [comment]
Unable to get to this atm. If you still find any of these to be a problem, do respond asap. Otherwise closed.
