### ISSUE TITLE
new idea for doom

### ISSUE THREAD

**Issue by showgun999** [pa1nki113r/Project_Brutality#1184]
hey I had an idea that I would like to share. what if there was a hook attachment that you could attach to the double barreled shotgun, and the quad shotgun? I am thinking that it could function like the hook on the double barreled shotgun in doom eternal. or maybe it could stun enemies while you flung yourself at the enemy with the hook. or maybe it could attach to the ceiling and work like a grappling hook for extra mobility? would this raise copyright issues? please contact me soon. I have rarely used this website, but after making this comment I will try to check up often to receive a respond from the team. thanks, "Scott".

**Comment by JMartinez9820** [comment]
Suggestions do not belong on here, post this on the Discord server. However, PB's direction is trying to not copy Doom Eternal, so I don't think that's on the plans for now, and probably won't be on.

**Comment by showgun999** [comment]
ok! thanks for the speedy reply! I honestly thought that it would take a while, and I did not know that there was a discord server. thanks for the help and insight! ;-)

**Comment by iamcarrotmaster** [comment]
https://discord.gg/2hJxXPc
