### ISSUE TITLE
Couple of performance issues and one repeatable crash to report.

### ISSUE THREAD

**Issue by Mrnglry** [pa1nki113r/Project_Brutality#1187]
Hello, new here and just wanted to leave a small report, This is also the only mod loaded, and as a .pk3 not zip for smoother loading.

I have a pretty beefy laptop and I experience VERY smooth gameplay for the most part, rarely dip below a solid 60fps(my current external monitor is shit so I cant go higher). These are niche issues besides the CTD. I play at 1920x1080 fullscreen with filters off and decals set to (125) to prevent single cell texture/sprite overdraw from too many instances of blood decals landing on one single wall in a small spot which was my only issue for a long time

-Performance issues-  
1 - Blood mist overdraw - When using the super shotgun, occasionally when killing at very close range I experience a VERY small but noticeable stutter, this can be repeatable and is pronounced when staring at a 90 degree angle adjacent to them, especially the headshot/upper body up close. I believe this is caused from the bloody mist when it briefly covers the screen at close range, similar to shooting a wall up close with the shotgun, same stutter but very very brief, mostly unnoticeable. This only happens at a very specific angle and only when the mist occurs directly in front of the player's periphery. When I used the Carrot build(it does not have bloody mist effect) the issue is resolved. This issue is honestly not too bad just kind of annoying but I wanted to leave good feedback. 

2 - Flamethrower can produce the same stutter but lasts slightly longer at very close range when using SUSTAINED fire in ONE spot when you are too close, looks like overdraw as well and quickly goes away. The carrot build's flames resolve this to a certain extent oddly enough. Side note, the floor ice decals made by the freeze ray from the carrot build ARE HORRIBLE when it comes to overdraw, immediately tanks my fps. Its either the light they emit or decals that build up in one spot not sure but its definitely not ready for release lmao. 

-Repeatable CTD- 
I have a feeling this has already been addressed since its bound to occur to anyone but regardless, the custom heavy red Chaingunner SPECIFICALLY the one with the helmet and visor will almost always crash my game when I shoot them in the upper body or head with the rocket launcher. Does not matter what map or the volume of enemies whether large or small, it will always happen. I have no idea why this happens and tried everything to fix it. That guy just doesn't like getting hit with a rocket to the face at all lol

I'll leave another report in a week maybe more or so after spending more time playtesting and enjoying more maps with it. All in all its amazing work and I've had a blast lol

**Comment by JMartinez9820** [comment]
@Mrnglry The Chaingunner crash is fixed in the Staging branch, use that instead.
https://github.com/pa1nki113r/Project_Brutality/tree/PB_Staging

**Comment by Mrnglry** [comment]
THANKS SO MUCH! It was infuriating lol
