### ISSUE TITLE
Item spawning on Tier 2 state would spawn a duplicate of that item

### ISSUE THREAD

**Issue by JMartinezHarmoniousPerson** [pa1nki113r/Project_Brutality#1189]
If an item spawns on the Tier 2 state, example, the armor, it would spawn a copy of said item due to the lack of a Stop on the Tier 2 states. Thanks to DarynS for reporting this issue, I have fixed the spawns for the Armor and Health, but it seems to affect other items too, such as ammo. I will likely post fixes on Discord too through bug reporting

**Comment by popguy12** [comment]
i think this has mostly been fixed, if any more crop up just lemme know
