### ISSUE TITLE
Included .wad files should probably be unpacked into their raw lumps

### ISSUE THREAD

**Issue by tunbridgep** [pa1nki113r/Project_Brutality#119]
According to the [Zdoom Wiki](https://zdoom.org/wiki/Using_ZIPs_as_WAD_replacement), placing .wad files inside ZIP files is very bad for performance and memory.

> WARNING: Loading WAD files inside of a ZIP or a PK3 will cause memory issues to arise. ZDoom will unpack each WAD file and use more memory to access the contents. This effect quickly adds up, especially in larger mods (with the exception of map wads in the maps/ folder, provided they follow the format explicitly -- see below). The bigger the mod is, the more likely it may run out of memory during play and crashing ZDoom, or for memory corruption to occur. Thus, it is highly recommended to completely unpack the entire contents of any WADs inside, or part of the mod, into the sorted directories.

This is low priority, but anything that isn't a map replacement should probably be unpacked for the sake of performance/optimisation

**Comment by MekBoss** [comment]
Size of all wad files around 10 megabytes, including level wads, which means gzdoom would consume +10 megabytes above its normal amount.
So this issue probably dont important at all.

**Comment by goldenmobster** [comment]
> Size of all wad files around 10 megabytes, including level wads, which means gzdoom would consume +10 megabytes above its normal amount.
> So this issue probably dont important at all.

Right, If there are any problems we will re-open this
