### ISSUE TITLE
Character not moving

### ISSUE THREAD

**Issue by Vlad23790** [pa1nki113r/Project_Brutality#1191]
My character not moving Fix This Bug I can't move.

**Comment by inkoalawetrust** [comment]
Maybe actually describe something ? Like, what version are you using for example, how did you start the mod up ?

**Comment by JMartinez9820** [comment]
Duplicate of the same thing that's been said a lot. Delete your GZDoom.ini and it should fix it

**Comment by Vlad23790** [comment]
> Maybe actually describe something ? Like, what version are you using for example, how did you start the mod up ?

I just send zip of project brutality to gzdoom

**Comment by generic-name-guy** [comment]
Make sure to update to the PB_Staging branch so this problem doesn't happen again.

**Comment by Vlad23790** [comment]
I solve this problem thank you all for say delete gzdoom ini

ср, 3 апр. 2024 г., 03:09 popguy12 ***@***.***>:
