### ISSUE TITLE
Hitting multiple Chaingunners with a rocket often crashes the game

### ISSUE THREAD

**Issue by Trigonomancer** [pa1nki113r/Project_Brutality#1194]
Renderer: Vulkan
GPU: Radeon 2200G Vega 11 APU
[Video](https://youtu.be/PGBgN9rlEwQ)

**Comment by JMartinez9820** [comment]
@Trigonomancer
Use the Staging branch. Next time, explain your issue rather than posting your specs. This is also a duplicate of previous issues. Look at issues or closed issues before posting.
