### ISSUE TITLE
Black screen in linux 

### ISSUE THREAD

**Issue by supersonic118** [pa1nki113r/Project_Brutality#120]
There is sound but there is nothing displayed, cannot even see the menu. I even reinstalled gzdoom and tried different versions pls help

**Comment by JMartinez9820** [comment]
I'm not an expert and Linux but you may need to open a terminal to start up GZDoom. Type this in the terminal.
+set mblur 0
I will help out later when I try to run this on Linux.

**Comment by JMartinez9820** [comment]
If you want help on Discord here is a link to the PB server.
Make sure to type ~>iam accepted in the verification channel.
https://discord.gg/2hJxXPc

**Comment by Cacodemon345** [comment]
What GPU you are using @supersonic118?

**Comment by supersonic118** [comment]
intel hd 4000

**Comment by Cacodemon345** [comment]
Then it looks like a issue with Intel's GPU drivers on Linux.
Also, what Linux Distro you're using?

**Comment by supersonic118** [comment]
linux mint

**Comment by supersonic118** [comment]
its weird because older versions of project brutality work

**Comment by Cacodemon345** [comment]
Have you disabled Motion Blur?

**Comment by scaryred24** [comment]
I take it that since its been over 2 weeks since the last post from the creator of this thread, I'm going to assume that the issue was resolved and close this. If not, just reopen it and we will look into this deeper.
