### ISSUE TITLE
Default in game font breaks if you use another language with special characters

### ISSUE THREAD

**Issue by JMartinez9820** [pa1nki113r/Project_Brutality#1201]
According to Kamil, the in game font breaks if you use another language with a special character type. It would simply default back to the standard GZDoom font, rather than PB's. I just tested this myself and I can confirm this. I will post screenshots later.

**Comment by ADmeral97** [comment]
TFW a font doesn't support other languages besides english.

**Comment by JMartinez9820** [comment]
Oh okay. Languages like Spanish (Latin American), French and Italian work, basically any other language character this happens. I'll go close this, thanks for letting me know.

**Comment by generic-name-guy** [comment]
Every language that uses the latin alphabet will work.
