### ISSUE TITLE
Completing a level while doing an execution completely locks/freezes player movement.

### ISSUE THREAD

**Issue by JMartinezHarmoniousPerson** [pa1nki113r/Project_Brutality#1205]
If you complete a level while doing an execution, the player movement completely locks up, and you can't even use the kill command because you're also completely invulnerable. You can easily replicate this by spawning a fodder enemy, do an execution, do enter changemap map## in the console. The player movement should now be completely locked.

**Comment by JMartinez9820** [comment]
Edit: You can still hear the grunts of the player getting hurt but you take absolutely no damage.

**Comment by popguy12** [comment]
i think this is fixed now, cant seem to replicate it at all
