### ISSUE TITLE
brutal doom v21

### ISSUE THREAD

**Issue by B-Nerd** [pa1nki113r/Project_Brutality#1208]
when will this update use the core of brutal doom v21 the final version of brutal doom because there has been a lot of changes to brutal doom

**Comment by generic-name-guy** [comment]
this mod is so different from brutal doom that updating it to the latest version would be completely pointless, and we also want to distance ourselves from brutal doom as much as possible

**Comment by DeckardDetribine** [comment]
bdv21 isnt even the final version anyway lol

**Comment by B-Nerd** [comment]
> this mod is so different from brutal doom that updating it to the latest version would be completely pointless, and we also want to distance ourselves from brutal doom as much as possible

ah oke no problem
