### ISSUE TITLE
Weapon Special wheel is completely broken in the newest update

### ISSUE THREAD

**Issue by JMartinez9820** [pa1nki113r/Project_Brutality#1216]
The weapon special wheel seems broken on selecting other specials in the newest update. Is it because of the change from GZDoom 4.8.2 to GZDoom 4.11? I did notice some start up warnings too say comparison between signed and unsigned variables. The fact that y'all didn't seem to test this before pushing it out is inexcusable and unacceptable.

**Comment by Ventolin1369** [comment]
😓
