### ISSUE TITLE
Project Brutal Brutality/Brutal Doom Exclusive Keys Will Not Save

### ISSUE THREAD

**Issue by neosnake87** [pa1nki113r/Project_Brutality#1219]
As the title says, keys on the first page of controls page will not save. Like kick, flashlight, etc. Have tried several things. Like making sure the folder or files are not read only. Granting additional permissions to myself, all users, system, all application packages. I even changed the PB zip file into a folder and added it in ZDL Doom instead of the zip, so that mod would not be read only. I reset the INI multiple times too and changed it to portable mode. Tried clearing the INI file instead of deleting it too. Nothing works. Using the Github version.

**Comment by popguy12** [comment]
the engine tends to not save things sometimes if the game crashes
but in general i think its kinda just funky sometimes

im gonna assume this is a engine problem, you might wanna bring it up with them, they might be able to help ya more
