### ISSUE TITLE
Shotguns with Magazines will do two things: reload when full, and then when reloading will deplete ALL shotgun ammo from the inventory

### ISSUE THREAD

**Issue by itstreganometry** [pa1nki113r/Project_Brutality#1234]
Just something I'd like to bring to your attention as something who thoroughly enjoys this mod:

As the title states i've actively avoided picking up a shotgun with a magazine for this reason. I understand the addition of mags on a shotgun for increased reload time but when it comes at the cost of all my accumulated shotgun ammo....

Again im not sure if its a bug or something to do with my settings (which i've checked and IIRC didnt see anything that had to do with my issue)

Using PB staging e501bf7.pk3 however I noticed this was an issue when I used PB staging 428f6d4.pk3 and updated to the latest PB to see if the issue was mitigated.

link to the video since video was too big to post https://youtu.be/WW1GwUN57YE

**Comment by popguy12** [comment]
judging by the fact its reporting 9 ammo on the HUD still, im guessing this is a major conflict with something else you have loaded

ill be closing this for now, but if you can replicate it with the most recent build without any extra addons loaded feel free to reopen it
