### ISSUE TITLE
Improve performance of headshot targets by using AAPTR_TRACER

### ISSUE THREAD

**Issue by GrayFace** [pa1nki113r/Project_Brutality#1238]
Use AAPTR_TRACER instead of AAPTR_MASTER in A_Warp in PB_HeadshotHitbox to improve performance.

Turns out AAPTR_MASTER loops through all actors to validate master-child relationship each time it's used.

**Comment by generic-name-guy** [comment]
we are not using those shitass hitboxes anymore, all of the hitboxes are in the projectile code.
