### ISSUE TITLE
1 errors, 0 warnings while compiling Project_Brutality-master.zip:zscript.zc

### ISSUE THREAD

**Issue by douglasdock** [pa1nki113r/Project_Brutality#1256]
OS: Windows 10 (NT 10.0) Build 18362
    
GZDoom version g4.12.1
W_Init: Init WADfiles.
adding E:/arquivos jogos/doom/doom/gzdoom/gzdoom.pk3, 679 lumps
adding E:/arquivos jogos/doom/doom/gzdoom/game_support.pk3, 3308 lumps
adding ./../DOOMwload 1 & 2 ByGamer/DOOM 1 & 2 ByGamer/DOOM 2/doom2.wad, 2919 lumps
adding E:/arquivos jogos/doom/doom/gzdoom/game_widescreen_gfx.pk3, 214 lumps
adding ../Project_Brutality-master.zip, 54726 lumps
adding ../Project_Brutality-master.zip:titlemap.wad, 7 lumps
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device IOpenAL Soft on Alto-falantes (Realtek(R) Audio)
  EFX enabled
I_InitInput
I_StartupMouse
I_StartupKeyboard
I_StartupXInput
I_StartupRawPS2
I_StartupDirectInputJoystick
Vulkan device: IAMD Radeon RX 5700 XT
Vulkan device type: discrete gpu
Vulkan version: 1.3.277 (api) 2.0.299 (driver)
Max. texture size: 16384
Max. uniform buffer range: -1
Min. uniform buffer offset alignment: 16
Resolution: 1920 x 1080
I_Init: Setting up machine state.
CPU speed: 3793 MHz
CPU Vendor ID: AuthenticAMD
  Name: AMD Ryzen 9 3900X 12-Core Processor 
  Family 23 (23), Model 113, Stepping 0
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
GProject_Brutality-master.zip:zscript/pbvp/pbvp.zc, line 74: Function IsGrayed attempts to override parent function without 'override' qualifier

Execution could not continue.
1 errors, 0 warnings while compiling Project_Brutality-master.zip:zscript.zc

**Comment by generic-name-guy** [comment]
don't use the master branch, use pb_staging

**Comment by douglasdock** [comment]
thanks ...

**Comment by AlvaroOctavio** [comment]
Go to the file pbvp.zc, rename "pbvp.txt", open the text file and search the line "IsGrayed" and rename to "IsGrayedCompact"

**Comment by generic-name-guy** [comment]
This issue was already fixed, just updste
