### ISSUE TITLE
Excessive Damage on Shotgun Zoomed Buckshot

### ISSUE THREAD

**Issue by alexcraig** [pa1nki113r/Project_Brutality#126]
In recent revisions of the master branch the damage of the shotgun scoped buckshot is sometimes very high (comparable to a full blast from the quad shotgun). This doesn't occur with slugs, and it also doesn't occur with the non-zoomed buckshot. 

I believe this was introduced in commit 0cb10fd5c3f8ea950a893ed3ce80908b8f78d1e8, and it's happening because the FBF_NORANDOM flag is omitted from the A_FireBullets call in the zoomed buckshot case.

My apologies if this was actually intentional.

**Comment by secretagentjr** [comment]
this wasn't intentional,  i must've accidentally somehow removed the FBF_NORANDOM flag in my own personal build before sending the Pull Request with the most recent changes

**Comment by secretagentjr** [comment]
alright, a commit has been pushed on the shotgunoverhaulnew branch fixing this

**Comment by secretagentjr** [comment]
alright, this has been been fixed since the PR got accepted
