### ISSUE TITLE
[GZDoom 4.12.0+] GProject_Brutality-master.zip:zscript/pbvp/pbvp.zc, line 74: Function IsGrayed attempts to override parent function without 'override' qualifier

### ISSUE THREAD

**Issue by asc82** [pa1nki113r/Project_Brutality#1264]
Starting with [GZDoom 4.12.0](https://github.com/ZDoom/gzdoom/releases/tag/g4.12.0) it crashes, giving the following error message:
`GProject_Brutality-master.zip:zscript/pbvp/pbvp.zc, line 74: Function IsGrayed attempts to override parent function without 'override' qualifier`

Up until [GZDoom 4.11.3](https://github.com/ZDoom/gzdoom/releases/tag/g4.11.3) it ran without any issues.

**Comment by JMartinezHarmoniousPerson** [comment]
Use the Staging branch instead, that issue is already resolved there.

**Comment by asc82** [comment]
> Use the Staging branch instead, that issue is already resolved there.

Just tried https://github.com/pa1nki113r/Project_Brutality/tree/PB_Staging and indeed it's working perfectly fine, thanks a lot!

**Comment by JMartinezHarmoniousPerson** [comment]
@asc82 If your issue is resolved, feel free to close your report

**Comment by asc82** [comment]
It's fixed in https://github.com/pa1nki113r/Project_Brutality/tree/PB_Staging
