### ISSUE TITLE
Project brutality 3.0 gzdoom 4.12.2 error

### ISSUE THREAD

**Issue by Vlad23790** [pa1nki113r/Project_Brutality#1267]
I just try to launch project brutality 3.0 on gzdoom 4.12.2  windows and this error happening Project_brutality-master (7). zip:zscript/pbvb/pbvb.zc, line 74: Function IsGrayed attempts to override parent function without 'override' qualifier, I try to delete gzdoom ini and this error again, who can help?

**Comment by JMartinezHarmoniousPerson** [comment]
@Vlad23790 Use Staging instead of Master

**Comment by Vlad23790** [comment]
How to download pb staging?

**Comment by JMartinezHarmoniousPerson** [comment]
https://github.com/pa1nki113r/Project_Brutality/tree/PB_Staging @Vlad23790

**Comment by Vlad23790** [comment]
Thanks
