### ISSUE TITLE
Railgun scoped mode bug

### ISSUE THREAD

**Issue by the-ebola-wizard** [pa1nki113r/Project_Brutality#127]
When the railgun is zoomed in in railgun mode it seems to have infinite ammo.

**Comment by Havcom** [comment]
I wrote about this bug a long time ago, but I was ignored.

**Comment by the-ebola-wizard** [comment]
They need to increase the max amount of energy ammo you can carry too. It depletes far too quickly to the point that youre forced to save it for big en ounters or the cyberdemon

**Comment by goldenmobster** [comment]
That is rather odd that you have infinite ammo when using the Railgun [scoped] , What's weird is that the player doesn't exit it to reload it 
How odd

**Comment by JMartinez9820** [comment]
This bug is actually a duplicate from one of the issues in #110. This will be fixed when the Railgun overhaul comes into place.

**Comment by scaryred24** [comment]
Still bugged atm. Once resolved this will be closed.

**Comment by JMartinez9820** [comment]
This issue can now be closed as the newly implemented Railgun overhaul has fixed this bug.
