### ISSUE TITLE
Help i can't move

### ISSUE THREAD

**Issue by idontknowhatnametosuse009** [pa1nki113r/Project_Brutality#1287]
Like the title says, I can't move.

I've been trying to play project brutality for 2 days but I haven't been able to because of this bug

Every time I try to move the character just stays still

It does not move even using WASD or the directional arrows

The only way to move is using the dash but every time I press the dash+w,a,s or d key the console opens and returns me to the main menu

I'm using zdl, with the original doom 2 iwad, doom 2 reloaded mega wad and project brutality 3.0

Apparently this is only a problem with the mod because I have already tried it with the following mods:
-russian overkill
-brutal doom v22 beta
-brutal doom insanity nightmares
-complex doom clusterfuck

but none of them have given any problems and they all work perfectly.

Please, if anyone knows the solution, tell me as quickly as possible and thanks in advance.

**Comment by idontknowhatnametosuse009** [comment]
I forgot to mention, I can't jump or perform any related actions either.

I can only aim, shoot, throw grenades and use melee but nothing else.

**Comment by idontknowhatnametosuse009** [comment]
I also tried to solve it by uninstalling and installing gzdoom, uninstalling and installing zdl, same with doom 2, tried using console and many more but nothing works

**Comment by JMartinezHarmoniousPerson** [comment]
Delete GZDoom.ini which is in My Documents

**Comment by idontknowhatnametosuse009** [comment]
Like I said, I tried everything and doing that didn't work for me.

**Comment by idontknowhatnametosuse009** [comment]
MAP01 Infestation

Un execution aborted: division by zero.

Called from PlayerPawnBase.Bobweapon at Project Brutality-master.pk3:zscript/player/playerpawn.zc, line 2220

That is the message that appears every time I use the dash+any of the WASD keys

**Comment by generic-name-guy** [comment]
Make sure you're using either 0.1.0-alpha or 0.1.1-alpha and delete your GZDoom configuration file.

**Comment by idontknowhatnametosuse009** [comment]
Thank you, aparently I was using another version
