### ISSUE TITLE
Broken title screen at 2560x1440 resolution

### ISSUE THREAD

**Issue by ZachKnife4517** [pa1nki113r/Project_Brutality#1292]
![Screenshot 2024-07-11 121758](https://github.com/pa1nki113r/Project_Brutality/assets/147652500/18eb122d-2213-419f-bee9-740f5233ae44)
I'm using GZDoom on Windows with the latest release of Project: Brutality loaded in and nothing else.

**Comment by generic-name-guy** [comment]
Can you try disabling "menu clean scaling" in the options? Just search for it.

**Comment by ZachKnife4517** [comment]
Disabling that has fixed the issue in question. Thanks!
