### ISSUE TITLE
Slope and 3D sector line specials on binary map format currently not functioning.

### ISSUE THREAD

**Issue by GTD-Carthage** [pa1nki113r/Project_Brutality#131]
Hi, all. I'm one of the devs of ObAddon, an Oblige addon. Would just like to report that for some reason, slope and 3D sector line specials currently don't seem to work on the maps we generate when playing with PB currently - that is, the effects of these line specials don't seem to show up at all during play (slopes are missing, 3D floors are missing, and so on) and we have not encountered this issue with any other mods so far.

Beyond this, I'm not particularly sure if any other line specials may additionally be broken.

**Comment by MekBoss** [comment]
Is it orks normal on "default" gzdoom settings, just with doom1/2/plu-tnt-onia?
If no, its an obaddon bug.
Send log file of map creting into obaddon discord, to devs of it. It must be in the folder with oblige/obaddon.

**Comment by Cacodemon345** [comment]
Some remappings for the line exit specials were made for the fade effect upon exiting in certain ways, but I am not sure how this would cause this bug in any way...

**Comment by GTD-Carthage** [comment]
Just in case, I tried replicating the problem outside of Oblige/ObAddon and simply built a sample map via Doom Builder: (using traditional ZDoom line setup in Doom map format)

Here is a shot using line special 342 (plane floor and ceiling alignt at front) and 281 (legacy 3D floor).

This first shot is with with other mods (Legendoom and a few others) on GZDoom 4.1:

![Screenshot_Doom_20190511_090342](https://user-images.githubusercontent.com/20450951/57563730-aed50300-73d3-11e9-8c71-17956e5fea09.png)

This second shot is on Project Brutality, the (cacobranch on commit c811fba):

![Screenshot_Doom_20190511_095830](https://user-images.githubusercontent.com/20450951/57563733-c3190000-73d3-11e9-8dbb-1effcc19f513.png)

I hope this helps!

**Comment by Cacodemon345** [comment]
Did you attempt to remove the Translator line in one of the ZMAPINFOs?

**Comment by GTD-Carthage** [comment]
I did just now and the line specials have been restored!

![Screenshot_Doom_20190511_130931](https://user-images.githubusercontent.com/20450951/57565311-19933800-73ee-11e9-9ece-84ed2e21b613.png)

**Comment by Cacodemon345** [comment]
...and that's it. I will go remove the xlat definitions (not like I was too fond of fade out effect...)

**Comment by MekBoss** [comment]
Than its bug of xlat lump.
Not sure is it fault of PB or gzdoom.

**Comment by goldenmobster** [comment]
This has been resolved for now , if it happens again re-open this issue
