### ISSUE TITLE
Fix barrels going through teleporters

### ISSUE THREAD

**Issue by BlackOpsMarine** [pa1nki113r/Project_Brutality#1314]
As the title suggests barrels have been having an issue of going through teleporters when they aren't suppose to causing you to telegfrag them and die. Not sure if the cause is the mass of the barrels being altered making them easier to move or if they were recently changed to allow them to be moved or thrown through teleporters.

**Comment by generic-name-guy** [comment]
fullmetal man you're in the dev server just report bugs there

**Comment by BlackOpsMarine** [comment]
Check the server when you get a chance
