### ISSUE TITLE
Silenced Pistol Zero Ammo Supply reload problem

### ISSUE THREAD

**Issue by JMartinez9820** [pa1nki113r/Project_Brutality#132]
"Attempting to reload the pistol with a silencer with a zero ammo supply breaks the inventory, making it impossible to shoot and choose a weapon. There is no such problem with the double pistols."

https://youtu.be/qBXCG7t4ThE

Kudos to Havcom for reporting this on the PB Discord.

**Comment by ADoomedSpaceMarine** [comment]
According to the master beta zip when played, the console outputs these errors, both related to an actor trying to call non-existent states. At least that should give some insight on what needs to be done to potentially resolve the issue. The two states in question are NoAmmo and NoAmmoSilencer. Upon glancing at the decorate code, they are indeed missing. I don't know enough about how you guys intend to script weapons or the standards by which you guys are designing them upon, so I will work on a potential solution, but will leave it to the discretion of the contributors to decide the best manner of which to resolve the issue.  

Figure 1: Error output, found on bottom three lines of console, adjusted for positioning in last three lines.
![Console report](https://user-images.githubusercontent.com/48197087/57576031-d3e56800-740b-11e9-94c7-44eda5466b8a.jpg)

**Comment by ADoomedSpaceMarine** [comment]
It honestly may be fairly straightforward. Adding states for the two would be fairly simple as long as they jumped to the correct states upon change. For example: making sure it knows the jump needs to be declared to reload once pistol ammo is present again. So adding a noammo and noammosilenced may just need to jump back to ready3 (in the decorate code} to recheck all the needed checks for ammo. I will try to mention the fix on the discord and see if anyone is knowledgeable about how to proceed about it.

**Comment by JMartinez9820** [comment]
I have fixed the issue myself. For those experiencing that issue, download this here. You may need to start a new game for this to take effect.
https://drive.google.com/file/d/1-0cJAwJJe-5w0Jcebwg1nWLIczN2qd2D/view?usp=drivesdk

**Comment by JMartinez9820** [comment]
Issue now resolved, thread closed
