### ISSUE TITLE
Game doesn't load at all.

### ISSUE THREAD

**Issue by NutMaster6942** [pa1nki113r/Project_Brutality#135]
GZDoom version: 4.1.1 (Same thing happened with 3.7.2 and 3.6.0)
Error: "Script error, "PB3.pk3:actors/weapons/slot6/m2plasma.dec" line 794: SC_GetNumber: Bad numeric constant "M221"."

**Comment by Cacodemon345** [comment]
Wait until one of the PRs is merged.

**Comment by JMartinez9820** [comment]
Or use this fix until one of the PR's is merged. Load after PB.
https://drive.google.com/file/d/16LYMCrbVoYMg74KRRUY_VvQa3idpa5zz/view?usp=drivesdk

**Comment by ADoomedSpaceMarine** [comment]
I ended up putting the fix on the last pull request I initiated. It was due to a Mk2 plasma rifle sprite not having a timing value. Fixed by placing a one at the end of line 793. Just waiting for PR approval.

**Comment by JMartinez9820** [comment]
New link for the FatalErrorFix due to my getting request access emails from some users.
https://mega.nz/#!CrRVzKRI

**Comment by JMartinez9820** [comment]
This issue has been fixed since late last month. NutMaster6942, this issue can be closed.
