### ISSUE TITLE
Lose all ability to switch weapons when throwing an enemy

### ISSUE THREAD

**Issue by XP47JSuperbolt** [pa1nki113r/Project_Brutality#137]
Throwing an imp makes you unable to switch weapons and you're stuck unable to attack

**Comment by MekBoss** [comment]
Known bug.
Check solution here
https://github.com/pa1nki113r/Project_Brutality/issues/116

**Comment by goldenmobster** [comment]
> Known bug.
> Check solution here
> #116

Then it that case it's a replicate Issue 
Closed
