### ISSUE TITLE
Guided rocket launcher

### ISSUE THREAD

**Issue by WolVexus** [pa1nki113r/Project_Brutality#138]
Firing a guided rocket locks my current weapon to the rocket launcher and I can't switch weapons with next/previous weapon or by weapon slot keys. Also unable to deactivate guided mode

Replication - https://media.giphy.com/media/YWzoVJLPYDVL1NI7nf/giphy.gif

**Comment by goldenmobster** [comment]
Link is Expired @WolVexus

**Comment by goldenmobster** [comment]
I just checked and this issue/problem does not happen , I have the Updated Build [WIP] and i was able to switch weapons just fine
So which means this issue can be closed now
