### ISSUE TITLE
My Project Brutality crashed

### ISSUE THREAD

**Issue by YuyukoSS** [pa1nki113r/Project_Brutality#139]
It has been the issue for me since May 1st release.
Please fix this ASAP, pa1nki113r.
This is my full GZDoom log:
OS: Windows 10 (or higher) (NT 10.0) Build 17763
    
M_LoadDefaults: Load system defaults.
Using program directory for storage
W_Init: Init WADfiles.
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Games/GZDoom 3.7.2 x64 - Project Brutality/gzdoom.pk3, 635 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Games/GZDoom 3.7.2 x64 - Project Brutality/zd_extra.pk3, 132 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/wads/DOOM2.WAD, 2919 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip, 39177 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip:dmlevels.wad, 40 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip:e2m8.wad, 11 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip:e3m8.wad, 11 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip:psxlevels.wad, 42 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip:terrain.wad, 260 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip:testmap.wad, 13 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip:titlemap.wad, 7 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Project Brutality - 2019-05-09.zip:xhairs.wad, 94 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/target-spy-1.8.pk3, 280 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Perfect_doom/Weapon Wheel.pk3, 16 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/beamflashlight.pk3, 8 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/HXRTC_Project_Golden_Edition_Update_07-07-2018/JPSPECIALPOWERS3IN1_V1.2.PK7, 46 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/MapPack/jpcp/JPCP.wad, 2135 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Heavy Graphic/fixed_skies/D2SKY.pk3, 3 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Heavy Graphic/HOOVER1979_UltraHD_Texture_Pack_02102018-1k/HOOVER1979_UltraHD_Texture_Pack_02102018_Main_file-1k.pk3, 634 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Heavy Graphic/HOOVER1979_UltraHD_Texture_Pack_02102018-1k/HOOVER1979_UltraHD_Texture_Pack_02102018_Doom_2_Override-1k.pk3, 13 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/Heavy Graphic/Liquidpatchv2.pk3, 203 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/TouHou DOOM Music v2 - Copy (2).pk3, 246 lumps
 adding C:/Users/Daniel McFly/Desktop/Games/Doom/NekitoBlux001 Alterations.wad, 334 lumps
I_Init: Setting up machine state.
CPU speed: 2904 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Family 6, Model 142, Stepping 9
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 HyperThreading
I_InitSound: Initializing OpenAL
  Opened device OpenAL Soft on Speakers (Realtek High Definition Audio)
  EFX enabled
V_Init: allocate screen.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
Invalid data encountered for texture Project Brutality - 2019-05-09.zip:sprites/weapons/ssg/thumbs.db
Invalid data encountered for texture Project Brutality - 2019-05-09.zip:textures/thumbs.db
Attempting to remap non-existent texture M_DOOM to M_DOOMPB
Attempting to remap texture SKYEAR5 to non-existent lump SKYEAR5HD
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
Attempt to get invalid state FinishInspect from actor Shot_Gun.
Script warning, "Project Brutality - 2019-05-09.zip:actors/items/ammo/genericammo.dec" line 77:
Icon 'NULL' for 'TankAmmo' not found

Script warning, "Project Brutality - 2019-05-09.zip:actors/items/ammo/genericammo.dec" line 96:
Icon 'NULL' for 'MechAmmo' not found

Script warning, "Project Brutality - 2019-05-09.zip:actors/items/ammo/genericammo.dec" line 116:
Icon 'NULL' for 'HeavyMachinegunAmmo' not found

Script warning, "Project Brutality - 2019-05-09.zip:actors/items/ammo/genericammo.dec" line 135:
Icon 'NULL' for 'MechRocketAmmo' not found

Script warning, "Project Brutality - 2019-05-09.zip:actors/items/ammo/genericammo.dec" line 153:
Icon 'NULL' for 'MechLaserAmmo' not found

Script warning, "Project Brutality - 2019-05-09.zip:actors/items/ammo/genericammo.dec" line 172:
Icon 'NULL' for 'MechMOrtarAmmo' not found

Script warning, "Project Brutality - 2019-05-09.zip:actors/items/ammo/genericammo.dec" line 191:
Icon 'NULL' for 'HelicopterRocketAmmo' not found

Bad hex number: no
Script error, "Project Brutality - 2019-05-09.zip:actors/gore/gore2.dec"line 713:
NODELAY may only be used immediately after Spawn:
Script error, "Project Brutality - 2019-05-09.zip:actors/gore/gore2.dec"line 795:
NODELAY may only be used immediately after Spawn:
Script warning, "Project Brutality - 2019-05-09.zip:actors/player/player.dec" line 25:
Tried to define class 'IsTacticalClass' more than once. Renaming class to 'IsTacticalClass@Project Brutality - 2019-05-09.zip@actors/player/player.dec'
Bad hex number: no
Attempt to get invalid state NoAmmoSilencer from actor BDPistol.
Attempt to get invalid state NoAmmo from actor BDPistol.
Attempt to get invalid state NoAmmo from actor BDPistol.
Script warning, "Project Brutality - 2019-05-09.zip:actors/weapons/slot2/dualpistol.dec" line 5:
Tried to define class 'PB_PistolFireAnimation1' more than once. Renaming class to 'PB_PistolFireAnimation1@Project Brutality - 2019-05-09.zip@actors/weapons/slot2/dualpistol.dec'
Script warning, "Project Brutality - 2019-05-09.zip:actors/weapons/slot2/uacsmg.dec" line 753:
Icon 'ATFLA0' for 'SMGAmmo' not found

Script warning, "Project Brutality - 2019-05-09.zip:actors/weapons/slot4/hmgweapon.dec" line 38:
Icon 'HMGNA0' for 'HMGAmmo' not found

Execution could not continue.

Script error, "Project Brutality - 2019-05-09.zip:actors/weapons/slot6/m2plasma.dec" line 794:
SC_GetNumber: Bad numeric constant "M221".

**Comment by JMartinez9820** [comment]
For the M2 error fix, use this until one of the PRs is merged.
https://mega.nz/#!CrRVzKRI!U1GtPtBIaDFyUedMkS9xqOtK-FXy0xuwP0p9LCdyN0Y

**Comment by JMartinez9820** [comment]
The crash issue with M2 has now been fixed, you are free to redownload the github build if needed. Otherwise, this issue can be closed.

**Comment by JMartinez9820** [comment]
Once again, this issue is now resolved. This issue can be closed

**Comment by YuyukoSS** [comment]
Sorry for not closing the issue.
Will do in the moment
