### ISSUE TITLE
Adding EasyKey parameter in difficulty definitions in zmapinfo doesn't work

### ISSUE THREAD

**Issue by AffanDede** [pa1nki113r/Project_Brutality#140]
Normally, in every mod I've come across, adding in the easykey parameter in mapinfo or zmapinfo shows the location of keys on automap. However, PB3 is the only mod that easykey does not work.

**Comment by AffanDede** [comment]
Normally, in every mod I've come across, adding in the easykey parameter in mapinfo or zmapinfo shows the location of keys on automap. However, PB3 is the only mod that easykey does not work.

**Comment by JMartinez9820** [comment]
Issue can be closed due to to no replies since post.

**Comment by Qinus** [comment]
Line 416-528 in DECORATE are causing it not to work. I'm guessing because the keys are being renamed

**Comment by lumin8shun** [comment]
@JMartinez9820 
I've made the changes in DECORATE that you've commit in your branch for this issue on my own DECORATE.
(eg. ACTOR BlueKeyCard : CustomInventory Replaces BlueCard changed to ACTOR BlueKeyCard : BlueCard)

From that change, It shows the key in automap as black (where I think its supposed to do the colour of the respective key).
I also found that when picking up the key, it doesn't add to my inventory and softlocks me in levels as unable to open any doors.

Unless there is a change outside of this commit that resolves the above?
(I'm new to bug reporting\testing so please excuse my lack of understanding)
