### ISSUE TITLE
Doomguy One Liners Option is Broken 

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#141]
The Option ''Disable Auto-Doomguy talk'' to turn off the Doomguy one liners doesn't work , even after disabling it

This has been an issue/problem since 2018

**Comment by goldenwarriorgw** [comment]
The Option ''Disable Auto-Doomguy talk'' to turn off the Doomguy one liners doesn't work , even after disabling it 

This has been an issue/problem since 2018

**Comment by JMartinez9820** [comment]
Not a top priority at this moment. To be fair, if its been that long, imo it should be scrapped.
