### ISSUE TITLE
Chaingunner/Commander Disappearance 

### ISSUE THREAD

**Issue by goldenmob72** [pa1nki113r/Project_Brutality#142]
When the Chaingunner/Commando is bleeding out the body [corpse] disappears , this happens when you don't kill it fast enough while its bleeding out

It happens when the Chainnguner or Commando's bleeding out animation is done

**Comment by goldenmobster** [comment]
Here's a video of what I was talking about https://youtu.be/AinaQCPStk8

**Comment by JMartinez9820** [comment]
This issue (especially the Rifle Commando) is now fixed on my pull request, #266. For some reason the DeadAssRifleCommando actor was spawning either a nonexistent sprite or misnamed sprite, now I fixed it to call the correct sprite.
