### ISSUE TITLE
No FreezerTrailSparksSmall Actor in FreezerRifle (Freezer.dec)

### ISSUE THREAD

**Issue by SoCalBryan** [pa1nki113r/Project_Brutality#144]
Hey I  was thinking about using the freezer rifle in another project and could not find the Actor Class FreezerTrailSparksSmall specified in the "ACTOR FreezerBall : FastProjectile" code lines 491 and 503 and also in "ACTOR CryoShot : FastProjectile" lines 611 and 622

Thought it might be in ACS but then noticed that not all the compiled ACS files have sources in the src folder.

I browsed thru the issues list and did find a Issue #90 .
maybe the missing actor is a contributing problem to it.

**Comment by JMartinez9820** [comment]
@SoCalBryan Care to explain this in further detail? Otherwise, this thread can be closed.
