### ISSUE TITLE
M2 Plasma Rifle issues

### ISSUE THREAD

**Issue by Nevermore2790** [pa1nki113r/Project_Brutality#146]
Once equipped with the Lightning Gun Upgrade for the M2 Plasma, the upgrade doesn't work even if it is on. It just shoots the same projectile as if it's normal M2. Stun Bomb still works though.

It always goes inspect mode when the M2 is equipped or doing things like using the special key without the Dual wield or the Upgrade.

The reloading issue while the Lightning Gun is active is still there though.

I think there are still other issues with this weapon?

**Comment by JMartinez9820** [comment]
The M2 always going into the weapon respect animation when selected is a failsafe. Its currently put in place to check if the animation works properly and doesn't bug out.

**Comment by JMartinez9820** [comment]
This issue can be closed since all of these issues are resolved in the newest commit.

**Comment by JMartinez9820** [comment]
Sorry to bother again, but all of these issues are now fixed since the M2 Plasma Rifle overhauled. You can now close this issue. If any problems come back, feel free to re-open it.
