### ISSUE TITLE
Freeing marines crashes the game.

### ISSUE THREAD

**Issue by SMG54321** [pa1nki113r/Project_Brutality#148]
Whenever i try to free a marine, the game boots me to console and repeats this a bunch:

VM EXECUTION ABORTED: TRIED TO READ FROM ADDRESS ZERO
CALLED FROM MBLURHANDLER. NETWORKPROCESS AT
PROJECT_BRUTALITY-MASTER.PK3:ZSCRIPT, LINE 540

Can you fix it please (maybe even get them to say "let's rock" when you free them).

**Comment by goldenwarriorgw** [comment]
I'm sorry that you are having this issue , In the Main Menu Go to Gameplay Options then Enable ''REPLACE CAPTURED MARINES'' it replaces the capture marines with Partial Invisibility  

Do that until the Issue is fixed/patched
