### ISSUE TITLE
Dual Plasma Rifles reloading even with full capacity

### ISSUE THREAD

**Issue by Nevermore2790** [pa1nki113r/Project_Brutality#149]
You can still reload the Dual Plasma Rifles even with full clip.

**Comment by JMartinez9820** [comment]
Issue can be closed due to no responses.

**Comment by JMartinez9820** [comment]
@Nevermore2790 This will be fixed in pull request #375 . It can be closed for now .

**Comment by JMartinez9820** [comment]
This issue can be closed. Was fixed in latest commit following the dual wield overhaul.

**Comment by JMartinez9820** [comment]
This issue can now be closed. Fixed in latest PRs
