### ISSUE TITLE
Invisible SGL [Super Grenade Launcher] Pickup

### ISSUE THREAD

**Issue by goldenwarriorgw** [pa1nki113r/Project_Brutality#151]
The Pickup for the SGL [Super Grenade Launcher] is Invisible , it may look like it's not there but it actually is there

**Comment by DR01D-Qs** [comment]
I've been able to see that it's not actually invisible, it's just hidden under the floor, maybe the sprite is just shifted

**Comment by Emircan34** [comment]
check the discord hotfix channel i shared a hotfix

**Comment by JMartinez9820** [comment]
Golden, feel free to close this issue as it is now resolved

**Comment by scaryred24** [comment]
Issue resolved. If it rears its ugly head up again, just reopen it.
