### ISSUE TITLE
Crash when picking up shotgun upgrade while already having it

### ISSUE THREAD

**Issue by DR01D-Qs** [pa1nki113r/Project_Brutality#152]
Been playing latest Extermination Day at the date (so called pre-beta X), DeathWish progression, Man and a Half difficulty. Picked up a shotgun upgrade on Eday01. Then at Eday02 I'm picking up another one - the game hangs. 100% reproducible for me. Tried doing logfile but it doesn't write any useful info.

Mods:
EdayPreBetaX.pk3
Project_Brutality-master.pk3
SpriteShadow_v1.5.pk3
DoomMetalVol4.wad

GZDoom g4.1.2

**Comment by JMartinez9820** [comment]
Download this fix until a fix is implemented in a pull request. You may need to start a new game for this to take effect.
https://drive.google.com/file/d/1kRuqbMLe5dO_8z6yRHCwqI2__56lckhW/view?usp=drivesdk

**Comment by DR01D-Qs** [comment]
> Download this fix until a fix is implemented in a pull request. You may need to start a new game for this to take effect.
> https://drive.google.com/file/d/1kRuqbMLe5dO_8z6yRHCwqI2__56lckhW/view?usp=drivesdk

Yep, no crashes now. Wasn't a huge deal, just had to disable the upgrade in settings, but thanks.

**Comment by JMartinez9820** [comment]
Feel free to update to the newest github build as this issue is not resolved. Otherwise, issue can be closed

**Comment by JMartinez9820** [comment]
The newer Github commits to Project Brutality have now resolved this issue. Feel free to close this issue if necessary.
