### ISSUE TITLE
Weird auto aim in all bullet weapons

### ISSUE THREAD

**Issue by pO0P3R125** [pa1nki113r/Project_Brutality#153]
The auto aim for some reasson affect all the bullets weapon and make things like shooting to the ground (some gib, body or 3d models in water), so no matter what i done there its that auto aim what make unplayable some maps where its so many monsters

**Comment by MekBoss** [comment]
PB is not supposed to play with autoaim.

**Comment by pO0P3R125** [comment]
it's off, and it is assumed that weapons should not have it

**Comment by MekBoss** [comment]
Again, you have turned off autoaim but gzdoom act like it turned on?
If yes, delete you gzdoom ini file.

**Comment by goldenwarriorgw** [comment]
Autoaim is only for Vanilla Doom , Not PB

**Comment by Hedronmx** [comment]
I am having the same problem, autoaim is off in gzdoom and it shoots to the ground. I even edited de gzdoom.ini file to autoaim=0

**Comment by pO0P3R125** [comment]
Ok, fix it, just activate smart self-image avoiding allies, even if you get too close to a gib, it will shoot to the ground.

**Comment by goldenmobster** [comment]
We need more information and detail on this , so for now this issue is closed
