### ISSUE TITLE
Pistol

### ISSUE THREAD

**Issue by cacy17** [pa1nki113r/Project_Brutality#156]
When the pistol runs out of ammo it doesn't allow you to select any other weapon.

**Comment by JMartinez9820** [comment]
This bug has already been reported. The result was an invalid actor involving the NoAmmoSilencer actor. I made a fix on another issue I made, but I will post it here. You may need to start a new game for this to take effect.
https://drive.google.com/file/d/1-0cJAwJJe-5w0Jcebwg1nWLIczN2qd2D/view?usp=drivesdk

**Comment by goldenwarriorgw** [comment]
Also @cacy17  , when you open a issue please provide a better name/title , that way we can know what the issue is concerning

**Comment by JMartinez9820** [comment]
This issue has now been fixed in the newest update. This issue can now be closed.

**Comment by JMartinez9820** [comment]
This issue should be closed as this is now resolved
