### ISSUE TITLE
evil grenade bounce...

### ISSUE THREAD

**Issue by APoniatowski** [pa1nki113r/Project_Brutality#157]
recently blew myself up with a grenade (not the GL, the equipment handgrenade), where I chucked it directly/straight down a hole and bounced back up to literally right under my feet, blowing me up... is it possible to scale back on the bouncing (virtically)?

throwing it horizontally is not a problem... just throwing it straight down a shaft/hole is, unfortunately.

**Comment by goldenmobster** [comment]
We need more info on that , if you can provide/show a video on how that happens that would be helpful

**Comment by pa1nki113r** [comment]
Unable to replicate this issue.
