### ISSUE TITLE
guided static missile bug

### ISSUE THREAD

**Issue by hyperJJmaster** [pa1nki113r/Project_Brutality#159]
when you shoot you can not change weapons or you can not do melee attacks or offend or a secondary attack so the only way out of that is to kill yourself, possibly get out of the level or make the missile explode

look it
https://youtu.be/3qsPgCNcFpA

**Comment by JMartinez9820** [comment]
The latest stable version LZDoom breaks the guided rockets. Please upgrade to GZDoom 3.8.1 Vintage, or use this test build of LZDoom I got from DRD before it was removed. This is not a PB problem, its a LZDoom/GZDoom issue. It says x86 but it works on x64.
https://mega.nz/#!mypHRSzA!RSJVFpTQSa5vMEiQ3tD5WsbAipzkrZwsEvF8GJtEtEo

**Comment by JMartinez9820** [comment]
This issue can be closed as it has been resolved in beta LZDoom releases. Please check this page more often for LZDoom betas. It says GZDoom Vintage but LZDoom builds can be found there too.
https://devbuilds.drdteam.org/gzdoom-vintage/

**Comment by JMartinez9820** [comment]
As this is now resolved with new versions of GZDoom and LZDoom, this issue can be closed
