### ISSUE TITLE
M1 Dark Matter Pulse Rifle glitch

### ISSUE THREAD

**Issue by HyperExia** [pa1nki113r/Project_Brutality#163]
When you have the Dark Matter rifle in hand, when you climb up a ledge, it switches to the plasma rifle sprite. Not a major issue, but it does irk me here and there.

**Comment by goldenmobster72** [comment]
When you report a bug/issue please provide a Image, video, or  Gif. That would be very helpful

**Comment by JMartinez9820** [comment]
This should be fixed in pull #442, will test to see if it does.

**Comment by JMartinez9820** [comment]
Update: Can confirm that pull #442 has fixed this bug. When that pull request gets merged, this can be closed.
