### ISSUE TITLE
Railgun scoped mode glitch/bug

### ISSUE THREAD

**Issue by n00binator230** [pa1nki113r/Project_Brutality#164]
When scoped in, there will be a second "scoped in" view in the bottome left corner. It isn't picture-in-picture zoom, as the image in the bottom left corner has the same level of zoom as the rest of the screen. I would say this is fairly annoying, but the gun is still usable. Attached is a screenshot for a better view on this issue.

![Screenshot_Doom_20190621_233054](https://user-images.githubusercontent.com/51970589/59949963-4b7fcb80-947d-11e9-93ad-f4eac936861e.png)

**Comment by JMartinez9820** [comment]
Set your screen size to 11. Press the -/_ or =/+ to change your screen size. In this case, press the =/+ key. This problem happens on screen size 10 or lower. You can also go into Display Settings and change the Screen Size to 11.

**Comment by n00binator230** [comment]
Thank you very much Martinez
