### ISSUE TITLE
non functional inventory items

### ISSUE THREAD

**Issue by the-ebola-wizard** [pa1nki113r/Project_Brutality#167]
The electropods and swarmers are still complety non functional. Plz fix. I can select them in my inventory but i cannot use them

**Comment by JMartinez9820** [comment]
I believe this has already been reported. Swarmers and Electropods are bound to get overhauled, but at a later phase in development.

**Comment by the-ebola-wizard** [comment]
Its still obnoxious. There are areas in maps of chaos where they would be incredibly useful. Such as the tricks and traps level or dead simple

**Comment by scaryred24** [comment]
Duplicate of #59. Please check previous opened or closed issues before making a new one.
