### ISSUE TITLE
Plasmagun M.2 first animation repeat

### ISSUE THREAD

**Issue by Vampire2008** [pa1nki113r/Project_Brutality#168]
First select weapon animation for Plasmagun M.2 repeats every weapon select.

**Comment by JMartinez9820** [comment]
The M2 Plasma Rifle Weapon Respect animation repeating is not an issue, its something called a fail-safe. The fail-safe is put in place to check if the weapon respect animation plays properly and does not bug out. The Nailgun and Deagle did this in the past. Its good practice to do.

**Comment by JMartinez9820** [comment]
The failsafe has been removed and it resolved. This issue can now be closed.
