### ISSUE TITLE
Toggle Equipment not working

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#170]
The Toggle equipment key is not working. If I press it I get:

P_Start Script: Unknown script "Proximity Mine Hotkey"

This means I can only use grenades. Mines are unusable.

**Comment by MekBoss** [comment]
Try rebind keys for equipment.

**Comment by goldenwarriorgw** [comment]
it also depends which GZDoom Version you are using

**Comment by TonyH1234** [comment]
Which version should I use? I'm using the latest beta.

**Comment by goldenwarriorgw** [comment]
Probably the Latest Or Vintage if you have low end PC, also when items/Equipment aren't working? Are you referring to the Electropods and Swarmers?

**Comment by TonyH1234** [comment]
They don't work either. But I was specifically referring to mines and grenades. Can use grenades but can't switch to mines.

**Comment by TonyH1234** [comment]
I don't know if this helps to fix this bug, but if I bind Activate Equipment to z , and Toggle Equipment to Mouse 3, I get this in the Gzdoom.ini file:

Z=grenadetoss
Mouse3=usemine

I believe this is a leftover from an earlier version of PB 3.0 dated 21 Jan 18

And as I mentioned earlier, inventory items such as Electropods and Swarmers don't work either.

**Comment by goldenmobster** [comment]
This is not Issue/Bug , this is more of a Discussion 

Closed
