### ISSUE TITLE
Using a Zombie as a meatshield crashes the game

### ISSUE THREAD

**Issue by LucianM1** [pa1nki113r/Project_Brutality#171]
The game will crash after you throw the zombie off of you.
(VM EXECUTION ABORTED)
https://youtu.be/g-jBn6ZFmMs

**Comment by MekBoss** [comment]
Check pined messages in hotfix channel of PB discord server. There are fix for it.

**Comment by JMartinez9820** [comment]
This issue is actually a duplicate of #102.

**Comment by JMartinez9820** [comment]
This issue can be closed as it has been fixed.
