### ISSUE TITLE
Offends Taunt Hurts Enemies and Explosive Barrels 

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#174]
Watch the Video 
[Don't ask which add-ons i'm using pls] 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33986489/60552103-8266a480-9cfb-11e9-92ba-6c3ee16ce866.gif)

**Comment by scaryred24** [comment]
That bug is old and will be addressed in a future revision. Would be a simple fit but isn't top priority. If Brutal Doom V21 eventually had it fixed before launch than so would Project Brutality 3.0.
