### ISSUE TITLE
Freedoom [Both phases/iwads] Menu is wrong 

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#175]
The Menu in PB is messed when playing it with Freedoom , it's because of the Font that's causing this issue or problem 
![Fredoom+PB](https://user-images.githubusercontent.com/33986489/60615313-cb226a00-9d9c-11e9-8dd6-8e30e0d53286.PNG)

**Comment by JMartinez9820** [comment]
Its the HD font that is replacing the original font. Currently its not a priority to replace the font. Old versions of BDv21 had that too. Techincally this is not an issue.

**Comment by goldenwarriorgw** [comment]
Can't this Font be scrapped ? BD v21 doesn't use that font anymore

**Comment by scaryred24** [comment]
It's not top priority and will be changed in a later revision assuming if the development team agrees upon a new one. I also can't fully guarantee Freedoom support hence why a lot of us uses the retail iwads.

**Comment by goldenmobster72** [comment]
I just want to make a Quick Note here guys

PB is not the only mod that has HD/Custom Fonts
For Example :  When I loaded Gunaster 3,3 w/FreeDoom  Phase 1 the Menu [Episode Selection] was just fine
Take a look https://youtu.be/JxZG45mEIVM

**Comment by JMartinez9820** [comment]
One thing I saw is that Guncaster doesn't use a custom font for Episodes, while PB's (based on the HD font add on) does. This is not current a top priority at this moment. Most users and the devs use the retail IWADs so full Freedoom support is not guaranteed at this time.

**Comment by goldenmobster** [comment]
I would suggest that the Episode names (Ultimate Doom) get removed, the ones that are used in PB, to avoid any Issues & conflicts

![Capture2](https://user-images.githubusercontent.com/40510344/73612136-e5ccf380-45b6-11ea-86c7-b75698812a52.PNG)
