### ISSUE TITLE
Flashlight FPS drop

### ISSUE THREAD

**Issue by BoomDoomTomb** [pa1nki113r/Project_Brutality#176]
The flashlight for current build of PB is causing me severe framerate drops (>5fps) when aimed at long distances or in large open areas. As soon as I turn off the flashlight, framerate shoots back up to normal. Don't have the same issue with the flashlight currently used in BDv21.

I am unable to make the problem disappear by messing with all the dynamic light and rendering settings. Lowering resolution did not help either.

i7-3770k 3.9 GHz
16gb DDR3
GTX 1070ti
SSD

**Comment by MekBoss** [comment]
Flashlight just unoptimized now. It try light entire "long distances or in large open areas". So dont use flashlight in such map sectors.

**Comment by scaryred24** [comment]
Project Brutality does not have a working flashlight in this current state of the build nor was there ever was one. Add-ons are not a part of mod itself and should be treated as unrelated to the development of this mod. For whoever you got that flashlight from, consult the creator of that instead.

**Comment by BoomDoomTomb** [comment]
Ah, my mistake. Must've definitely been part of an add-on was accidentally using when the issue arose. Thank you for the clarification.
