### ISSUE TITLE
Menu Options For Graphically Taxing Features

### ISSUE THREAD

**Issue by webursey** [pa1nki113r/Project_Brutality#186]
This is more of a recommendation than an issue, and I'd like to apologize in advance if this stuff is very difficult, as my coding knowledge is limited. 
My "Gaming PC" is actually a low end Hewett Packard Laptop, meaning it's graphical abilities are limited. For the most part, the mod runs at a steady 40-60 fps on my machine, which is more than enough for me, as I'm used to gaming on it.
There are, however, certain situations that cause the frames to chug SIGNIFICANTLY, and through rigorous testing, I've discovered the causes, and have some suggestions to fix them.
Primarily, two things cause the lag. Combat on water, and large numbers of projectiles on screen. Namely chain gun fire. The source of the lag from enemy fire is obvious. The large number of dynamic lights for each round, and the large number of particles on impact. As for combat on water, I'm going to trace that to the ripple effects, simply because Brutal Doom has an option to turn them off, and when I do, the problem ceases for the most part.
This segues well into the core of my suggestion. If some menu options could be added to the rendering tab for these more taxing bits, the mod could potentially hold a steady frame rate on most low end machines. The water ripples should be easy enough, as the option already exists in brutal doom. As for the bullets, I would prefer if most of the game's dynamic lights were still there, but a low end setting for bullets specifically would be a godsend for frame rate. Specifically a setting that removes the dynamic lights and impact particles. This would allow me to stop pretending that the heavy lag when under any kind of chain gun fire is just a suppression mechanic, cause it's not, and i'm tired of lying to myself.
I don't want to sound like I'm demanding features, as the mod is an amazing piece of work to put out free of charge. I'm simply looking for a middle ground when it comes to graphics, and have managed to boil it down to the two main sources of dropped frames that I've noticed. Thanks for reading, and I'd love to see this added soon.

**Comment by JMartinez9820** [comment]
Github Issues is not the place to post suggestions. You can post this on the official Project Brutality Discord. If you need a link to it here you ago. Make sure to follow the verification process and have a profile pic/avatar on your Discord account.
https://discord.gg/2hJxXPc

**Comment by goldenmob72** [comment]
Not an issue, closing
