### ISSUE TITLE
Couple of bugs in the new update.

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#189]
Note: i know that this update it's super experimental but ill post it anyway.

1.-Ledge Grab: It's Bugged, when you use the  ledge grab on a surface you get stuck on place where you are climbed, also if you use new dash after that the "dash system" will be bugged af.
2.-Movement System: For some reason, when i go to the Left/Right or in zig zag you move faster when i don't want, specially in some tiny small places where you are from a high place, not jumping, i saw the bunny hop option and the strafe jump but this 2 options only work while jump, but this rarely happens.
3.-Jumping: idk if the "zmovement" affects(yeah i think it is) but the jump kick was ok before this update, now when you "jump+kick" the " lightly movement kick(to the front)" is null. 
4.-M2 Plasma upgrade:  this was also on the previous version some frames from the akimbo mode appear on  the m2 upgrade when you switch guns, also, if this not happens, you can get em unloading the m2 upgrade and reloading then this should happen.
4.5.-M2 plasma upgrade v2: when you are on akimbo and then you grab the  m2 upgrade, this will bug your m2 even if you drop and then grab a normal m2plasma.
5.-Drill Gun: if you look up close to a wall and then you shoot(on drill mode) the "missile/torpedo" will "boing" or "bounce" on the wall right to you, idk if this a bug.
6.-Barrels: Barrels crash/freezes the game if you grab them and if you put them back in their place(right click after you grab one) the game (like i said before) crashes/freezes.

Tested Using GZDoom 4.1.3 x64

**Comment by megaboyx90** [comment]
As far as 2 is concerned, the movement is snappier and more precise so it isn't going to be like before. Personally I don't have an issue with this, you can use walk mode or just adjust the settings in zmove. It takes some getting used to but overall I feel it's a very welcome change, Perhaps there could be a legacy doom acceleration option for those who want a more vanilla movement system.

**Comment by MekBoss** [comment]
Barrels still crash game?!
Why nobody push fix for this from discord server to master branch?

**Comment by scaryred24** [comment]
> 
> 
> Barrels still crash game?!
> Why nobody push fix for this from discord server to master branch?

Because it wasn't reported in a formal fashion. The posts would get buried fast and sometimes it gets overlooked. The more formal way of doing it would have been to report in on here as it was done or to submit a pull request to fix such a bug if you can provide that you have fixed it.

**Comment by Mr-Blazkowicz** [comment]
My bad guys, aparently the barrel's crash it's fixed, but the remain of the crash i mean the Vainilla melee hand sprite appears for some few seconds.

**Comment by scaryred24** [comment]
I will keep this open for anyone else who wants to report on it. After roughly a month goes by, this will be closed so if anything hasn't been addressed by then, just respond and I will reopen this.

**Comment by Mr-Blazkowicz** [comment]
hmmmm this is weird, i don't know if its a weapon that causes this, i started e1m1 with the beggining weapons then i grab a barrel, i did the thing and nothing happened(no crash) but after that late on some maps it crashes. maybe this it's caused for some weapon/upgrade in the inventory or something on the berserk packs, also i did this with the "give berserk" command and didn't crash.

**Comment by MekBoss** [comment]
Switch places this two lines
TNT1 A 0 A_TakeInventory("BarrelThrower",1)
TNT1 A 0 A_SelectWeapon("Melee_Attacks")
in actors/Weapons/Meatshields/BarrelThrower.dec, line 118 and 119 respectively to fix this bug.

If you throw barrel, barrel thrower, weapon which throw barrel, takes from inventory and destroys, but psprite still try call a_selectwepon function, from this non existing barrel thrower which produce error.

Cant do pull request myself, because my PB code too differs and 5 months behind actual PB version.

**Comment by JMartinez9820** [comment]
@MekBoss Actually, that is incorrect as it will crash the game. I recently found out that lines 133, 134, 144, and 145 in BarrelThrower.dec are causing the crash.
Just switch the places around these lines
TNT1 A 0 A_SelectWeapon("Melee_Attacks")
TNT1 A 0 A_TakeInventory("BarrelThrower",1)
in lines 133, 134, 144, and 145 to fix this issue.
BarrelThrower.dec can be found in actors/Weapons/Meatshields.

**Comment by JMartinez9820** [comment]
Issues 4 and 5 have been resolved. Care to share more info on other bugs so they can be replicated? Thanks.

**Comment by stalinator999** [comment]
items respawn and super powerups respawn gameplay options don't work

**Comment by JMartinez9820** [comment]
@Mr-Blazkowicz All issues I believe have been resolved. Ledge grabbing has been updated to ZMovement's system. Issue can be closed.
