### ISSUE TITLE
moving down stairs or over objects while walking causes you to suddenly move faster

### ISSUE THREAD

**Issue by megaboyx90** [pa1nki113r/Project_Brutality#190]
This is due to being in mid air for a slight second. I think there should be a jump speed slider for both running and walking so that this doesn't occur.

**Comment by MekBoss** [comment]
This is because of dusk movement code. I think same bug exist in original code.

**Comment by scaryred24** [comment]
This has been addressed and being worked on. We are well aware how much tweaking this may need. Now if the bug exists in the original code, then its really not our fault but rather on the creator's behalf. Otherwise be patient as we work out the movement issues.

**Comment by JMartinez9820** [comment]
I believe this has been fixed since ZMovement was updated to 3.0. Issue can be closed.

**Comment by JMartinez9820** [comment]
This issue should be closed. This may have been fixed since the update to ZMovement 3.0

**Comment by JMartinez9820** [comment]
This issue can be closed as ZMovement 3.0 has seemed to fix this problem.
