### ISSUE TITLE
Suggestion: Replace the current weapon sway script with Nash's

### ISSUE THREAD

**Issue by ADmeral97** [pa1nki113r/Project_Brutality#192]
Link to Nash's weapon sway mod: https://forum.zdoom.org/viewtopic.php?f=46&t=62634

**Comment by megaboyx90** [comment]
That looks bad compared the the current modified weapon sway in the mod

**Comment by scaryred24** [comment]
I'm not a fan of the weapon snapping to the center of the screen when it goes into the firing animation. It shouldn't just be the idle animation that would be applied to. Of course it can be tooled around to our liking. Not sure if this would be adopted over the current weapon sway system.

**Comment by JMartinez9820** [comment]
This is a suggestion, therefore this will be closed.
