### ISSUE TITLE
Jumping camera jerking movement is not suitable for b-hopping

### ISSUE THREAD

**Issue by Someone65** [pa1nki113r/Project_Brutality#193]
It's way too strong for the new movement system and is quite jarring because of it. Should be reduced or settings of ZMovement tweaked to fit.

**Comment by scaryred24** [comment]
We are well aware of this. The moment this was implemented and pushed to master, we were going to fine tune it.

**Comment by JMartinez9820** [comment]
ZMovement has now been fine tuned since April (iirc that is). This can be closed for now. If it still persists, then this can be reopened.
