### ISSUE TITLE
Super shotgun 3 hands when meleeing and dual wield reload bug

### ISSUE THREAD

**Issue by Someone65** [pa1nki113r/Project_Brutality#194]
When you quick melee while holding the super shotgun, the gun stays on the screen, making it appear as if you have 3 hands.

Firing all 4 shells when dual wielding the SSG and then reloading only reloads one SSG and not the other, making it unbalanced due to the fact that there is no reload time penalty for having 2 double barreled shots since the reload still loads 4 shells despite only showing 2.

**Comment by JMartinez9820** [comment]
Proper quick melee sprites for the SSG have not been made yet.

**Comment by JMartinez9820** [comment]
Dual SSGs have been overhauled, and the quick melee glitch is going to be fixed by me in a pull request.

**Comment by JMartinez9820** [comment]
Update: Quick melee two hands glitch is going to be fixed in pull #385.
