### ISSUE TITLE
Dual Wielding Pistols melee sprite glitch

### ISSUE THREAD

**Issue by Someone65** [pa1nki113r/Project_Brutality#195]
When you quick melee while dual wielding pistols, the non-dual wield sprite appears at the end of the animation in between the 2 dual wielded pistols.

**Comment by goldenmobster72** [comment]
Can you get Screenshots , Video , or a Gif of that Please ? That would help and explain a lot

**Comment by Someone65** [comment]
It's pretty consistently replicable. Just do exactly as I described and: https://gfycat.com/UnpleasantDependableLeveret

**Comment by scaryred24** [comment]
@Someone65 i have encountered this and took note of it a week prior to it being reported. I was just waiting to see who else would stumble upon this. 

I briefly discussed about it openly here: https://shigusegubu.club/notice/9lG8XQZr9tXwgl5Mfo

Jokes aside we are aware of the issue and will be addressed as soon as one goes back around and correct it.

**Comment by JMartinez9820** [comment]
This issue is should now be fixed after the newest commit. This issue can be closed.

**Comment by JMartinez9820** [comment]
This issue can now be closed following several new GitHub commits
