### ISSUE TITLE
Swarmer Pod-Pickup

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#196]
When Picking up the Swarmer Pod The Pickup Sound for it doesn't happen [Play]

**Comment by scaryred24** [comment]
Noted. Thank you for the report.

**Comment by JMartinez9820** [comment]
This issue can now be closed. Swarmers are no longer available as a backpack, meaning that they may be officially scrapped due to redundancy to PB's current arsenal.

**Comment by JMartinez9820** [comment]
This issue can be closed.
