### ISSUE TITLE
Portable Medkit/First Aid Kit-Pickup

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#197]
When picking up the Portable Medkit or First Aid Kit it uses a Health Pack Pickup Sound and not it's own sound, Unlike the Swarmer and Electro Pods, those two have their own Pickup Sounds

I find it weird that a Portable Medkit/First Aid Kit uses a Health Pack Sound and not it's own Pickup Sound

**Comment by scaryred24** [comment]
Noted. Thank you for reporting this.

**Comment by tunbridgep** [comment]
I have never actually seen a portable medkit appear, despite having them turned on in the options. What gives?

**Comment by JMartinez9820** [comment]
This issue can be closed due to it being from a deleted user.

**Comment by JMartinez9820** [comment]
Once again, this issue should be closed by collaborators due to this being opened by a deleted user. It was moved to #337 .
