### ISSUE TITLE
Imp Gore Issues

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#198]
When Blowing up a Dark or Savage Imp head it leaves behind regular Imp [Brown] gore behind

Take a look - https://www.dropbox.com/s/qn51jq443xpm8ih/ImpHeadGore.mp4?dl=0

**Comment by scaryred24** [comment]
Not top priority but will look at it in the future. Thank you for reporting this.

**Comment by JMartinez9820** [comment]
Once again, this issue should be closed by collaborators due to this being opened by a deleted user. It was moved to #337. Unless this issue still remains it can be open.

**Comment by JMartinez9820** [comment]
This issue should be closed. It has been moved to a single issue at #337.
