### ISSUE TITLE
Double jump breaks after using a tank

### ISSUE THREAD

**Issue by Wuzzle** [pa1nki113r/Project_Brutality#199]
What it says on the tin, entering and leaving a tank stops double jumping from working at all. The bug persists even after starting a new level and/or quitting the game.

**Comment by goldenmobster72** [comment]
How Odd and Weird...

**Comment by JMartinez9820** [comment]
This issue has actually been fixed since the latest commit when ZMovement was added as a part of the Player Movement overhaul. Update to the latest Github version of Project Brutality to fix this. However, you will need to start a new game if you made any progress in levels that involve tanks.

**Comment by goldenmobster72** [comment]
Yes. and therefore you can close this issue
