### ISSUE TITLE
[Gameplay] I think the HMG might be a bit too powerful

### ISSUE THREAD

**Issue by tunbridgep** [pa1nki113r/Project_Brutality#200]
This is NOT a technical issue or a bug. It is an issue of gameplay.

I think the HMG might be a little too good as a weapon. It seems to outdamage even the rocket launcher, has no chance to hurt the player, has unlimited range, and uses a modest amount of ammo.

What do you guys think? This gun makes the game WAY easier on higher difficulties.

I would personally slightly decrease damage and up the ammo usage or reduce clipsize, although it obviously should still be better than the regular chaingun or fill a different role.

For some comparisons: It takes 4 rockets to kill a green mancubus. It's about 4 seconds of firing, uses up the majority of a rocket clip, and you have to risk hurting yourself. Alternatively, you can kill one in under 2 seconds with about 20 bolts from the HMG, and won't need to reload for days.

On the flip side, the "fire lots of projectiles at once in a big burst" mode is totally useless. It probably needs a buff. I would reduce the time it takes to actually fire, and it's cooldown time.

on a completely unrelated note, there's a hilarious unintended side effect with the way enemy dodging works. In the normal game, enemies like cacodemons will quickly dodge through the air to avoid projectiles like rockets. This is fine, and looks good. But with the HMG, because it fires so many projectiles so quickly, they will often dodge multiple at the same time, sending them flying across large rooms at light speed. This is hilarious, but it looks and plays really wierdly. Maybe enemies should only be able to dodge 1 attack per second or something so they don't fly around in crazy directions at supersonic speeds.

**Comment by goldenmobster72** [comment]
it's fine just the way it is, why bother changing/editing something that people like to use ?

**Comment by tunbridgep** [comment]
I really don't mean to be rude, but "being something people like to use" is one of the worst justifications for keeping something the way it is that I have heard in my entire life.

People like the feeling of the gun, it's sound and the way it handles (except maybe the long cooldown I talked about above). But breezing through the game because a weapon is significantly more powerful than it should be is not a fun experience for a large number of people, me included.

The reality is neither of us are really in a position to accurately speak on behalf of what people generally like and dislike, as the vast majority of the users of this mod don't even comment.

I have given what I believe to be valid, objective reasons why the weapon is overpowered to the point of being completely broken. I really don't care if people like it or not. I guarantee you, people will like a more balanced game over a less-balanced one overall.

**Comment by tunbridgep** [comment]
I have given what I believe are objective reasons why the weapon is extremely overpowered to the point of being broken. Leaving something the way it is because people "like to use" it is one of the worst justifications I have ever heard to keep something the way it is (no offense). Having a more balanced game, I assure you, will result in a lot more fun for a lot more people in the long run. I highly doubt I am the only person who feels this gun is off-balance, which is half of the reason why I made this thread in the first place - to gather data and get different perspectives. If there's something I have missed in my reasoning, this is a good place to point it out.

So I guess I should ask - what do you think makes the gun fine? Sure, the gun feels great to use, and I wouldn't want the actual way it handles to change at all since it's really great and I can see why people love it (I also love it), it's just the actual damage amounts or DPS that I feel is wrong.

**Comment by secretagentjr** [comment]
It's an upgrade, also it's meant to be the best weapon of the Slot 4 category. however, i propose, that maybe instead of nerfing it, everything else gets buffed so it doesn't outshine them.  also the only reason to even use the HMG/Nailgun right now is for enemies who don't move around alot, like the mancubus, because it's projectile is slow as hell. The only reason even worth using it right now is because it chews through higher tier monsters. Picture it getting a nerf and the projectile speed stays the same, it's already slow, and just by using it you risk dying because of imps dodging the projectile. if it doesn't at least have a reason to use despite the projectile be so slow, the gun may as well just be worthless.

**Comment by tunbridgep** [comment]
Maybe projectile speed makes sense as well. I could see that being reasonable. Also buffing the other weapons could be good too, although IMO some of the tier two weapons are already absolutely amazing at taking out enemies (black hole generator).

The dodging thing I think is a real issue, Enemies jump around all over the place because they dodge per-projectile, rather than at a constant rate, so I have seen enemies jump to the other side of the room at near light speed to dodge my 5 nails. Maybe the nails don't need a speed buff, maybe the enemies need a slight reduction in how often they can dodge because it usually ends up looking ridiculous anyway. I have seen cacodemons "dodge" to the other side of a very large outdoor area.

I am a bit of a stickler for difficulty. If it was up to me, I would make the Tier 2 enemies even better than they are now because the tier 2 weapons are really good against them, I would say Tier 2 is actually easier than Tier 1 because of how much better that tier of weapons are against their respective enemies - the weapons got WAY better, the enemies got SOMEWHAT better.

Sorry for being rude before. I woke up on the wrong side of the bed this morning.

**Comment by Havcom** [comment]
Hey. What weapons are you talking about, I can’t understand? HMG is what? Nail gun? If so, then it is completely balanced and easy to use. At first I thought that he was even a little imbalanced, but then I got used to it, now it is a good spam machine + a powerful harpoon gun with a long reload time and a high consumption of ammunition. I don’t see anything bad here. Good weapon.
But the excavator in this modification is extremely imbalanced)) His missiles inflict very high damage, destroying even the most powerful enemies in a couple of shots, while the missiles do not cause damage to the player. At high levels of complexity, of course, the gun is indispensable and often helps me in critical situations, but for the sake of balance, it would be worth remodeling it a bit.

**Comment by Krigeris** [comment]
I agree and will probably nerf the weapon in my own files

**Comment by goldenmob72** [comment]
This is not an issue, Closing
