### ISSUE TITLE
Ammo Boxes/Packs-Sounds

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#201]
The Ammo Boxes (Or Packs) for the 9mm [Pistol or SMGs] and Rifles and Miniguns [and Nailgun] use the Ammo Clip/Magazine Sounds, Unlike the Shotgun Shells [Four] and Box (or Pack) they have their own Individual sounds

For Example:
When Picking up a 9mm Ammo Box or 5.56 Ammo Box they use the Ammo Clips/Magazine Sounds [Sometimes]. Not their own Individual sounds

**Comment by scaryred24** [comment]
This will be looked into at a later point in development. Thank you for the bug report.
