### ISSUE TITLE
Unmaker and DMR upgrade

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#206]
Just a suggestion, maybe the unmaker should be a weapon on its own right and not an upgrade for the flame cannon. I say this because the unmaker uses energy for ammo and the flame cannon uses gas. Once you pick it up all that gas can never be used.

Also wondering about the under barrel grenade launcher upgrade for the DMR. Is it functional?
I have never found it.

**Comment by Havcom** [comment]
unmaker can shoot like a fire cannon, therefore it is an upgrade for it. Use the key for additional weapon mode.

An upgrade for DMR sometimes comes across, but rarely. In my opinion, it is extremely useless, so it's good that you did not find it)))

**Comment by JMartinez9820** [comment]
Github Issues is not the place post any suggestions, its used to post any bugs. If you have a suggestion I would recommend posting it on the Project Brutality Discord. Join here if you haven't yet, otherwise, this issue can be closed.
https://discord.gg/2hJxXPc

**Comment by TonyH1234** [comment]
Oops! Sorry, I forgot to try the alternate fire mode for unmaker.
As for the DMR upgrade, I finally found it but doesn't seem to work. Alternate fire mode does nothing.

I have been trying to get into Project Brutality Discord but unsuccessfully. I go through the verification process but it doesn't take me back to Project Brutality Discord.

**Comment by Havcom** [comment]
An upgrade for DMR gives you ability to fire an underbarrel grenade launcher. To do this, press grenade throw key, and then again to reload grenade launcher for next shot.

**Comment by JMartinez9820** [comment]
@TonyH1234 You will need to add an avatar/profile picture on your Discord account to join the Project Brutality Discord. One of the bots kicks users without avatars/profile pics, was originally intended to prevent some banned user from joining the server with alt accounts, but also done to prevent spam accounts from joining. If you can, please add an avatar/profile pic on your Discord account you should be good to go.

**Comment by JMartinez9820** [comment]
Update. DMR upgrade is going to become the HDMR in the future, and I believe it will also retain the underbarrel grenade launcher  from the current DMR upgrade. Check #422 for more details.

**Comment by JMartinez9820** [comment]
Update: The DMR upgrade has been officially overhauled into the Heavy DMR. I will also close this because this is a suggestion, which doesn't belong on Github Issues.
