### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by kslyuen** [pa1nki113r/Project_Brutality#208]
Got a error with the most recent release

![error](https://user-images.githubusercontent.com/53952562/62805485-22afa600-babe-11e9-8d4a-ea8551e13250.JPG)

Execution could not continue.

Script error, "Project_Brutality-master.pk3:zmapinfo.txt" line 9:
Expected identifier but got integer constant '0x32' instead.

**Comment by JMartinez9820** [comment]
You are using GZDoom 3.6.0, which is now outdated. Project Brutality now officially requires GZDoom 4.1.3 (latest version) to run. If your computer can't handle GZDoom 4.1.3, you can try using GZDoom 3.9vpre Vintage beta or LZDoom.
GZDoom 3.9vpre Vintage beta can be found here: https://devbuilds.drdteam.org/gzdoom-vintage/
LZDoom can be found here on the center: https://zdoom.org/downloads

**Comment by kslyuen** [comment]
@JMartinez9820 Thanks for your help, much appreciated

**Comment by goldenmobster72** [comment]
Good work @JMartinez9820 
Alright, Pls close this issue @kslyuen

**Comment by JMartinez9820** [comment]
This issue can be closed at we resolved this issue.
