### ISSUE TITLE
Issue ·#209

### ISSUE THREAD

**Issue by LastManonEarth6604** [pa1nki113r/Project_Brutality#209]
Found this issue when playing the latest build.

![20190810_105321](https://user-images.githubusercontent.com/53973921/62822903-5fcc7480-bb60-11e9-9364-1c57938f79a8.jpg)

**Comment by JMartinez9820** [comment]
I would try disabling motion blur. Motion blur is inside the Rendering Options in the Project Brutality settings. Also, next time when posting an issue, please provide sufficient information on how the issue happened, and how it can be replicated. The dev team won't be able to fix issues if insufficient info is provided to fix an issue.

**Comment by LastManonEarth6604** [comment]
Motion blur was off.

**Comment by goldenmobster72** [comment]
Next time provide a better issue name/title please , that way we can know what issue we are dealing with

**Comment by MekBoss** [comment]
Add this 
if(!target) return;
line in 
 Project_Brutality/zscript/Monsters/ZombieMen/ZombieMan.zc  line 53 to fix this bug.

**Comment by LastManonEarth6604** [comment]
<img width="385" alt="1" src="https://user-images.githubusercontent.com/53973921/62840827-6e0cb480-bc76-11e9-856d-6b19a290a726.png">
Thanks MekBoss. As this is not an specific situation error, at least in gameplay, I am still trying with the change your suggested. Currently, it was steady and did not crashed. Will report back in case it does.

**Comment by JMartinez9820** [comment]
Updated the Zombieman fix to the latest version if needed
https://mega.nz/#!7n4RQYiA!B4OKLBqtk7LhZxSm1w6HU8v3kSUFnh3KMe5ex8_haQk

**Comment by JMartinez9820** [comment]
Issue should now be fixed in new commit, issue can now be closed
