### ISSUE TITLE
Some easy-to-fix issues

### ISSUE THREAD

**Issue by Sagan-Ro** [pa1nki113r/Project_Brutality#210]
Hello, awesome mod!  I have found the following issues, and most are simple to fix.  However, since I have been having to fix the first 3 myself for each of the past several releases on GitHub, it is getting a little irritating.  I am not sure what is up with the 4th issue, and the 5th may be something that just got overlooked in the graphical updates (though it was present in previous versions).  They are as follows:

1.  Demontech Rifle: Primary fire in incendiary mode uses 2 ammo a shot, caustic mode uses 1 ammo a shot
2.  Dual MP40s: reloading causes *three* magazines to drop, not two (one for each SMG)
3.  HMG upgrade: text says "Switching to AMMMO belt" (three M's?)
4.  Streaming BFG (don't know the name offhand): Trying to alternate weapon modes displays "Weapon special not available in classic mode" when NOT playing in classic mode.
5.  Upgraded pump shotgun: No longer appears to have the "add one to the chamber" when reloading from a completely empty weapon.

**Comment by goldenmobster72** [comment]
The MP40s haven't been overhauled yet , there's still several weapons to Overhaul

**Comment by JMartinez9820** [comment]
Some of these are not a top priority at this moment but will be looked into. Thank you for reporting this.

**Comment by JMartinez9820** [comment]
@Sagan-Ro All issues have been resolved with the exception of the Shotgun chambering. I can try to take care of that, and I can try to push a commit for testing.
