### ISSUE TITLE
Axe and Quick Melee Sounds 

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#211]
The Axe doesn't have it's own Pickup Sound Effect, it uses the Same sound for when using the Knife [Quick Melee/Slash]  

https://www.dropbox.com/s/hsg8yq7i9nrk312/KnifeandorAxeSounds.mp4?dl=0

It should have it's Pickup Sound because every weapon has it's own Pickup Sound

**Comment by tunbridgep** [comment]
While we are there, since this Axe was ported across verbatim from Brutal Doom, someone should probably also update it's sprites to the release version of Brutal Doom 21's, as those sprites look WAY better IMO

**Comment by BenjaminZuriel** [comment]
The Axe has already got a finished sprite set sitting on stand by ready to be used. Its just not a weapon that's on the high end task right now.

**Comment by tunbridgep** [comment]
The best part of collaboration is that people with different interests or priorities can work on different things.

If you've got this sprite set, I can have a look at implementing it. I can take a look at the pickup sound while I'm there.

**Comment by BenjaminZuriel** [comment]
I have the sprite set but its not a re skin its got new swinging angels etc.

**Comment by tunbridgep** [comment]
That's all good. I know DECORATE
