### ISSUE TITLE
Dual-Wielding system has serious issues

### ISSUE THREAD

**Issue by AlexThePianoNailer** [pa1nki113r/Project_Brutality#215]
Ok, i have found that the dual-wielding mechanics in PB test build is pretty broken.
Tested on latest Git build, without any other mods, GZDoom 4.2.0.

1) Some interactions with Revolver, like dropping while dual-wielding and switching back to it, crashes the game.
2) Second autoshotgun cannot be picked up, disallowing to dual-wield.
3) Player stocks up to 3 same weapons in inventory, obviously 3rd being redundant. Noticable when dropping weapons. This concerns only dual-wield'able stuff (30 DMR, .45 pistol, Revolver, SMG, Sawed-off Shotgun, M1/M2 Plasma Rifles). Surprisingly, MP40 works fine.
4) Also, dropping one weapon while in dual-wielding mode will not disengage dual-wielding.
5) Fully loaded dual-wielded M1 Plasma Rifles can always be reloaded. If doing so with 30 DMR, it changes its sprite to single-wielded DMR.
6) I must add that unloading often works incorrectly on dual-wielded weapons. Although that is classified as minor bug.

I'm not mentioning "three hands" sprite glitches since they were already highlighted.

My programming skills aren't good enough to help you guys, otherwise i would've fixed it all myself. All I can propose, apart from polishing the mechanics, is a complete removal of Dropping/Unloading features, as these bring lots of troubles and instability. I cannot say they're not cool though.

**Comment by JMartinez9820** [comment]
Is there a way that the Revolver one can be redone/replicated? These are not a top priority but we will take a look at these. Thank you for reporting.

**Comment by AlexThePianoNailer** [comment]
> Is there a way that the Revolver one can be redone/replicated?
Excuse me, didn't quite get  question.

**Comment by JMartinez9820** [comment]
@AlexThePianoNailer What I meant is to give out instructions on how to recreate the Revolver crash so the devs can find a way on fixing the issue. This is very important to the team as the team needs information on replicating bugs so they can find out what is causing the problem and fix it. Without sufficient information, the devs will run headless, won't know what to fix and the problem will not be resolved.

**Comment by AlexThePianoNailer** [comment]
Get 2 revolvers in the game -> Dual-wield -> Drop one then pick up -> Switch back to revolver
???
PROFIT!

**Comment by AlexThePianoNailer** [comment]
Sometimes it may crash on dropping part already.

**Comment by Havcom** [comment]
In addition to this, I will write a couple of my comments:
-- If you take m2 Plasma normal in both hands and pick up an upgrade for this weapon, then it will forever remain in a state taken in both hands.
-- Reloading of double weapons also raises a lot of questions. By the way, there is an interesting glitch)) If you take a weapon in both hands, shoot almost all bullets in store, leaving a couple of bullets before reloading and then switch to normal mode of one weapon and reload, character will reload both weapons, using up cartridges for one. Half the consumption of bullets))
This trick applies to almost all types of weapons, except for a revolver. He correctly reloads only one gun, and not both at once.
There are also problems reloading two sawed-offs. After reloading and subsequent switching to one sawn-off shotgun, first 2 shots will consume bullets of recharged two-shotguns.

**Comment by JMartinez9820** [comment]
Some of these issues have been fixed with the exception of the DMR and M1 Plasma Rifle, idk what's causing the M1 Plasma Rifle, but it's very minor. When all of these issues are resolved, this thread can be closed.

**Comment by JMartinez9820** [comment]
Dual wielding system is now overhauled. Fixing some of these issues

**Comment by JMartinez9820** [comment]
Minor updates to this issue:
1. Fixed
2. Fixed
3. Sounds like an easy fix but minor
4. Will take a look when I can.
5. Fixed
6. No sprites made for unloading animations yet, and no code for it too
