### ISSUE TITLE
Is it possible to disable the custom monsters entirely? 

### ISSUE THREAD

**Issue by parkerlreed** [pa1nki113r/Project_Brutality#217]
I'm wanting to use Project Brutality over another total conversion and it works currently but replaces the conversion monsters with the ones from Doom.

Is there a config/flag to not do the monster replacements?

**Comment by tunbridgep** [comment]
Unfortunately, the only way to completely get rid of them would be to strip them out of the wad, because of the way "replaces" works in decorate/zscript

**Comment by parkerlreed** [comment]
I tried removing the folders but then the zscript also references stuff and thus bails out. Haven't been able to find the right combination of file removal and zscript editing to get this to work.

**Comment by goldenmobster** [comment]
This is not a Issue, this is a discussion. These type discussions can be talked about in the PB Discord Server 

Closed

**Comment by AldenBluetenberger** [comment]
whats the point of using project brutality with other monsters anyway?
