### ISSUE TITLE
[Feature] [Outdated] Map-Enhancement Script (from Brutal Doom) is outdated and doesn't have a lot of maps

### ISSUE THREAD

**Issue by tunbridgep** [pa1nki113r/Project_Brutality#218]
The map enhancement system is very old, and as a result, there are some areas that look different and some which are not done at all. I believe some cases PB actually looks better (like the TNT Map01 example below), but I think it should be updated for cases where it's not implemented at all, which is true for a LOT of Doom 1, which I guess wasn't done at the time this was ported across.

This seems like a lot of work. How much actual effort is it to port it across? I might do it if it's not a monumental task.

![bd_e3m1](https://user-images.githubusercontent.com/31608726/63602050-fb9ebb80-c609-11e9-9978-1150ad04dcce.png)
![brutal_tnt_map01](https://user-images.githubusercontent.com/31608726/63602051-fc375200-c609-11e9-933c-8535a9d9659d.png)
![pb_e3m1](https://user-images.githubusercontent.com/31608726/63602052-fc375200-c609-11e9-9941-61515089b414.png)
![pb_tnt_map01](https://user-images.githubusercontent.com/31608726/63602053-fc375200-c609-11e9-8355-faef7934a447.png)

**Comment by JMartinez9820** [comment]
Actually, Map Enhancement System may possibly get scrapped from Project Brutality and will become its own file

**Comment by goldenmobster72** [comment]
It might get scrapped, Since Pa1n did scrap the BD Class so..

**Comment by tunbridgep** [comment]
Yeah I understand it getting scrapped.  That said, I really love the map
enhancement system. I think it would be worthwhile someone doing a project
to make it standalone, so that it can be used with other mods and isn't a
core part of PB.

I basically can't play Doom without the map enhancement script

**Comment by goldenmobster** [comment]
Pa1n scrapped the MES , & Therefore this issue is closed
