### ISSUE TITLE
Smart Scavenger portable stimkits/medkits option does nothing

### ISSUE THREAD

**Issue by tunbridgep** [pa1nki113r/Project_Brutality#219]
From what I understand, this setting is supposed to add in medkit style items that can be picked up, like the ones in Strife or Heretic/Hexen. As far as I know, this never actually works, since every single health kit I have ever seen has always been a standard healthkit (with the Smart Scavenger enhancements).

**Comment by secretagentjr** [comment]
it worked back in one the stable builds, but broke in one of the stable builds as well, so it's been an issue for quite sometime, personally they never spawn for me either

**Comment by goldenmobster72** [comment]
That _is_ very odd

**Comment by JMartinez9820** [comment]
Its been broken since the Github versions came. I could see the syringe potentially being scrapped in favor of the Health Packs, but as of this moment this is not a top priority.

**Comment by JMartinez9820** [comment]
@tunbridgep Portable stimkit has been officially scrapped in favor of the Leech Grenade. This can now be closed.
