### ISSUE TITLE
Random/unknow error...

### ISSUE THREAD

**Issue by Jerico3000** [pa1nki113r/Project_Brutality#221]
While playing with the mod, regardless the WAD/MegaWAD, this errors sometimes appears:

VM execution aborted: tried to read from address zero.
Called from MBlurHandler.NetworkProcess at
Porject_Brutality 3.0.zip:zscript.zc, line 608

Dont know why this, and appears when i kills enemies, but sometimes just appears without notice, when happen i have to quit...

Anyway to fix this?...

**Comment by goldenmobster72** [comment]
Which version of GZDoom are you using ?

**Comment by Jerico3000** [comment]
4.2.0

**Comment by emileb** [comment]
Done a potential fix for this here: https://github.com/pa1nki113r/Project_Brutality/pull/226
Fixes it for me, but should be reviewed

**Comment by Jerico3000** [comment]
Thanks, ill try it

**Comment by Jerico3000** [comment]
Thanks, now it works fine...

**Comment by JMartinez9820** [comment]
This issue is now resolved and can be closed.
