### ISSUE TITLE
No documentation/readme

### ISSUE THREAD

**Issue by FalcoGer** [pa1nki113r/Project_Brutality#223]
Please add a README.md file to the repository.
How do you pack this to run it? Where do the files go? Do you need some tool to compile something or similar?

**Comment by scaryred24** [comment]
What are you talking about? Download zip file, rename it from .zip to .pk3, and drag it over gzdoom.exe. Not every single git repo needs a readme.md. That's how everyone else does it.

**Comment by JMartinez9820** [comment]
Also, this sounds like a suggestion, but a redundant one. Suggestions do not belong to Github issues. If you want to post a suggestion, please posting on the Discord server if you feel like joining. This issue can be closed as this is invalid.

**Comment by goldenmobster** [comment]
Yes ☝

**Comment by FalcoGer** [comment]
"Download zip file, rename it from .zip to .pk3"
Exactly this kind of information is missing.

**Comment by goldenmobster** [comment]
That can probably be added in a READ ME file
