### ISSUE TITLE
[master 2019-09-04] bloody footprints bugs

### ISSUE THREAD

**Issue by ilvrak** [pa1nki113r/Project_Brutality#228]
missing red bloody footprints completely
blue and green bloody footprints are giant
![doom_blue_bf](https://user-images.githubusercontent.com/16130834/65608195-6a43b000-dfe0-11e9-9ec7-6100a8dcc256.png)
![doom_green_bf](https://user-images.githubusercontent.com/16130834/65608196-6adc4680-dfe0-11e9-87c5-30d9039d60e7.png)

**Comment by ilvrak** [comment]
in [2019-09-30] all bloody footprints are missing at all.
at least no more giant footprints.

**Comment by goldenmobster** [comment]
The Giant footprints isssue was resolved a while back and this is closed.. for now
