### ISSUE TITLE
Few issues (Blood colllisions, Plasma recoil, Reload button)

### ISSUE THREAD

**Issue by Krigeris** [pa1nki113r/Project_Brutality#230]
Hey just listing some issues I've noticed from the few levels I've played, will update this if I come across more.

>Ground blood splatters floating mid air

Near ledges if a splatter is big enough it will be floating, I never noticed this on BD or earlier PB versions and noticed it immediately on here. Not sure if thats something that affects all 3, but my suggestion is if its not too resource taxing to check the ground under a splatter for collision and to make the splatter smaller until a majority of the space under the splatter is solid.

>Plasma Rifle (first one I found) recoil doesn't reset

This issue went away after I duel wielded it, or reloaded with the assault rifle. But if when I fired a single plasma rifle my camera started tilting to simulate recoil but the tilt never reset, was legit playing with my head tilted for a minute before I realized what happened lol

>2 options for "reload" hotkeys, only 1 works

The default brutal doom reload hotkey doesn't work, and the second one was kinda hard to find (had to manually search for it), If possible I would replace the brutal doom reload button with your reload button to prevent confusion, or adding yours below it on the main controls page

Appreciate the mod gents, keep up the good work. Sorry if any of these issues are repeats.

**Comment by AlexThePianoNailer** [comment]
Well, actually Brutal Doom has the same issue with the blood splatters.
![Screenshot_Doom_20190929_005722](https://user-images.githubusercontent.com/54241958/65822876-3ffa2880-e254-11e9-8352-ebab1d75c90c.png)

**Comment by JMartinez9820** [comment]
@Krigeris In the recent versions of Project Brutality, the Brutal Doom reload key was removed in favor of GZDoom's default Weapon Reload key, the new updates also scrapped Brutal Doom v21 class. The tilting issue with the plasma rifle has also since been fixed thanks to the implementation of Tilt++. The blood splatters float is a model issue since the blood splatter is a flat sprite/model,

**Comment by Krigeris** [comment]
Thanks guys that was quick, not sure why I noticed the blood on here and never before, might've just got a really unlucky splatter that was super visible right off the bat.

**Comment by JMartinez9820** [comment]
You're the owner of this issue, so feel free to close this issue. If this issue comes back and rears up its ugly head again, feel free to reopen it.

**Comment by scaryred24** [comment]
Since the issue was never properly closed, its been done.
