### ISSUE TITLE
Bug zombieman

### ISSUE THREAD

**Issue by Tomilasquei1** [pa1nki113r/Project_Brutality#232]
I'm having a issue with some comands in console. I can't post photos on github so I've posted in the project brutality discord, my name is Tomilasquei. Maybe you can find it in bug reporting channel. Thanks.

**Comment by scaryred24** [comment]
You actually can post images but you have to have them embedded and hosted outside of github.

**Comment by JMartinez9820** [comment]
Duplicate of #209 if this involves the Zombieman console. I did update the hotfix for it two days ago.
https://mega.nz/#!7n4RQYiA!B4OKLBqtk7LhZxSm1w6HU8v3kSUFnh3KMe5ex8_haQk

**Comment by JMartinez9820** [comment]
Should now be fixed in new commit, issue can now be closed
