### ISSUE TITLE
slow move, no dash, no double jump in the new build

### ISSUE THREAD

**Issue by zheng598218529** [pa1nki113r/Project_Brutality#233]

**Comment by JMartinez9820** [comment]
The Dashing and Double jumping is off by default. These can be turned on within the ZMove Settings. Under Options/Project Brutality - ZMove Settings. As for movement and other options, PA1N himself recommends these settings according to what he posted on Discord.
https://cdn.discordapp.com/attachments/628066836751319060/628402950120931358/unknown.png
https://cdn.discordapp.com/attachments/628066836751319060/628402844957016094/unknown.png

**Comment by zheng598218529** [comment]
Thanks for the reply







------------------ Original ------------------

**Comment by goldenmobster72** [comment]
Feel free to close this issue
