### ISSUE TITLE
Divide by zero in script 24008

### ISSUE THREAD

**Issue by cemtex-tk** [pa1nki113r/Project_Brutality#236]
The only mod I have running is UDV and when equipping the pistol it kills off the weapon list in the hud as well as anything in ammotype2 for the weapon.  It seems to be only with that actor but I do not know why (I am new at this).  I got around it by having two actors for the same pistol (seriously just copying the actor with a new name an ID, and having the player use that actor and the problem disappears).  That is a sloppy fix and I am also curious as to what is actually the cause.

**Comment by scaryred24** [comment]
UDV has been put onto hiatus until 3.0 stable becomes a thing so it's highly discouraged to use addons as part of the bug reporting of the project as its unrelated to the core problem.

**Comment by cemtex-tk** [comment]
I am sorry.  I overlooked that the ACS script that is being referenced is in UDV and not in PB itself since I was also diagnosing a different issue (I am currently tinkering with the build for fun ATM)
