### ISSUE TITLE
Can't join PB Discord

### ISSUE THREAD

**Issue by ie516** [pa1nki113r/Project_Brutality#238]
I cannot join Project Brutality Discord for reasons
https://discord.gg/2hJxXPc

**Comment by JMartinez9820** [comment]
1. Do you have a profile pic on your account? You will need to add one. The verific

**Comment by JMartinez9820** [comment]
@ie516
1. Do you have a profile pic on your account? You will need to add one. The verification bot automatically kicks users with profile pics to prevent spam bots from joining.
2. Did you just create a new Discord account? The verification bot will also kick or not verify any accounts that are too young and are less that three days old.

P.S. This is not a Github issue. I would recommend contacting on the mods or admins on the PB server if you can.

**Comment by JMartinez9820** [comment]
@ie516
1. Do you have a profile pic on your account? You will need to add one. The verification bot will automatically kick or not verify users without profile pics to prevent spam bots from joining.
2. Did you just create a new Discord account? The verification bot will also kick or not verify any accounts that are too young and are less that three days old.

P.S. This is not a Github issue. I would recommend contacting on the mods or admins on the PB server if you can.

**Comment by goldenmobster72** [comment]
Close this issue when you can please

**Comment by scaryred24** [comment]
I got this.
