### ISSUE TITLE
Project Brutality crashing to the console

### ISSUE THREAD

**Issue by Pagan-Scriptures** [pa1nki113r/Project_Brutality#240]
I'm having a problem with Project Brutality. This happens at random, I have no idea why this happens.
What happened is that after I did an action (shoot, use a switch, etc.), it would crash to the console. I am using the latest version of GZDoom (4.2.3)
![image](https://user-images.githubusercontent.com/56914355/67375977-f502d500-f5b5-11e9-9cc9-dd44b67b38c2.png)

**Comment by goldenmobster** [comment]
Yikes

**Comment by JMartinez9820** [comment]
Try disabling motion blur, that might work. I believe pull #225 has fixed this issue.

**Comment by emileb** [comment]
Looks like the non JIT vm issue, this fixed it for me  https://github.com/pa1nki113r/Project_Brutality/pull/226

**Comment by JMartinez9820** [comment]
Another method would be to use this fix.
https://cdn.discordapp.com/attachments/498363558070059009/637288698681098240/ZombieManConsoleHotfixV3.pk3

**Comment by INFxBROOOKES** [comment]
ok im having a similar issue, but it only occurs when i have a meat shield and run out of ammo. when the shield is thrown it crashes, ive tried the fixes mentioned above but none have worked.

**Comment by INFxBROOOKES** [comment]
![base PB3 0](https://user-images.githubusercontent.com/57405428/68341625-78d8b900-00ae-11ea-90e1-daf6879dabdc.jpg)
this is without either fix

![with non JIT vm issue](https://user-images.githubusercontent.com/57405428/68341657-8beb8900-00ae-11ea-9a5b-4238802a11e0.jpg)
this is emileb's non JIT vm fix

![with zombieman hotfix](https://user-images.githubusercontent.com/57405428/68341716-a7ef2a80-00ae-11ea-9698-dfb6191c9445.jpg)
and this is with the zombieman hotfix

honestly its not a big deal, it would be nice for it to be fixed but i can play around it. ive come to discover it doesnt do this with standard zombie men (i.e. pistol and rifle variants) and standard/dark imps.

**Comment by MekBoss** [comment]
This is same type of problem as with barrel, which firstly takes away from inventory and then try to perform some actions using non existing self as function caller.
Check for all a_takeinventory calls.

**Comment by Epictyphlosion** [comment]
Just a guess, but GZDoom v4.2.3 can be rather buggy sometimes. There have been multiple cases where it crashes with whatever map pack I try to load, as it tries to read memory address FFFFFFFFFFFFFFFF for some reason. Try running it on v4.2.4 and see if it's any different

**Comment by JMartinez9820** [comment]
This issue should now be fixed in the latest commit, can now be closed
