### ISSUE TITLE
Bug: Unloading Hard-Crashes

### ISSUE THREAD

**Issue by shreksmomxdsaucememes** [pa1nki113r/Project_Brutality#248]
Only works with the DMR. Tested it with other guns, but to no avail. Unloading the DMR, revving the Minigun after unloading, then switching back and unloading it hard-crashes the game. [https://gfycat.com/fearlessfeminineinsect](url)

**Comment by JMartinez9820** [comment]
I can confirm that this bug is fixed on the new commit. I have no crashes anymore. This issue can be closed for now, but if it happens again feel free to reopen it.

**Comment by JMartinez9820** [comment]
This issue can be closed. @shreksmomxdsaucememes

**Comment by JMartinez9820** [comment]
This issue can now be closed, it's already fixed.
