### ISSUE TITLE
DMR Upgrade replaced Carbine, not DMR

### ISSUE THREAD

**Issue by L4Y-Duke** [pa1nki113r/Project_Brutality#249]
As title states. I picked up the DMR upgrade, but it seemed to replace the Carbine, not the DMR.

**Comment by goldenmobster** [comment]
Do a video or Gif on that please

**Comment by JMartinez9820** [comment]
The DMR upgrade is the Underbarrel Grenade Launcher, which will possibly get merged with the upcoming DMR upgrade, the HDMR (Heavy DMR), and the LMG replaces the Carbine. This issue only is pretty much invalid and can be closed.

**Comment by JMartinez9820** [comment]
@L4Y-Duke Unless you can show proof that this happens via a video, then this thread can be closed.

**Comment by goldenmob72** [comment]
My bad

**Comment by JMartinez9820** [comment]
Due to the lack of a response, this can be closed for now.

**Comment by JMartinez9820** [comment]
This issue can be closed due to no response from the issue opener.
