### ISSUE TITLE
autochange to Pistol and Carbine

### ISSUE THREAD

**Issue by ilvrak** [pa1nki113r/Project_Brutality#251]
i want to try playing clear start with melee only/

so,
in actors\player\player.dec
i clear up section with player start items and leave only:
	Player.StartItem "Melee_Attacks"
	Player.StartItem "IsPlayer", 1
        Player.StartItem "SlotOWN1", 1
	Player.StartItem "SlotOWN2", 1
	Player.StartItem "SlotOWN3", 1
	Player.StartItem "SlotOWN4", 1
	Player.StartItem "SlotOWN5", 1
	Player.StartItem "SlotOWN6", 1
	Player.StartItem "SlotOWN7", 1
	Player.StartItem "SlotOWN8", 1
	Player.StartItem "SlotOWN9", 1
	Player.StartItem "SlotOWN0", 1
	Player.StartItem "FragGrenadeSelected", 1
	Player.StartItem "IsPlayingAsProjectBrutality", 1

AND  - when i pick up Pistol, or Carbine - they do not atochange weapon to them

how to fix this?

**Comment by BenjaminZuriel** [comment]
Mate, this would be better to ask for help with on the discord server and I don't consider this to be an issue with the mod or any type of bug. please keep it to posting issues and bugs about the mod and not requests.
