### ISSUE TITLE
Lab Guy Kill doesn't count / Hellknights "splattered sound" loops endlessly

### ISSUE THREAD

**Issue by lord-andre** [pa1nki113r/Project_Brutality#253]
If you kill a Labguy (the Axe Version) with certain weapons, while he is in his idle state (the player has not been spotted yet), the kill will not count.
All kills with weapons that cause "normal / low" damage, such as the Fists, pistol or the dmr, are not considered as kills.
Weapons like shotguns or rocketlaunchers with special / brutal deaths DO count.

In addition, the Labguy seems to die, while he is in his idle status, with just one hit, no matter how much damage the weapon causes.

The "Labguy with chainsaw" variant seems to only not count when killed with the fists. (? not sure)

How to reproduce:
Load any map, activate "notarget" and summon "labguy". Test with different weapons.

---

When you kill a Hellknight with your ssg or quad ssg, the "splattered" sound will keep playing forever.
This only occurs in hallways, not in open areas. (With no ceiling above)

Edit:
After playing more, I'm not sure anymore which weapon or situation triggers this behavior. However, after further tests I can say that kills through headshots in narrow corridors trigger this pretty sure.
The Baron of Hell is also affected.

If you use the "iddt" cheat, you will see rotating triangles where you have killed these enemies.
In one situation i was lucky an could see endlessly rotating intestines of the hellknight. maybe that causes this sound?
![Intestines](https://user-images.githubusercontent.com/54155260/68985236-7d6f4100-0815-11ea-89dc-3811813a452f.gif)

Rotating triangle:
![image](https://user-images.githubusercontent.com/54155260/68985256-91b33e00-0815-11ea-8ab7-ce5d801e776a.png)

**Comment by tunbridgep** [comment]
I was wondering why there were some maps I could never get 100% kills on

**Comment by lord-andre** [comment]
In the latest version the Hellknight and Baronofhell remain silent after their death. Very good!
The only problem now is when a hellknight dies at low ceiling height. Then the guts appear halfway inside the ceiling accompanied by a loud noise. But these can now be removed with the "clear gore" keybind. (Must sometimes be executed twice in a row).

![Hellknight Head gibs6](https://user-images.githubusercontent.com/54155260/71778677-0a7e7d00-2fb1-11ea-8972-0b0df41fdc0c.gif)

**Comment by lord-andre** [comment]
Update: The not counting kill of the Labguy variations seems to be fixed.
