### ISSUE TITLE
Hi Res episode text in freedoom phase 1

### ISSUE THREAD

**Issue by swc132994** [pa1nki113r/Project_Brutality#256]
In freedoom phase 1 the hi res doom 1 episode section text is overwriting the freedoom episode selection showing the doom 1 episode names instead.

**Comment by swc132994** [comment]
Seen this was already reported. I agree not really an issue just a aesthetic problem

**Comment by JMartinez9820** [comment]
Yes, this was a duplicate of #175. Freedoom support is not guaranteed at this time, hence why many users and the devs play using the official IWADs.
