### ISSUE TITLE
If a lost soul kills an idle imp the imp just disappears

### ISSUE THREAD

**Issue by RealRexen** [pa1nki113r/Project_Brutality#259]
here's a video of it
[https://twitter.com/NagaTigerShark/status/1195525290363150336](url)
I have made a map to help with testing it, get the lost soul to notice you and then you can use notarget to help guide the lost soul to the imp, this can even happen in normal gameply, oddly if the imp isn't idle (for example attacking another monster) then it dies normally)
[MAP01.zip](https://github.com/pa1nki113r/Project_Brutality/files/3853739/MAP01.zip)

**Comment by scaryred24** [comment]
Excuse me for the late response. I already brought this to the developers. It has been noted and a fix will arrive sometime in a future commit.

**Comment by RealRexen** [comment]
Okay that's good to hear, I'll open another issue if I find any other issues
