### ISSUE TITLE
Ironsights misaligned

### ISSUE THREAD

**Issue by HWG90** [pa1nki113r/Project_Brutality#260]
Just letting you know that the ironsights for most ADS capable weapons are not centered (They're a little low). Not sure if there's anything that can be done about that.

**Comment by goldenmobster** [comment]
For which Weapons @HWG90  ?

**Comment by JMartinez9820** [comment]
Due to how some of the graphics are made, this may not be fixed. Brutal Doom also has this issue too. Also, it will be nice to say each weapon you think that has misaligned iron sights. Something like this is not a top priority at this time.

**Comment by HWG90** [comment]
The big offender is the pump shotgun, if that helps.

**Comment by scaryred24** [comment]
We are aware of the problem. The alignment will be considered at a later point but as of right now its not important enough to fix it right this very moment.

**Comment by pa1nki113r** [comment]
We have plans to update and polish the ADS for all weapons. Thanks for reporting though.
