### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by toastermanbruh** [pa1nki113r/Project_Brutality#267]
every time i shoot a zombie it will crash and will pop up a long string of text. the only thing i know about this is that it has something to do with the gore in the zscript

**Comment by JMartinez9820** [comment]
If this is the Zombieman error where it crashes to the console, then I have a fix here. Or check pull #226 for that similar fix. If you have a Discord account I will be on there too. Here is an invite to it.
https://discord.gg/2hJxXPc
https://mega.nz/#!ynxR3Y5T!7ShvV-VwB5X3yFBdKoY65w5MDQDX7R__jn56qM-Zeug

**Comment by toastermanbruh** [comment]
thx bro u da best

**Comment by toastermanbruh** [comment]
the pk3 didnt work, i think theres textures missing or something cuz its not working

**Comment by toastermanbruh** [comment]
is there a way 2 disable the gore to avoid this?

**Comment by scaryred24** [comment]
You can drop the value's so low that it wont render but you cant shut it off. Are you running anything in the background along with this that could be causing any conflicts?

**Comment by RealRexen** [comment]
the only time I had issues with the gore is if I have a video playing in edge dev, I also never had a crash from a zombie man, running gzdoom 4.3pre
