### ISSUE TITLE
Do I need brutal doom 

### ISSUE THREAD

**Issue by CooftyPoop** [pa1nki113r/Project_Brutality#269]
when I was playing the first map in doom 1 with this and pressed the button on the teslas and then something poped up didnt let me leave back to the game

**Comment by RealRexen** [comment]
no, PB is its own thing nothing else is needed, are you using gzdoom?

**Comment by CooftyPoop** [comment]
> no, PB is its own thing nothing else is needed, are you using gzdoom?

yea

**Comment by JMartinez9820** [comment]
I'm not really good into Delta Touch, but what is your load order? A screenshot would be appreciated. Did you try LZDoom under the GZDoom settings in Delta Touch? If more help is needed I will be in the Discord server.
