### ISSUE TITLE
This is annoying

### ISSUE THREAD

**Issue by CooftyPoop** [pa1nki113r/Project_Brutality#271]
Theres this bug that every mod I play on delta touch after a while the shooting button is broken I can shot then after a few minutes I just cant shoot or switch weapons I tought it post here because I couldnt find a solution on the internet

**Comment by NutMaster6942** [comment]
> Theres this bug that every mod I play on delta touch after a while the shooting button is broken I can shot then after a few minutes I just cant shoot or switch weapons I tought it post here because I couldnt find a solution on the internet

Consult the creators of Delta Touch.

**Comment by CooftyPoop** [comment]
> > Theres this bug that every mod I play on delta touch after a while the shooting button is broken I can shot then after a few minutes I just cant shoot or switch weapons I tought it post here because I couldnt find a solution on the internet
> 
> Consult the creators of Delta Touch.

and how do I do that

**Comment by NutMaster6942** [comment]
> > > Theres this bug that every mod I play on delta touch after a while the shooting button is broken I can shot then after a few minutes I just cant shoot or switch weapons I tought it post here because I couldnt find a solution on the internet
> > 
> > 
> > Consult the creators of Delta Touch.
> 
> and how do I do that

No idea, you can check [here](https://doomwiki.org/wiki/Delta_Touch) to see if they have an official site.

**Comment by JMartinez9820** [comment]
@CooftyPoop Can you please post a screenshot of the issue you are experiencing? Without any sufficient info, the devs won't know what to do and won't fix it. I can't guarantee full Delta Touch support at this time due to the constant changes Project Brutality has been going through.

**Comment by CooftyPoop** [comment]
> @CooftyPoop Can you please post a screenshot of the issue you are experiencing? Without any sufficient info, the devs won't know what to do and won't fix it. I can't guarantee full Delta Touch support at this time due to the constant changes Project Brutality has been going through.

well its not for project brutality its for delta touch in general
https://youtu.be/AHwQS39ONag

**Comment by JMartinez9820** [comment]
This issue is not related to Project Brutality then, but Delta Touch. I would recommend consulting the Delta Touch developer about this.

**Comment by CooftyPoop** [comment]
> This issue is not related to Project Brutality then, but Delta Touch. I would recommend consulting the Delta Touch developer about this.

how do I contact them

**Comment by JMartinez9820** [comment]
Check Developer contact
https://play.google.com/store/apps/details?id=com.opentouchgaming.deltatouch
