### ISSUE TITLE
BFG doesn't alert enemies

### ISSUE THREAD

**Issue by AlexThePianoNailer** [pa1nki113r/Project_Brutality#273]
When you fire BFG, enemies do not notice. As i checked, all other weapons work fine.

**Comment by goldenmobster** [comment]
> When you fire BFG, enemies do not notice. As i checked, all other weapons work fine.

I just checked it out and it's odd , We will keep note of this.
Ty for reporting that

**Comment by AlexThePianoNailer** [comment]
np

**Comment by JMartinez9820** [comment]
This issue is now fixed in the latest commit, can now be closed
