### ISSUE TITLE
still wont work

### ISSUE THREAD

**Issue by toastermanbruh** [pa1nki113r/Project_Brutality#274]
every time i play it will randomly crash to the commands with a long string saying "Called from PB_ZombieMan.Tick at :zscript/monsters/zombieman/zombieman.zc , line 90
i launched pb 3.0 doom with ZDL with the zombie fix and it STILL doesnt work

**Comment by JMartinez9820** [comment]
Please post a screenshot. That will show the team what's wrong. What source port are you using and version?

**Comment by toastermanbruh** [comment]
im sorry for bothering but ive figured out the problem and will report back any coding errors

**Comment by goldenmobster** [comment]
Since the Issue/Problem has been resolved it's going to be closed
