### ISSUE TITLE
SMG Pickup Icon 

### ISSUE THREAD

**Issue by goldenmobster** [pa1nki113r/Project_Brutality#276]
The SMG used the Old SMG Pickup Sprite, and Not a new & accurate one 

![Screenshot_Doom_20191201_154210](https://user-images.githubusercontent.com/40510344/69920061-7c632400-1451-11ea-86f9-521fdb215152.png)

**Comment by JMartinez9820** [comment]
Check pull request #266, now has an updated pickup sprite to match with the main weapon itself

**Comment by goldenmobster** [comment]
I will close the issue Until it [SMG PU Icon] gets updated/patched

**Comment by JMartinez9820** [comment]
SMG icon updated in new commit, can now be closed
