### ISSUE TITLE
Cannot switch weapon away from SSG-DW: Video Bug Report

### ISSUE THREAD

**Issue by jadenquinn** [pa1nki113r/Project_Brutality#277]
The bug is game-breaking, and seems to have JUST appeared in the last week or so from this repo, I just downloaded the master branch and zipped it up as usual, and just re-named from .zip to .pk3 and it works, except this time there is a bug that prevents me from playing further on my current save.

YouTube link to the bug report video: https://youtu.be/pvPKSUv245s
Thanks!

-jaden-

**Comment by goldenmobster** [comment]
Ty for reporting that , We will look into this

**Comment by jadenquinn** [comment]
Woah! Thanks for the VERY quick reply! Is there also any Discord Server that I can join for reporting things?
Thanks!

-jaden-

**Comment by goldenmobster** [comment]
The PB Discord Server https://discord.gg/2hJxXPc
Report Bugs in #pb-bug-reporting

**Comment by JMartinez9820** [comment]
This bug is one of the few major bugs that actually fixes its self after pressing kick. This commonly happens after ledge grabbing. To get out of it just press kick.

**Comment by jadenquinn** [comment]
It still happens, as seen on my CURRENT YT livestream, near the very beginning: https://www.youtube.com/channel/UCY17YzQXtkEw32NW1fTlX0w/live
Thanks for the CO-OP! You guys are so active!
-jaden-

**Comment by goldenmobster** [comment]
This is odd

**Comment by goldenmobster** [comment]
Did you try dropping the SSG (s) ?

**Comment by JMartinez9820** [comment]
Make sure you have your kick key mapped. If the Dual SSGs get stuck after trying to switch weapons, press kick. If you are still experience problems, DM me on Discord. I can help from there. My username is JMartinez2098.

**Comment by jadenquinn** [comment]
Oh, yep. I am inside the voice chat there currently.
Thanks!

-jaden-

**Comment by jadenquinn** [comment]
I have not (as far as I know) tried to (or pressed) drop the SSG(s) yet, or the keybind either.
-jaden-

**Comment by JMartinez9820** [comment]
@jadenquinn I can confirm that this bug is now completely fixed. After doing some testing with the new update with the dual SSG's being overhauled, it seems the dual SSGs being stuck after ledge grabbing is now fixed. This issue can now be closed.
