### ISSUE TITLE
No Blood stains on ceilings

### ISSUE THREAD

**Issue by Ord01** [pa1nki113r/Project_Brutality#281]
Like the title say, the last few builds dont project any blood stains on the ceilings. Is this a design choice or a bug?

**Comment by JMartinez9820** [comment]
I believe it is currently a design choice as gore is being overhauled for all monsters. Thank you for reporting this, we will take care of this as soon as gore and monsters overhauls are complete.

**Comment by Ord01** [comment]
:) thx for the replie. Lets hope they dont add more and more things, the performance goes down with every download i got from here(3 now).

**Comment by JMartinez9820** [comment]
Fixed in the Staging branch
