### ISSUE TITLE
Unloading a gun while dual-wielding it and then reloading it will cause an unintended sprite order

### ISSUE THREAD

**Issue by BlyatSlayer** [pa1nki113r/Project_Brutality#284]
The title says it all. To reproduce it,

1. Select Pistol ( DMR works too )

2. Aquire a second Pistol / DMR

3. Dual Wield it

4. If the ammo is less than 32 ( 16 + 16 ) or 62 ( 31 + 31 ) for Pistol and DMR respectively, reload it.

5. Unload the gun. Now you are no longer dual wielding it.

6. Reload it. Now you would see the other rifle appears and starts reloading it.

7. Now its back to normal

**Comment by JMartinez9820** [comment]
Oversight. Due to dual-wielding now being tied under one script (rather than a separate script for dual wielding) for some weapons, this will happen. Thank you for reporting this and showing steps on how to replicate the error.

**Comment by BlyatSlayer** [comment]
Well then! Thanks for the acknowledgement. Always delighted to see fast replies.

**Comment by JMartinez9820** [comment]
Minor update. Dual Wielding is now overhauled. Although some weapons don't unload completely on dual mode, my build has fixed some of the weapons to unload completely on dual wield.
