### ISSUE TITLE
infinite loop gore sprite

### ISSUE THREAD

**Issue by oof-machine-9000** [pa1nki113r/Project_Brutality#286]
The gore sprite of the Chaingunner, "deadchaingunguy_half" cannot be destroyed. Once it reaches 0 hp it makes a new sprite and the old one is destroyed. 

tl;dr chainsaw that, it is destroyed as normal with guts all over the place but a new one is made. infinite loop.

(tested with chainsaw)

**Comment by pa1nki113r** [comment]
Thanks, fixed it in the upcoming changes.
