### ISSUE TITLE
PDA script randomly makes the game crash to console when picking up new weapons.

### ISSUE THREAD

**Issue by reznorms** [pa1nki113r/Project_Brutality#292]
Had this happening 4-5 times with today update. It seems to be random as in this time I got it with the shotgun, but other time was with the SMG, and I also got the shotgun earlier without crashing. Reloading a save before picking it up or even before it spawn/drop doesn't change the result, still crashing on picking it up. Tested both with lzDooom v3.8.4 and gzDoom v4.2.4.

> You got the Pump Shotgun! (Slot 3)
New PDA Entry:UAC-GS10 Pump Shotgun
VM execution aborted: array access out of bounds. Max.index = 8, current index = 15
Called from PB_EventHandler.UiTick at PB30_20-12-2019.pk3:zscript/pbpda.zc, line 139

![Untitled](https://user-images.githubusercontent.com/6136005/71290690-c2d0e200-2370-11ea-9197-b5f789ed5f38.png)

**Comment by JMartinez9820** [comment]
I would recommend contacting Cacodemon345 on here or Discord about this error. He was the one that worked on the PDA. It's in a very early phase (basically an early alpha) like he mentioned.

**Comment by reznorms** [comment]
Little note: picking up the normal shotgun then the autoshotgun THEN the shotgun causes the crash.

**Comment by JMartinez9820** [comment]
Bugs take time to get fixed bud.

**Comment by goldenmobster** [comment]
Be patient , It WILL get fixed eventually

**Comment by Cacodemon345** [comment]
Yeah, that's a weird bug that I have encountered before. No idea why and how this happens...

**Comment by Cacodemon345** [comment]
After researching into the bug, it doesn't look like something easy to fix, fuck...

**Comment by reznorms** [comment]
Maybe you could disable the PDA untill you find a fix? It's a nice idea, but trying to avoid a crash on a core mechanic like picking up weapons make the game very tedious. And sometimes you can't avoid it as you stumble on a pickup while strafing around enemies in a fight.

**Comment by goldenmobster** [comment]
That is a good idea

**Comment by Cacodemon345** [comment]
I made a slight rewrite removing the savegame hacks from the PDA script. Test it and let me know, I will make a PR for it.

**Comment by reznorms** [comment]
I cloned the pdabranch and played a bit on it, tested getting the autoshotgun first and then the normal shotgun, no more crashes as before. I didn't pay attention to pickups but I played throu 3 maps and it does looks like even other combination of weapons/updates works fine.

**Comment by JMartinez9820** [comment]
This issue can now be closed as the PDA branch is now merged.
