### ISSUE TITLE
Unmaker is brokenly overpowered

### ISSUE THREAD

**Issue by arthurthlee** [pa1nki113r/Project_Brutality#300]
This is a suggestion/enhancement, but the Unmaker currently almost has infinite ammo, as the number of demons and therefore demon energy that you pick up nearly makes up for very liberal usage of it. It also does an insane amount of damage. Ex. Killing a Cyberdemon with the Unmaker recovers nearly all of its ammo back from the energy that the Cyberdemon drops. The secondary homing fire makes almost every other weapon inferior.

Suggestion: Double the ammo usage of it.

**Comment by JMartinez9820** [comment]
Suggestions most of the time are not usually posted in issues. If you have a suggestion, I would suggest posting it on the Discord server in suggestions for pb instead. If you are not on Discord, join [here](https://discord.gg/2hJxXPc)

**Comment by goldenmobster** [comment]
This is a Suggestion, Not a issue.
Closed
