### ISSUE TITLE
Weapon wheel mod

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#302]
I like to use the weapon wheel mod by  gleasspty. Was working well with previous releases but not this one. Getting a weird 20 x 20 blue grid obscuring the screen when I try to use it. I can probably do without it but I find it convenient to use when changing weapons.

**Comment by JMartinez9820** [comment]
This issue will not be logged as mods like the Weapon Wheel are not related to Project Brutality. Please consult with the developer of the Weapon Wheel mod if you want better compatibility with the current version.
