### ISSUE TITLE
PB30.pk3:zscript/playerpawn.zc error

### ISSUE THREAD

**Issue by SebRW** [pa1nki113r/Project_Brutality#305]
Unable to load the .pk3 created from .zip file in gzdoom3.7.2

Error: 

**PB30.pk3:zscript/playerpawn.zc, line 232: Attempt to override non-existent virtual function CalcHeight

Execution could not continue.**

Also minor: 
Invalid data encountered for texture PB30.pk3:sprites/weapons/ssg/thumbs.db

**Comment by reznorms** [comment]
Recent builds requires gzDoom v4.1.3 to run. zscript.zc still says 3.7.2 tho, updating that should make the requirement more clear as gzdoom will warn about version requirement at start.

**Comment by SebRW** [comment]
Problem solved thank you!
