### ISSUE TITLE
Magnum and Deagle seem too wimpy.

### ISSUE THREAD

**Issue by webursey** [pa1nki113r/Project_Brutality#312]
The rounds don't hit enemies with enough punch to seem like they're firing high caliber rounds. Fooled around with the actor file a bit and changed the projectile type to shotgun slugs. This resolved the issue, and allowed the two hand cannons to actually chunk enemies on death, and giving them the heavy hits they very much need.

**Comment by JMartinez9820** [comment]
This is a suggestion, please avoid posting suggestions here, instead, post it on the [Discord](https://discord.gg/2hJxXPc) server. I'm sure that the Deagle and Revolver are like that for the sake of balance.

**Comment by goldenmobster** [comment]
Since this is a Suggestion this issue/discussion is closed
