### ISSUE TITLE
Auto-equip inventory

### ISSUE THREAD

**Issue by SebRW** [pa1nki113r/Project_Brutality#314]
Don't know if it's an issue of voluntary behaviour.

In previous version of PB, when you picked up inventory items (goggles, hev suit etc...) you could keep in in your inventory and use it on will.

It seems that now, the items auto-equip like in vanilla doom. Why?

**Comment by JMartinez9820** [comment]
My guess is that was removed because it was possibly buggy and wasn't really necessary. I will show this issue to other devs to see what they say.

**Comment by SebRW** [comment]
I wonder if this is not related with UDV mod that I am using simultaneously.
I will let you know if I find out. 
I will close this issue as I'm not sure yet it's related with PB.

**Comment by scaryred24** [comment]
When reporting bugs, you need to make sure that no add-ons are causing any of the issues. We will only take in bugs with PB, not an add-on causing said bugs. The creator of UDV had told us that he won't update his mod for 3.0 compatibility until PB 3.0 becomes stable.
