### ISSUE TITLE
Disabling screen sway on strafe

### ISSUE THREAD

**Issue by sherief** [pa1nki113r/Project_Brutality#326]
I can't seem to find an option to disable screen sway (rotation around the view vector) when strafing left or right. This causes disorientation for me, is there any way to disable it? I can't seem to find one in the options. Adding one, or pointing me towards the code I'd need to change to disable it, would be appreciated.

**Comment by JMartinez9820** [comment]
@sherief You can disable Strafe Tilting along with other movement Tilt options in the Tilt++ settings.
![Tilt++1](https://user-images.githubusercontent.com/40510256/73083990-c684e680-3e91-11ea-80ed-b5e84b47b348.png)
![Tilt++2](https://user-images.githubusercontent.com/40510256/73083991-c684e680-3e91-11ea-8c12-110756a82ab8.png)

**Comment by goldenmobster** [comment]
Tell us if this works out for you @sherief , if it does please close this issue

**Comment by sherief** [comment]
That worked! 10/10, better support than AAA games. Would totally buy you guys a beer.
