### ISSUE TITLE
Weird Glitch/Bug IDK

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#328]
i found a weird bug, if you change your character color(in options) your legs change color too but looks weird, idk if this is was made to be like this on last build.
![20200125141535_1](https://user-images.githubusercontent.com/52841061/73127040-2fe32300-3f80-11ea-89f9-48834eacb4e6.jpg)
![20200125141621_1](https://user-images.githubusercontent.com/52841061/73127043-3e313f00-3f80-11ea-9057-12e95b75e21f.jpg)

![20200125141621_1](https://user-images.githubusercontent.com/52841061/73127075-9ec07c00-3f80-11ea-8b02-a1c47177351d.jpg)

Using Latest GZDoom 4.3.3 x64

**Comment by JMartinez9820** [comment]
Pa1n already mentioned this in his changelog. The kicking sprites will be updated to properly match with the color of the player sprite.
"- All first-person player leg animations will reflect the color chosen for third person (buggy right now, sprite updates needed)"

**Comment by Mr-Blazkowicz** [comment]
oh, i didn't saw it, thanks
