### ISSUE TITLE
31 errors while parsing DECORATE scripts (I'm using LZDoom 3.84)

### ISSUE THREAD

**Issue by lexaDOOM** [pa1nki113r/Project_Brutality#329]
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 179:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 188:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 202:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 214:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 226:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 236:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 880:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 893:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 903:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 916:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 926:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 939:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 949:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 962:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 975:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 1047:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 1055:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 1082:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 1098:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 1110:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 1165:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 1174:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 1193:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/slot1/melee.dec" line 1383:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/slot1/melee.dec" line 1400:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/slot1/melee.dec" line 1413:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/slot1/melee.dec" line 1430:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/slot1/melee.dec" line 1443:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/slot1/melee.dec" line 1465:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/slot1/melee.dec" line 1474:
Unknown identifier 'PSPF_PLAYERTRANSLATED'
Script error, "Project_Brutality-master.pk3:actors/weapons/slot1/melee.dec" line 1496:
Unknown identifier 'PSPF_PLAYERTRANSLATED'

**Comment by reznorms** [comment]
You need to use the dev build of lzDoom to run latest PB3 builds. You can get it from https://devbuilds.drdteam.org/lzdoom/

**Comment by lexaDOOM** [comment]
Thank's it works!
