### ISSUE TITLE
GZDoom "Crouch Toggle" feature doesn't work with PB.

### ISSUE THREAD

**Issue by EfremovSerg** [pa1nki113r/Project_Brutality#333]
So, when I installed clean GZDoom 4.3.3, I double checked that and it works for vanilla doom. But then I installed PB with a bit mods, bind being intact, but the function of toggle crouch doesn't work. When I installed custom WAD, I forced "Yes" on Allow mouselook, crouch and jump.

Normal crouch works fine though, but I prefer toggle crouch instead.

List of mods being used while stumbling this problem:

3ha2.wad
Project_Brutality-master.zip
HXRTCHUD-PB3_ghd274938.pk3
pb_allow_sv_cheats.pk3
target-spy-1.12.pk3

**Comment by JMartinez9820** [comment]
@EfremovSerg This is actually an issue with ZMovement itself and not a PB issue. I can confirm this after testing the Crouch Toggle with ZMovement itself. We didn't create ZMovement, but Ivory Duke did. You can contact Ivory Duke on ZDoom Forums or Discord (you may have to find him on certain Discord server) if you want a fix for this problem. Crouch Toggle being fixed is not a top priority at the time being. Here is the link to [ZMovement] (https://forum.zdoom.org/viewtopic.php?f=43&t=65095) itself if necessary to contact Ivory Duke, or to test with PB.

**Comment by EfremovSerg** [comment]
Ok, will try. I'll leave a message if I manage to contact him and tell what he is gonna do about that.

**Comment by EfremovSerg** [comment]
Just got word from Ivory Duke, what he fixed that issue (one line of code). But, we have to wait for release of ZMovement 3.2. Hope it's gonna be included in the next update, when ZMovement gonna be ready.

**Comment by JMartinez9820** [comment]
@EfremovSerg Some good news. I was able to port the crouch toggle fix from ZMovement 3.2.1 into my build, and I can confirm it works properly. Although PB is still going to use ZMovement 3.0 but modified the crouch toggle fix from 3.2.1. Check pull request #375 and its branch if you want to test it out.

**Comment by GoldTomatoes** [comment]
Yay!


ср, 20 мая 2020 г., 5:59 JMartinez9820 <notifications@github.com>:

**Comment by EfremovSerg** [comment]
Yes. I've checked that snippet. Works flawlessly! Much appreciated!

**Comment by JMartinez9820** [comment]
@EfremovSerg Now added in newest commit. Issue can now be closed.

**Comment by JMartinez9820** [comment]
This issue can be closed. Fixed in latest PRs.
