### ISSUE TITLE
PDA has no borders on the edge of the screen for the cursor

### ISSUE THREAD

**Issue by Epictyphlosion** [pa1nki113r/Project_Brutality#335]
The PDA seems to be a rather new feature, and I kinda like it. However, I noticed that the mouse cursor can be moved beyond the edge of the screen instead of stopping at the edge like one would expect. This means that, if you're not careful, you could lose track of where your cursor was and be stuck in the PDA screen, forcing you to restart the game (Not restart as in closing the game, hitting escape and clicking "New game" can fix this). That actually happened to me when I first tried it, I noticed that my cursor had disappeared, and had no idea where it went.

A "Close PDA" hotkey could've avoided this problem as well, and would be a good addition too.

**Comment by JMartinez9820** [comment]
The PDA currently implemented is in a very early alpha phase, so this is expected. I believe Cacodemon345 is still working on it, but I'm not entirely sure because he has life stuff to focus on apart from PB.

**Comment by Epictyphlosion** [comment]
Ah, that makes sense. I could try and see what's causing the issue, but I don't have much knowledge of how the code of this mod actually works and such

**Comment by Cacodemon345** [comment]
I haven't implemented clamping for the mouse cursor yet. This will have to wait.

**Comment by goldenmob72** [comment]
This is more of Suggestion than an Issue, This is now closed
