### ISSUE TITLE
VM EXECUTION ABORTED: TRIED TO READ FROM ADDRESS ZERO. IN FUNCTION PARAMETER "TARGET"

### ISSUE THREAD

**Issue by lexaDOOM** [pa1nki113r/Project_Brutality#336]
VM EXECUTION ABORTED: TRIED TO READ FROM ADDRESS ZERO. IN FUNCTION PARAMETER "TARGET"
CALLED FROM ACTOR.CHECKSIGHT [NATIVE]
CALLED FROM PB_MONSTER.A_SMART_CHASE AT PROJECT-BRUTALITY-MASTER.PK3: ZSCRIPT/MONSTERS/PBMONSTER.ZC, LINE 40
CALLED FROM THINKER. TICK [NATIVE]
CALLED FROM PB_MONSTER. TICK AT PROJECT-BRUTALITY-MASTER.PK3: ZSCRIPT/MONSTERS/PBMONSTER.ZC, LINE 57
CALLED FROM PB_ZOMBIEMAN. TICK AT PROJECT-BRUTALITY-MASTER.PK3: ZSCRIPT/MONSTERS/ZOMBIEMEN.ZC, LINE 92
![Screenshot](https://user-images.githubusercontent.com/60314014/74541915-9c37bd80-4f53-11ea-9031-87616cf88dca.png)

**Comment by JMartinez9820** [comment]
Already reported. This may be an issue with your hardware, as 32 bit may not work properly. Some have confirmed that 64-bit works okay. Do you mind posting your PC specs, please?

**Comment by Lophier** [comment]
this problem mostly seen on Delta-touch.  never seen on PC. my cell phone cant play the build.

**Comment by emileb** [comment]
https://github.com/pa1nki113r/Project_Brutality/blob/9cd0872ed9893f411e5a4b3b3b9f19de9fae33a9/zscript/Monsters/PBMonster.zc#L35

Need return here, if target is NULL the rest of the function makes no sense to continue.

**Comment by JMartinez9820** [comment]
@lexaDOOM Try this fix I attempted to make here. Added the return statement to see if it fixed it. Thanks to @emileb for pointing this out
https://drive.google.com/open?id=10WvuolxsTB0aeFrlbXlQhelNwkjtNclU

**Comment by goldenmob72** [comment]
Is this pushed and merged to the main PB Branch @JMartinez9820  ?

**Comment by JasonM2396** [comment]
Not yet. Needs further testing by those affected by that error until I feel like pushing it.

**Comment by JasonM2396** [comment]
This is actually JMartinez9820 right here. Just currently using my school account.
