### ISSUE TITLE
Blur Weird on Fist

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#339]
-Quick Note, this was tested on gzdoom 4.3.3 x64 with zdl and latest pb build.

After playing with the latest build, and using only fist w/berserk (i didnt test this without berserk) all the entire level or map, sometimes the blur on the fist looks kinda cartoonish or bad edited when doing a combo or after some fatality, also the blood on the gloves turn into the same color of the player,i didn't take screenshot because you can get this "bug" just playing a entire map with only fist and with berserk and you'll see what im talking, the "fist swing" from the sides when doing a combo it's what look weird.

**Comment by JMartinez9820** [comment]
@Mr-Blazkowicz 
About the blur, can you please post a screenshot? How are the devs like me supposed to know if you provident insufficient info? About the blood on the gloves turning to the player color, that's because of the PSPF_PLAYERTRANSLATED flag not exiting properly when doing an air kick. The recent update from a couple of hours ago has fix. If you can, please post screenshots. Good information is crucial for a dev to figure out what is the issue. Otherwise, this issue can be closed if necessary.

**Comment by Mr-Blazkowicz** [comment]
Quick Update

After try many times i know how to get this, simple, keep jumping and punching until this appear and i saw something interesting, the colors of the blood got oversaturated when this happens, this is most noticeable when you kill a caco, the light blue turns into a darker blue, and to get the "player color" on the gloves happens when you kill a hellknight(Fatality on them), also was hard to get these ss, so here:

![Blur R1](https://user-images.githubusercontent.com/52841061/75129514-effe8100-568e-11ea-96fd-97eae59335de.jpg)
![Blur R2](https://user-images.githubusercontent.com/52841061/75129532-fee53380-568e-11ea-9729-de08b3446f44.jpg)
![Blur B1](https://user-images.githubusercontent.com/52841061/75129536-03115100-568f-11ea-9502-5f0a9f8772ef.jpg)
![Blur B2](https://user-images.githubusercontent.com/52841061/75129539-07d60500-568f-11ea-84bf-2aaab869b48b.jpg)
![Blur  G1](https://user-images.githubusercontent.com/52841061/75129544-0c022280-568f-11ea-98e6-76235bf210f9.jpg)
![Blur G2](https://user-images.githubusercontent.com/52841061/75129546-102e4000-568f-11ea-9094-8d8a6c9d10ce.jpg)
![Blur G3](https://user-images.githubusercontent.com/52841061/75129553-158b8a80-568f-11ea-922b-7ba3a0ced870.jpg)

**Comment by Cacodemon345** [comment]
Is this a bug related to the new weapon sprite recoloring feature in GZDoom?

**Comment by goldenmob72** [comment]
I would say it's the motion blur, but this is not that big of a deal (IMO) since there's not a lot of people who pay attention to these details

**Comment by JMartinez9820** [comment]
@Mr-Blazkowicz Are you playing with the latest build? I swore I fixed this by fixing some of the PSPF_PlAYERTRANSLATED flags on the BaseWeapon.dec script. This issue can be closed if its fixed on your end now.

**Comment by Mr-Blazkowicz** [comment]
like i said "Tested on latest Build" and also the new build has it too(march latest build).

**Comment by JMartinez9820** [comment]
Ah, I see. Just tested out right now. God, I'm so stupid, I just want to hurt myself right now. I know why this is happening, its the PSPF_PLAYERTRANSLATED flag. That actor flag forces sprites to be more like a Doom graphic format (Indexed format), and it also overwrites the green color to the play color, causing that oversight when you combine punching and kicking at the same time. I'm going to try my best to fix this, as of right now deal with it until a fix is made.

**Comment by goldenmob72** [comment]
Ok , When you push out a fix and get patched to the main PB Branch please let me know asap, after I'll close this

**Comment by JMartinez9820** [comment]
@Mr-Blazkowicz I haven't pushed an attempted fix I have worked on yet, but here is my branch containing the fix if you want to download it. This should fix the blur and blood color oversight on the fists. Basically made the PSPF_PLAYERTRANSLATED flags to be false when punching to prevent that oversight.
https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezWorkBranch

**Comment by Mr-Blazkowicz** [comment]
downloading the build above me, if its fixed i'll let you know.

**Comment by Mr-Blazkowicz** [comment]
ok so i tried the same process with Red/Blue/Green, that means common red blood enemies, cacos and hellknights, the "player color" is still there after a hellknight fatality and after that, don't punch because if you punch after that, it will turn into normal green blood, but like i said this now happens on a very, very rare situation, but the rest of the red/blue blood and the blur on it it's fixed.

**Comment by goldenmob72** [comment]
Alright, when that fix gets pushed to main PB branch i'll close the issue

**Comment by JMartinez9820** [comment]
This issue can now be closed as it has now been fixed.
