### ISSUE TITLE
Looking to Contribute

### ISSUE THREAD

**Issue by webursey** [pa1nki113r/Project_Brutality#349]
I'm sure this is't the right place to put this. I was sent a link to the discord a looong time ago, but no longer have it. Would like to post there if I could request a link. 

I've been doing some sprite work for the mod in my spare time. Have currently converted the UAC-LMG sprites to match the new carbine, and replaced the chainsaw special fire sprites to match the new super shotgun. While they are a bit rough, and lack motion blur effects, I'm sure they could be of some use, and I'd be happy to share them.

What would I have to do to go about doing this?

**Comment by JMartinez9820** [comment]
Discord link is right here: https://discord.gg/2hJxXPc

As for the LMG, its already got new sprites in the works, but not implemented yet. Here is a sprite of how the LMG going to look like, sprite by iamcarrotmaster.
![lmg4](https://user-images.githubusercontent.com/40510256/76585108-8ca48980-64ab-11ea-9666-b0066e7190ee.png)

**Comment by webursey** [comment]
Okay, that beats mine by a long shot. I just re-skinned the carbine as a base myself, but im liking this one a lot. Is there anything that does need sprite work done?

________________________________

**Comment by JMartinez9820** [comment]
@webursey Hey dude, you were in the Brutal Doom server, right? IIRC you were in there before I left the server. Anyways, if you want to DM me on Discord feel free too, my username on there is JMartinez2098. Maybe you can send me the fixed chainsaw special sprites so I can tweak an existing I'm working on right now.

**Comment by scaryred24** [comment]
This is for bug reporting, not feature suggestions.
