### ISSUE TITLE
Missing files [Weapon Base] | Not being able to boot

### ISSUE THREAD

**Issue by TheHUNKMrDeath** [pa1nki113r/Project_Brutality#350]
I have encountered error with newest version of this mod.

Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 14:
Parent type 'PB_WeaponBase' not found in PB_Weapon
Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 17:
"weapon.bobrangex" requires an actor of type "Weapon"

Execution could not continue.

Script error, "Project_Brutality-master.pk3:actors/weapons/baseweapon.dec" line 17:
Unexpected '0.3' in definition of 'PB_Weapon'

It was tested on Zandronum 3.0

**Comment by scaryred24** [comment]
Zandronum 3.0 was dropped ages ago. Minimum requirement as this point of development is GZDoom 4.3.x.

**Comment by JMartinez9820** [comment]
@TheHUNKMrDeath Zandronum support has been dropped since 2017. Either upgrade to GZDoom 4.3.x, or use LZDoom. Can be found [here](https://zdoom.org/downloads), with LZDoom being under alternative. This issue can now be closed.
