### ISSUE TITLE
Is there a way to play this on zandronum?

### ISSUE THREAD

**Issue by AmpedgamR** [pa1nki113r/Project_Brutality#352]
Is there a way to get rid of the weapon sway, and screen tilt and other things to play on zandronum? Maybe like a lite version?

**Comment by JMartinez9820** [comment]
Due to the use of ZScript and updated script, PB is not compatible with Zandronum, its been like that since 2017. GZDoom 4.3.3 or LZDoom 3.85 is required to use. If you want to play PB on Zandronum you have to download PB 2.03 to play.

**Comment by AmpedgamR** [comment]
Ok.
