### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by Rooc-Key** [pa1nki113r/Project_Brutality#353]
Hi guys,

I'm kinda new to this kind of programming (though I can program in C) and I'm having some trouble with some stuff.
I'd like to add the following weapons:
-A Kraber-AP style sniper rifle (with a single shot ripper projectile upgrade). I'm thinking on adding the 0 slot
-A new OP revolver with 2 different fire modes
   1-Shotgun spray (3 bullets per clip)
   2-Revolver Ocelot style (6 bullets per clip)
-The CyberDemon Rocket Launcher (which as a higher fire rate than the normal rocket laucher and doesn't need to be reloaded)
-A semi-automatic rifle (although I'm not so sure about adding this one)

Sooo here are a few questions:

-Where can I find the gameinfo containing the playerclass?
-How do I program the trails behind a projectile?
-What is A_DoPBWeaponAction?

Thanks for the help, and sorry for the many, infinite grammar mistakes I made

**Comment by scaryred24** [comment]
We are not accepting any additions at this phase of development. Thread closed
