### ISSUE TITLE
Script Error "LANGUAGE" line 98, when starting

### ISSUE THREAD

**Issue by dave-filion** [pa1nki113r/Project_Brutality#359]
Hey all, just downloaded master and tried starting. Got this error:
![pb_issue](https://user-images.githubusercontent.com/687294/78704256-98804180-78d9-11ea-8257-8a97cd9a644d.PNG)

```
Execution could not continue.

Script error, "LANGUAGE" line 98:
Unterminated string constant
```

using GZDoom 4.3.3 64-bit. Any ideas?

**Comment by JMartinez9820** [comment]
This issue just got fixed and can be closed. This was totally my fault for that fucky wucky I made, sorry about that. I would take notice to test changes before I commit next time. God I'm so dumb I want to hurt myself until I bleed out...

**Comment by Cacodemon345** [comment]
> God I'm so dumb I want to hurt myself until I bleed out...
Never do that, man.

**Comment by dave-filion** [comment]
Awesome thanks @JMartinez9820 ! I'll pull the latest. Its no big deal, I commit stuff I dont mean to all the time.

**Comment by JMartinez9820** [comment]
@dave-filion You're welcome. I actually was unaware of a mistake that I made at line 98, which I mistakenly put two quotation marks at the beginning instead of just one. I learned an important lesson  today though, ALWAYS test any changes before committing to a repository.
