### ISSUE TITLE
Project Brutality crash

### ISSUE THREAD

**Issue by Cerberus3010** [pa1nki113r/Project_Brutality#360]
I have this issue when as i headshot or kill in any way a Zombieman the game crashes, i have no idea why this happens. I was using GZDoom to load PB when it crashed.
![Crash](https://user-images.githubusercontent.com/63308116/78715046-d5086900-78ea-11ea-9222-21042eadc47a.PNG)

**Comment by JMartinez9820** [comment]
@Cerberus3010 Check @emileb 's build, it fixes that error. However, it's not updated to the latest changes.
https://github.com/emileb/Project_Brutality/tree/fixes_for_delta_touch

**Comment by JMartinez9820** [comment]
@Cerberus3010 Redownload emileb's build again, it's now been updated to the latest master changes.
https://github.com/emileb/Project_Brutality/tree/fixes_for_delta_touch

**Comment by JMartinez9820** [comment]
This issue can now be closed. I have fixed this problem and was pushed to master.
