### ISSUE TITLE
I was using an outdated version of GZDoom

### ISSUE THREAD

**Issue by CptnCobalt** [pa1nki113r/Project_Brutality#364]
Sorry for bugging you guys, looking at the discord showed that it doesn't work on an outdated version of GZDoom.
![Untitled](https://user-images.githubusercontent.com/63592511/79121543-284f4100-7d5b-11ea-88d3-411f85a25c37.png)

**Comment by JMartinez9820** [comment]
@CptnCobalt You need to update your GZDoom to 4.3.3. Otherwise, use LZDoom if you can't use GZDoom 4.3.3.

**Comment by JMartinez9820** [comment]
GZDoom 4.3.3 is now required due to a newly introduced called PSPF_PLAYERTRANSLATED, which PB currently uses for kicking sprites to reflect the player's color. PSPF_PLAYERTRANSLATED was introduced in GZDoom 4.3.1.

**Comment by JMartinez9820** [comment]
This issue can be closed of resolved.

**Comment by goldenmob72** [comment]
Just Update to the Latest version of GZDoom and that's it
