### ISSUE TITLE
Character gets stuck with no ability to use any weapons or anything even after a game restart.

### ISSUE THREAD

**Issue by iiFir3z** [pa1nki113r/Project_Brutality#365]
When you grab a Imp and it gets killed there is a chance for you to hold nothing when the imp goes away forcing you to restart the whole level to punch/use guns.

**Comment by JMartinez9820** [comment]
@iiFir3z Due you have any information on how to replicate this problem? If it involves the meatshields, then you can just press the Drop Weapon key. To map a key Drop Weapon, go to Customize Controls/Inventory

**Comment by iiFir3z** [comment]
I don't really have a way of replicating it. I just had to restart the level a couple times in DOOM 2 (The Pit) which kind of got on my nerves but thanks for the solution if it happens again.

**Comment by goldenmob72** [comment]
If you do replicate that again, feel free to re-open this issue
