### ISSUE TITLE
( ZMOVE ) Using Build Engine Movement Style Will Make The Player Move Backwards when trying to move forward ( Same as setting high value into -turbo )

### ISSUE THREAD

**Issue by SharlLegreg** [pa1nki113r/Project_Brutality#366]

**Comment by SharlLegreg** [comment]
Ways to replicate :
GZDoom Version : 4.3.3

1. Set movement type in ZMOVE to Build Engine
2. Try running forward
Expected Result : The Player can't move forward.

**Comment by goldenmob72** [comment]
That's rather strange

**Comment by JMartinez9820** [comment]
@SharlLegreg Strange. Do you have any information to reprouce this issue? Also, this is something related to ZMovement which is something not related to Project Brutality. For that, you might want to go through it's creator to fix that problem.
https://forum.zdoom.org/viewtopic.php?f=43&t=65095

**Comment by SharlLegreg** [comment]
> @SharlLegreg Strange. Do you have any information to reprouce this issue? Also, this is something related to ZMovement, which is not related to Project Brutality. For that, you might want to go through it's creator to fix that problem.
> https://forum.zdoom.org/viewtopic.php?f=43&t=65095

Yeah thx for the link. I couldn't find the zmove zdoom forum.

For the info to reproduce the bug, it's as simple as making the movement type to build engine. iirc it only happens on both the latest GZDoom and LZDoom version ( 4.3.3 and 3.85 respectively )

**Comment by JMartinez9820** [comment]
@SharlLegreg I have no such issue, I'm moving just fine with Build engine movement, no issues. It might be something on your end. Make sure that all of your keys are mapped correctly as well.

**Comment by goldenmob72** [comment]
What JMartinez2098 said, any further issues or bugs w/ ZMovement have to be dealt with the Creator/Dev of ZMovement, Ivory Duke.
