### ISSUE TITLE
Pistol reload sprite issue

### ISSUE THREAD

**Issue by popguy12** [pa1nki113r/Project_Brutality#367]
there is a glaring issue with the reload sprites for the akimbo pistols. i havent checked to see if it applies to the standard pistol reload. but the gloves on some of the akimbo reload frames are much darker in sections for some reason

**Comment by JMartinez9820** [comment]
@popguy12 Care to show a screenshot or a sprite? This sounds very minor but not a top priority.

**Comment by popguy12** [comment]
![D6GAQ0](https://user-images.githubusercontent.com/53667854/79410892-66fd1b00-7f56-11ea-8cd2-16e899e2cad8.png)
this frame for instance, along with frames with the same angles

**Comment by JMartinez9820** [comment]
Older versions of PB 3.0 and PB 2.03 had the arm like that too when reloading. That's how the sprite was just made like. Definitely an easy fix but not a top priority right now.

**Comment by popguy12** [comment]
yea, i noticed the problem was on the old sprites as well

**Comment by JMartinez9820** [comment]
Officially fixed with the pistol reanimation update
