### ISSUE TITLE
Carbine inconsistency

### ISSUE THREAD

**Issue by Saysike991** [pa1nki113r/Project_Brutality#368]
there are inconsistencies between animations on the carbine, some parts are greenier than others (particularly in reload animations and firemode switch) and also on the scope, with one of the knobs being up and other getting set down when aiming

**Comment by JMartinez9820** [comment]
Not a top priority at this time right now. We will take care of it though, Carbine overhaul is not really completed yet.

**Comment by JMartinez9820** [comment]
Sometimes, developers or the artists have life stuff to deal with too apart from PB. Hope you understand that and bugs or inconsistencies take time to fix.

**Comment by popguy12** [comment]
to add to this, similar to the glove color issue on some of the pistol sprites, some of the sprites have the dark black gloves, mainly the idle un-aimed sprites

**Comment by JMartinez9820** [comment]
Carbine re-overhaul has fixed this problem
