### ISSUE TITLE
Upgraded weapons shows previous weapon sprite

### ISSUE THREAD

**Issue by nihilexmachina** [pa1nki113r/Project_Brutality#369]
Whenever you select a weapon that has been upgraded, it shows the sprite of the standard weapon plus the upgraded weapon. I've noticed this after replacing PB pk3 from commit 270110d with the one of commit fd3070d

**Comment by JMartinez9820** [comment]
Known issue, but not a top priority to fix right now. My guess is that PA1N could have possibly added an upgrade checker to see if the player has an upgrade then it switches to the upgrade, but I'm not entire sure. It's a very minor issue but not a top priority to fix right now, and it doesn't affect the game.

**Comment by nihilexmachina** [comment]
Thanks for the response.

(also, I'm editting issue's title)
