### ISSUE TITLE
Demon Tech Rifle Secondary fire on Former Human Variants crash my game

### ISSUE THREAD

**Issue by wyruzzah** [pa1nki113r/Project_Brutality#372]
Hi, when i use Demon Tech Rifle Secondary fire on Zombieman or other Former Human Variants it sometimes crash my game. It not happens with cacodemon or pinky etc.

Im using only GZDoom g4.3.3 + current Project_Brutality-master with doom.wad

**Comment by JMartinez9820** [comment]
Just tested on my end, confirmed to be a bug. It could be related to switching to friendly. Thanks for reporting.

**Comment by Cacodemon345** [comment]
Further testing seems to indicate it's a engine-side bug. Will be pushing a fix to GZDoom if this seems to be fixable.

**Comment by Cacodemon345** [comment]
Ah, seems like a mod-side infinite loop bug instead.
