### ISSUE TITLE
Ledge climbing

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#377]
Probably not a bug, but is there an option to turn it off?
Seems automatic now, grabs ledges even when not jumping.

**Comment by JMartinez9820** [comment]
Ledge grabbing has been overhauled to use ZMovement's system, but it's on by default. However, you can disable ledge grabbing ok the console by typing pb_ledgegrab 0

**Comment by goldenmob72** [comment]
Then in that case, this issue is now closed
