### ISSUE TITLE
Meatshields shots don't connect.

### ISSUE THREAD

**Issue by Charles424** [pa1nki113r/Project_Brutality#378]
Shooting an enemy with a rifle from point blank range while holding a meatshield doesn't seem to do anything, like the shots are flying through a ghost. Doing the same thing with a regular gun still works though.
Maybe it is a known issue but I have never seen it mentioned.

**Comment by JMartinez9820** [comment]
The shots DO connect, it's just they work very weirdly. Also, meatshields are not overhauled yet so this isn't really a priority now.

**Comment by JMartinez9820** [comment]
Should be closed due to the removal of meatshields
