### ISSUE TITLE
I crash to console whenever I Jump

### ISSUE THREAD

**Issue by RelishedPrawn** [pa1nki113r/Project_Brutality#380]
The console crashes and leaves this message for me:

"VM execution aborted: division by zero.
Called from PlayerPawnBase.BobWeapon at Project_Brutality-master.zip:zscript/playerpawn.zc, line 3447"

I don't know.

**Comment by JMartinez9820** [comment]
@RelishedPrawn Which GZDoom version are you using? I need clarification on which GZDoom version, and either 32 bit or 64 bit. I would try disabling weapon sway, found in Visual Options in the Project Brutality Settings in Weapon Options. If that doesn't work, try using LZDoom.

**Comment by JMartinez9820** [comment]
Sharing your PC specs would be great too just in case needed.

**Comment by RelishedPrawn** [comment]
> @RelishedPrawn Which GZDoom version are you using? I need clarification on which GZDoom version, and either 32 bit or 64 bit. I would try disabling weapon sway, found in Visual Options in the Project Brutality Settings in Weapon Options. If that doesn't work, try using LZDoom. Under rnative
> https://zdoom.org/downloads

I'm using gzdoom v

> @RelishedPrawn Which GZDoom version are you using? I need clarification on which GZDoom version, and either 32 bit or 64 bit. I would try disabling weapon sway, found in Visual Options in the Project Brutality Settings in Weapon Options. If that doesn't work, try using LZDoom. Under alternative
> https://zdoom.org/downloads

I'm using GZDoom 4.3.3 64bit, on some HP 15 laptop.

**Comment by JasonM2396** [comment]
I would try using LZDoom 3.85 if that might work

**Comment by RelishedPrawn** [comment]
> I would try using LZDoom 3.85 if that might work better

Project Brutality seems to be working on the LZDoom file good. The worst part is that GZDoom was working just fine with it a few days ago.

**Comment by JasonM2396** [comment]
I would try deleting the ini for a fresh reinstall of GZDoom, but if LZDoom is working fine then you should be ok. It's your choice

**Comment by RelishedPrawn** [comment]
> I would try deleting the ini for a fresh reinstall of GZDoom, but if LZDoom is working fine then you should be ok. It's your choice

That's what I just did deleted everything, re downloaded the GZDoom.zip file, and everything was working perfectly. I have no idea what could have happened to the old one.

**Comment by JMartinez9820** [comment]
@RelishedPrawn Probably your old settings conflicted with the new settings since portions of ZMovement are now hardcoded in PB. If you think you fixed this issue, then this thread can be closed. If it happens again, don't hesitate to re-open it.
