### ISSUE TITLE
Cyber Baron Sprites

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#381]
Tested on Latest PB Build from 21/04/20 with ZDL and GZDoom 4.3.3 x64

1.-If you kill a Cyber Baron With incendiary ammo/weapons such as:

-Dragon's Breath(Shotgun upgrade)
-Mancubus Flame Cannon
-Incendiary Rounds from the SuperGL
-etc
This will die with the Dark matter rifle animation

2.-And if you kill a Cyber Baron with the dark matter rifle(plasmagun upgrade)/Black Hole Generator, this will die with the Baron of hell dark matter rifle death sprites.
![Inendiary 1](https://user-images.githubusercontent.com/52841061/80897563-b6b24500-8cbf-11ea-9bea-951ed266564b.jpg)
![Incendiary 2](https://user-images.githubusercontent.com/52841061/80897565-b9149f00-8cbf-11ea-9cce-0239a34d5e2a.jpg)
![Purple 1](https://user-images.githubusercontent.com/52841061/80897567-bade6280-8cbf-11ea-9700-c4514ba9560c.jpg)
![Purple 2](https://user-images.githubusercontent.com/52841061/80897569-bca82600-8cbf-11ea-83dd-49766b589a06.jpg)
![Purple 3](https://user-images.githubusercontent.com/52841061/80897570-bf0a8000-8cbf-11ea-98ba-32978385ea9f.jpg)

**Comment by JMartinez9820** [comment]
Idk how this happens, my guess is that no proper burn sprites were made yet. The Cyber Baron itself is not overhauled, but I might just make a quick fix by modifying the burn death to just using the Hell Knight/Baron burning death animation. Not a priority rn, will be fixed when the monster overhaul gets to Barons.

**Comment by JMartinez9820** [comment]
Okay, I just fixed it right now. Turns out that the wrong death type was used in Death.burn under SpawnItem, and wrong sprites used for Death.blackhole under the same SpawnItem name. Very easy fix. Check pull #375 for more details.

**Comment by JMartinez9820** [comment]
@Mr-Blazkowicz This issue can be closed. Fixed in latest commit from yesterday.
