### ISSUE TITLE
Health Regeneration and Level Enhancement System is doesn't works.

### ISSUE THREAD

**Issue by WiPoppiMk-4** [pa1nki113r/Project_Brutality#383]
I playing Project Brutality on AMD Ryzen 5 1600 and RX470.
GZDoom is version g4.3.3 and frontend is dlaunch.
someone show me Health Regeneration code for me?

**Comment by WiPoppiMk-4** [comment]
by the way I tried add Labels but I can't no to do.
because I'm just beginer of github.

**Comment by JMartinez9820** [comment]
@WiPoppiMk-4 Map Enhancement System and Health Regeneration (along with the old ledge grabbing system) are officially scrapped. Even though they have options, they don't work anymore. Those options will be removed in the future.

**Comment by JMartinez9820** [comment]
As for Health Regen, you can use [this] (https://forum.zdoom.org/viewtopic.php?f=37&t=47788) instead. The old health Regen system, it was part of the old parkmore ledge grab system, which was scrapped in favor of ZMovement's.
