### ISSUE TITLE
Super shotgun bug

### ISSUE THREAD

**Issue by 34-cyrpty** [pa1nki113r/Project_Brutality#384]
Whenever i slice with the super shotgun i grow a third arm and slice with it. Is this a bug or its already planned to be fixed?

**Comment by JMartinez9820** [comment]
It will be fixed soon, heck I might push a pull request right now. I've already fixed this, along with the Autoshotgun, Deagle and Dual Weild SMGs on my end.

**Comment by JMartinez9820** [comment]
I forgot to mention this, but part of this is a duplicate of #194 .

**Comment by 34-cyrpty** [comment]
sorry i havent realised it

**Comment by goldenmob72** [comment]
Since this is Duplicate, I'm closing this issue
