### ISSUE TITLE
Unable Cancel Reloads

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#388]
When using a Full clip w/ the DMR or Carbine, When Reloading the weapon I cannot kick, Therefore I cannot cancel the reloading animations

This also applies w/ the Nailgun

**Comment by JMartinez9820** [comment]
Not a top priority.

**Comment by JMartinez9820** [comment]
Update:
Could be potentially possible with an overhaul to the kicking system.

**Comment by popguy12** [comment]
kicking system redone (and due to be redone again), closing
