### ISSUE TITLE
Dark Matter Rifle Dual Wield Doesn't Work

### ISSUE THREAD

**Issue by pokefan1543** [pa1nki113r/Project_Brutality#389]
I got the Dark Matter Rifle upgrade for the plasma rifle and I pressed the weapon state change button and the dual wield animation played but you can't shoot the Dark Matter Rifle when dual wielded. can you fix it?

**Comment by JMartinez9820** [comment]
I noticed that too, thanks for reporting. It's because of something called DualPulseCannonAmmo being removed, which is a sign that the Pulse Cannon (Dark Matter Rifle) is going to be overhauled in the future.

**Comment by JMartinez9820** [comment]
Unfortunately, I was wrong. I think it could be related to the removal of LeftPlasmaGunAmmo and RightPlasmaGunAmmo, which I think was used for the dual pulse cannon. Unfortunately, I currently have no way of fixing this, but I will keep trying. My only suggestion is to wait until the Pulse Cannons are overhauled.

**Comment by JMartinez9820** [comment]
Update 7:32: I fixed it! It turns out that it was calling DoublePlasmaGunAmmo on Fire2 (line 178), which was removed from the Plasma.dec code. I just changed it to DoublePulseCannonAmmo and it got fixed. I will push he fix to my pull request right away, check pull #375.

**Comment by pokefan1543** [comment]
cool!

**Comment by pokefan1543** [comment]
I just redownloaded the mod and I tried to dual wield the dark matter rifle but it keeps repeating 3 frames of the dual wielding animation and the only way to stop it is to select another weapon

**Comment by JMartinez9820** [comment]
I've noticed that too, I haven't found a way to fix it. If I do then I will update this

**Comment by JMartinez9820** [comment]
Fixed in newest commit. Issue can be closed

**Comment by JMartinez9820** [comment]
This issue can be closed. Fixed in newest prs
