### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by phryk** [pa1nki113r/Project_Brutality#390]
It's very unclear where the "official" source for Project Brutality's releases is, I for one can't figure it out and can only find a proper release for 2.03, not for any of the 3.x versions.

It would be nice if releases could be tagged in the git repo, so people can download specific releases here.

**Comment by scaryred24** [comment]
You are in the right place. If it ain't done by painkiller then you are in the wrong place. Forks exist but this is the official repo for it.

**Comment by phryk** [comment]
And I've already noticed that there's at least one release *branch*: https://github.com/pa1nki113r/Project_Brutality/tree/october_release

Would be super helpful if releases also got tagged, tho. I doubt many non-techies are able to figure out how to get a proper release from here. Which is a pity, because this mod is \ *amazing* / :)

**Comment by JMartinez9820** [comment]
In case you didn't know, Project Brutality is far from being stable since its just a work in progress. In the Discord server, you can see updates on github_logs. If you need to join the server here is the invite: https://discord.gg/2hJxXPc

**Comment by goldenmob72** [comment]
This is not an issue, Closing
