### ISSUE TITLE
Lava issue

### ISSUE THREAD

**Issue by 34-cyrpty** [pa1nki113r/Project_Brutality#391]
When i was in the stage called the crusher and i fell in the lava by accident it kept hurting me still when i jumped out of it, not sure if its a problem with my pc but im sure that this is a bug

**Comment by JMartinez9820** [comment]
@34-cyrpty Can you provide a video or gif of this happening? Also, do you have anything to reproduce this issue? Thanks. Make sure you have turned on "Hazards disable advanced movement" if you want to jump on hazard floors such as lava or acid. It can be found in Project Brutality ~> Gameplay settings.

**Comment by 34-cyrpty** [comment]
i might try getting this thing to work, this only happened to me the first time

**Comment by goldenmob72** [comment]
What JMart, This can be easily changed with the option
Issue closed
