### ISSUE TITLE
Mouse controls broken in v3

### ISSUE THREAD

**Issue by alex256z** [pa1nki113r/Project_Brutality#392]
(sorry for my English) In the v3 mouse controls feels not precise, as it was in v2. It's like a some sort of acceleration, or inertia. You can't shoot just in Q3-like style anymore. Without this mod(in clean gzdoom with doom2.wad mouse controls are OK)
(I'm played ALOT in v2.03)

**Comment by JMartinez9820** [comment]
The mouse controls to me are fine, what's wrong with your mouse movement? Mind if you posted a video or show me your settings?

**Comment by alex256z** [comment]
> The mouse controls to me are fine, what's wrong with your mouse movement? Mind if you posted a video or show me your mouse settings?

![Win Mouse](https://user-images.githubusercontent.com/13462761/82136662-aa2e0080-9818-11ea-978e-604c648b5726.png)
![gzd mouse settings](https://user-images.githubusercontent.com/13462761/82136663-ab5f2d80-9818-11ea-907d-42156ff4af46.png)
You can't see this on video, you only can feel it. In clean gzdoom WITHOUT mod v3 - no problem - it's feels like solid controls, In  this mod v2 - same solid control with mouse, and this v3 changes something, an it feels like there is a spring between your mouse and personage - when you stop moving mouse - camera stil moves a bit in that direction in some milliseconds(something like inertia). Just play in old Q3 arena. Ive tested it on 2 PCs with different Win, i tested different mouses and different mods - and same stuff only with v3 installed.

**Comment by alex256z** [comment]
I've found a problem. This is Tilt++ mod. It changes movement behavior and accelerates camera. And switching this OFF in options doesn't help, becaus it is in code.

**Comment by JMartinez9820** [comment]
Tilt++ is mainly based on player movement. Other camera movement motions coded in the animations. I might consider disabling Tilt++ by default in the future. I'm not sure what can be causing the mouse movement to be different in PB 3.0, mouse movement wasn't really touched, although it could be ZMovement. Idk though.

**Comment by alex256z** [comment]
> Tilt++ is mainly based on player movement. Other camera movement motions are coded in the animations. I might consider disabling Tilt++ by default by default in the future. I'm not sure what can be causing the mouse movement to be different in PB 3.0, mouse movement wasn't really touched, although it could be ZMovement. Idk though.

And you were right. I just tested both "Tilt++" and "Zmovement" mods on last gzdoom with clean doom2.wad, and BOTH of this mods cause weird mouse movement.

**Comment by goldenmob72** [comment]
This is not an issue anymore, Closing
