### ISSUE TITLE
Having Gore Issue

### ISSUE THREAD

**Issue by hastekrieg** [pa1nki113r/Project_Brutality#395]
Hi, ive been having this pop up consistently and I see no way to fix it, not sure if new problem or problem with my pc 
![Screenshot_Doom_20200611_184647](https://user-images.githubusercontent.com/66774275/84365046-3fec5e00-ac14-11ea-9553-c00f539bd038.png)

**Comment by Xeno1979** [comment]
For those seeing the message saying the sv_corpsequeuesize is at a low value, in the console, just type sv_corpsequeuesize 5000 and the error should be gone.

**Comment by JMartinez9820** [comment]
@hastekrieg Known issue, which I believe Brutal Doom does as well. Just type this in the console and you should be okay for now. I've been trying to find this cvar in the files and it's message, but I can't find it anywhere. I will keep searching though.
> sv_corpsequeuesize 5000

**Comment by JMartinez9820** [comment]
Once this is resolved then it can be closed
