### ISSUE TITLE
P_StartScript: Unknown script "Script_GetGunOffsetX" and P_StartScript: Unknown script "Script_GetGunOffsetY"

### ISSUE THREAD

**Issue by trainfan91** [pa1nki113r/Project_Brutality#396]
this appears when selecting lmg or unmaker.

**Comment by JMartinez9820** [comment]
This will be fixed in pull #375 . This is because the original ACS scripts calling that were removed in favour of ZScript.

**Comment by JMartinez9820** [comment]
@trainfan91 This issue can be closed. My fixes just got merged to master.
