### ISSUE TITLE
Zandronum testing

### ISSUE THREAD

**Issue by Ich-Henker** [pa1nki113r/Project_Brutality#398]
**Hey**, I greatly appreciate **Project Brutality**. To me and my fellow players it is the best classic Doom expansion thus far. So let me use this introductory sentences as a big **thank you**!

To cover my background I played the Eternal Doom Megawad, Lost Civilization, Doom I, Doom II, Plutonia and Extermination Day all with PB an GZDoom and had a wonderful time. Now we are playing Lost Civilization and Doom I and II with PB and Zandronum with three players survival Coop. This is where I can report issues. All issues are multiplayer issues, so can mostly be replicated when hosting a server and may not appear, when using Zandronum for singleplayer.

We are using Zandronum 3.0 within the correct install directory C:\Zandronum and with administrator rights for the exeutables so ini changes made with Zandronum are mostly kept.

**A. All PB Versions that are Zandronum compatible:** **This includes Version 2.03a from Mod DB!**

A1. The Overlord turns invisible after first being shot at or after he starts attacking the player. Allied freed marines or turret items can still shoot at him. He is not teleporting, he is just invisible. He works in GZDoom Singleplayer.

A2. Freed Marines: After commanding freed marines to hold positon and then to re-follow, the players that did not free them see multiples of said marine for everytime you command them in that manner.

A3.performancemode true
This cvar activates both janitors and the performance mode. We only needed the janitors to work. Performance Mode should be seperated from the janitors. 
A3.1 zdoombrutaljanitor 1 and zdoombrutaljanitorcasings 1 did not work on their own. I could make it run on the enhanced online version of PB within the custom parameter section(see *1).

A4. UDV-Bug. Just mentioning it here I know it is not of your making. Weapon names are displayed wrongly on the right side of the UDV when more players are connected - mostly scrambled text like blazr etc.

A5. Keys are shared between players does not work with blue, red or yellow skulls. There is a Zandronum Forum bug request, but they say it comes from mods using those pseudo keys in a different manner then regular keycards.

A6. Ledge grabbing should be disableable because it breakes a lot of maps.

A7. Performance mode is extra complicated to change because it requires a level restart wich is not possible in Zandronum multiplayer-server.

A8. Could you maybe get the HMG MInigun back, it was my favourite weapon but got swapped with the Nailgun right? :D It is such a shame, we loved it all!

**B. The latest PB Version 2.03a from Mod DB:**
[This may be neglectable for it works right now.]
B1.CVars like bd_NoOverlord do not work in Zandronum online multiplayer even when used in the Custom Parameter section of server creation or ingame via console and even when sv_cheats true is implemented in the Custom Parameter section and even when the PB_Allow_Sv_Chaets.pk3 is in the load order directly after ProjectBrutality 2.03a.pk3.
I found them to be working as intended (Preloaded within the Custom Parameter section of Zandronum) in a modified PB Version enhanced for online Play: [https://www.moddb.com/addons/project-brutality-30-for-zandronum-and-mobiles-v2]***1**
But even there I cannot change the Overlord back in from within the game via console. 
After achieving it there it seems it is preloaded within 2.03a too...but this could be just due to ini saves via Zandronum :/ 

Hope this issues do not annoy you and hope even more that your project will evolve. And if you need some testing for Version 3.0 let me know. On ZDL and GZDoom I am playing with a clone of this latest GitHub repository.
Bye, Armand.

**Comment by JMartinez9820** [comment]
This is an unauthorized version of Project Brutality made for Zandronum and is against PA1NKI113R's wishes. In the past he has warmed other people that attempted to upload PB 3.0 to ModDB. Also, PB is no compatibility with Zandronum due to new features.

**Comment by goldenmob72** [comment]
Only PB 2.03 is compatible with Zandronum

**Comment by Ich-Henker** [comment]
I edited the first post: All bugs listed under category A are present in PB  2.03a too.

**Comment by goldenmob72** [comment]
Contact em on The PB Discord

**Comment by scaryred24** [comment]
Unless Zandronum gains zscript support for 4.0 there won't be any compatibility with that. Zandronum 3.0 itself is based on a build of GZDoom 1.8.6 which came out in March 2014 therefore 6 years behind at the time of writing this. Notice that with GZDoom only the host needs to port forward unless its a true p2p connection which is supported. UPnP exists too and if you are going to be ruining netplay on a pc that you don't care for setting the ip of your device on your internal network to be assigned to a DMZ will work around all the port forwarding issues. Tunneling software like Hamatchi and VPNs like Radmin will also get you around the port forwarding issue.

Any and all of the problems with 2.03 that still remains in this unstable 3.0 build will be fixed if one reports it or will be with lots of re-coding to zscript anyways as its most likely been reported and will be on the queue of things to go fix. We can only do things one step at a time. As for suggestions It's best to voice your concerns in the [Discord server](https://discord.gg/2hJxXPc). These issue trackers are for bug reporting only.

**Comment by goldenmob72** [comment]
That being said ^ , This Issue is being closed
