### ISSUE TITLE
Grenade type select menu appears for M2 Heavy Plasma Rifle weapon special

### ISSUE THREAD

**Issue by vidaritos** [pa1nki113r/Project_Brutality#399]
See attached screenshot.

Steps to reproduce:

1. Select Special Grenade Launcher
2. Select M2 Heavy Plasma Rifle
3. Hold down weapon special key (weapon special for the grenade launcher appears still)

![Screenshot_Doom_20200623_092141](https://user-images.githubusercontent.com/31620802/85373366-7343bc80-b533-11ea-86e8-0420d9e49ede.png)

**Comment by JMartinez9820** [comment]
@vidaritos Known error. This will be fixed when the M2 Plasma Rifle possibly gets the weapon special wheel.

**Comment by JMartinez9820** [comment]
@vidaritos I can confirm that this bug is fixed in the newest commit. This issue can now be closed. However, for some reason this comes up again, don't hesitate to reopen this issue.
