### ISSUE TITLE
cant jump in liquids

### ISSUE THREAD

**Issue by yeyeyeety** [pa1nki113r/Project_Brutality#402]
if you are in a pool of liquid (any type) you are unable to jump

**Comment by JMartinez9820** [comment]
@yeyeyeety Not a bug, it's Intentional feature for Vanilla Doom based maps only. You turn off the Hazards Preventing Jumping in Project Brutality Settings > Gameplay Settings > Hazards Prevent Advanced Movement, or type pb_hazardmovement 1in the console.

**Comment by JMartinez9820** [comment]
This issue can be closed since not jumping in hazard liquids is only intended for vanilla-based maps only. To disable this, just turn on the option Hazards Prevent Advanced Movement in Project Brutality ~> Gameplay Settings, or type pb_hazardmovement 1 in the console.
