### ISSUE TITLE
Chainsaw a bit overpowered? (suggestion)

### ISSUE THREAD

**Issue by transcendreamer** [pa1nki113r/Project_Brutality#406]
Hi devs,

thank you so much for the efforts put into the latest updates and now PB looks very much more polished and balanced

the only thing is slightly out of balance (to me) is the chainsaw because it's very easy to step around a corner and just keep pressing fire button and chainsawing any forthcoming monsters

so my suggestion is adding fuel cans for chainsaw or sharing fuel cans from flamethrower 

by the way this was already implemented in Brutal Doom Black Edition mod

I feel that adding fuel limitation for chainsaw will make game-play a bit more tactical and challenging

with best regards...

**Comment by JMartinez9820** [comment]
@transcendreamer Suggestions do not belong here, I would suggest bringing this to the [Discord](https://discord.gg/2hJxXPc) server instead. Also, in my opinion having fuel for the chainsaw is a terrible idea. Take a look at how Brutal Doom 64 handled the chainsaw with the fuel, and you will see why. Or you can ask Scaryred24 about it, he can explain why he opposes it and how BD64's chainsaw was handled like.

**Comment by goldenmob72** [comment]
Since this is an issue, I'm closing this issue
