### ISSUE TITLE
There's something wrong with rendering when PB is loaded on a (new) custom map

### ISSUE THREAD

**Issue by ReaperJoe** [pa1nki113r/Project_Brutality#407]
So I decided to make some maps that utilize PB's features, namely advanced movement and pickup/enemy progression.
I did a part of the first map before testing and a weird visual bug cropped up.

This is what it *should* look like (this is with only the map wad loaded):
![Screenshot_Doom_20200711_113605](https://user-images.githubusercontent.com/68146505/87221330-8cd66800-c36b-11ea-9ea4-0c8b23aadc9f.png)

And this is what it looks like with the map wad and PB loaded:
![Screenshot_Doom_20200711_113531](https://user-images.githubusercontent.com/68146505/87221354-b98a7f80-c36b-11ea-9687-ac3fcb5d40f3.png)

The lighting on the "doorframe" and ceiling is correct, it should be very dark. But sectors next to it have the same light values, but are much lighter than they're supposed to be. All surface light levels are zero. Since the map works as intended with GZdoom without any mods loaded, and doesn't with PB loaded, I have to assume it's an issue with PB itself or some part of it.

Just in case it's relevant, I use:
GZdoom 4.4.2 x64
Ultimate Doom Builder r3518 x64
The only resource is a Doom II iwad.

Non-vanilla features I used in the map are one 3D floor, 8 dynamic lights and several slopes so far. Could I have possibly used something that conflicts with something else PB-related? Should I use PB as a resource when making maps for it?

Rendering API is OpenGL, hardware accelerated, with dynamic lights and shadowmaps enabled. But changing various display settings doesn't solve the issue.

Is there something in PB itself that could cause correct lighting on ceilings, but incorrect on walls/floor?

**Comment by JMartinez9820** [comment]
@ReaperJoe Since this is related to Ultimate Doom Builder, this bug may not be logged and unrelated to PB.. This is also due to the dynamic lighting BD/PB has. I would try using BDv21 to see if this persists. If you need help, feel free to jump into the [Discord](https://discord.gg/2hJxXPc) server for help. Dynamic lighting is currently not a big priority to focus on now.

**Comment by ReaperJoe** [comment]
@JMartinez9820 Yeah, the issue persists with BDv21, too. I'm going to assume it's something I did wrong in UDB with the map then and seek help on Discord per your advice. Thanks!

**Comment by goldenmob72** [comment]
Then in that case, Issue is closed
