### ISSUE TITLE
Lag when loading new game or load game

### ISSUE THREAD

**Issue by HaskiHero** [pa1nki113r/Project_Brutality#409]
When I start a new game or load game, the game will **freeze** and **lag** for a few second (5 second - 30> second). Is this a bug?

**Comment by JMartinez9820** [comment]
Not really a bug imo. Depending on your PC specs, load times may be slower. I believe this may be a duplicate of an issue, but we are aware of this. PB at its current state is very unoptimized which we will optimize later by rewriting a ton of code from the ground up to ZScript code. Mind if you post your PC specs? See if this happens outside of PB too.

**Comment by JMartinez9820** [comment]
@HaskiHero Also, which GZDoom are you using? I would recommend trying LZDoom to see if it's better or not. Otherwise try [this] (https://drive.google.com/file/d/1Dn49NLQQVVT5uyZ4f3KJz8BWXQYIGRbV/view?usp=drivesdk). Just put this in the main GZDoom directory. Otherwise, join the  [Discord](https://discord.gg/2hJxXPc)  server for help.

**Comment by HaskiHero** [comment]
"I would recommend trying LZDoom"

I'll try it

**Comment by HaskiHero** [comment]
Yep, it works! The chance to freeze and lag is reduced.

GZDoom: high chance to freeze and lag (freeze or lag time 5 second - 30> second)

LZDoom: small chance to freeze and lag (freeze or lag time 4 second - 18 / 23 second)

Note: I'm bad at english

**Comment by HaskiHero** [comment]
And...

"I believe this may be a duplicate of an issue"
sorry, I didn't know...

**Comment by HaskiHero** [comment]
it seems like it's also time for me to close this issue

(although I don't know whether this is a bug or not :P)

**Comment by JMartinez9820** [comment]
This issue can be closed if necessary.

**Comment by HaskiHero** [comment]
Ok
