### ISSUE TITLE
SGL pickup sprite fall

### ISSUE THREAD

**Issue by ATeenWhoIsWorkingOnBDCME999** [pa1nki113r/Project_Brutality#42]
SGL Pickup sprites falls through floors.

**Comment by scaryred24** [comment]
Can you elaborate and tell us what is actually causing this to happen?

**Comment by Cacodemon345** [comment]
This seems to be offset issue. It will be fixed later.

**Comment by TheMakelProject2** [comment]
> Can you elaborate and tell us what is actually causing this to happen?

not sure. Places, where it would spawn such as rocket launcher, spawn it is completely invisible.  Summoning it causes it to spawn and then disappear like a second later one it hits the ground.

**Comment by JMartinez9820** [comment]
This issue can now because closed as the offsets of the SGL have been fixed. If this issue comes up again, feel free to reopen it.
