### ISSUE TITLE
Throwing Shotgun guy head make my game crashed

### ISSUE THREAD

**Issue by Mdaffahanif** [pa1nki113r/Project_Brutality#437]
when i do some fatalities to some shotgun guy i take his head and throw it randomly and it suddenly crashed this happened for 3 time now

**Comment by Cacodemon345** [comment]
Please, post the crash log. Does the game abort to console if this happens or it crashes to desktop instead?

Also, run the mod with `vm_jit` turned off from the command line.

**Comment by Cacodemon345** [comment]
We couldn't replicate this bug. Did you update your PB version?
