### ISSUE TITLE
October 2019 build

### ISSUE THREAD

**Issue by saeed101286** [pa1nki113r/Project_Brutality#439]
Hello I was wondering if anyone has the GitHub bleeding edge build of project brutality 3.0 from October 2019. I would be heavily oblijed if someone can help me out with this. Thanks in advance.

**Comment by JMartinez9820** [comment]
Why do you want to play such an outdated build? This is not an issue and will not be logged. I think there is no copy that build right now.

**Comment by AmpedgamR** [comment]
I will send you a link of your desires sir, and what type of link you want it to be?

**Comment by scaryred24** [comment]
I don't recommend using an older build for any reason aside from tracing back how long a particular coding error has been unresolved for. If you are so inclined to use an older commit then follow this. Replace commit hash with the hash value of the particular build from October 2019.

https://stackoverflow.com/questions/31462683/git-pull-till-a-particular-commit#31463068

**Comment by saeed101286** [comment]
Thanks for responding so quickly. The reason I asked for that specific
build is it still had the environment enhancement system working properly
and the weapons and features feels complete to me at least. Sorry if my
post is in violation of githubs rules but kind sir, it would be really
helpful if somehow I got that build as I have looked for it from every
possible source but to no avail. Again my most sincerest apologies for any
misconduct. Thank u and good luck.

**Comment by saeed101286** [comment]
Thank you for your response.if it's a mega or MediaFire link it would
suffice.as it's downloaded by thousands of not millions from github,the
build might be in .zip format which requires me to raname it to .pk3 to
use. U can even send it via my email address.again thank u kind sir 4
helping me out. PEACE ✌️😂✌️

**Comment by scaryred24** [comment]
Mediafire nor Mega is how it's going to be distributed until it becomes stable. Also until the development team are set for a snapshot release, this is how things are going to be distributed for now at least. Renaming the file is not needed as GZDoom/LZDoom is good enough to accept a zip as a wad replacement. If you had pulled via CMD/Terminal or the desktop client, you would need to make that a pk3 yourself. That's just how things are going to be for the time being. It may change but don't count on it.

**Comment by cemtex-tk** [comment]
I have a copy dated December of 2019.  If you respond I can arrange a link for you to download.

**Comment by saeed101286** [comment]
Yes that will be more than enough. Thank u.

**Comment by cemtex-tk** [comment]
https://mega.nz/file/0EhRELQD#jJtyqn-FMXPOR_Yj04PlC5LHYV73kI3pATxHCklLs4s

I do not know if I modified it.  Likely not.

**Comment by saeed101286** [comment]
@cemtex-tk Thank you good sir and GOD BLESS😊😊☺️

**Comment by saeed101286** [comment]
@cemtex-tk well unfortunately the build u put up for download is very unstable in that it crashes a few moments after starting . Again thank u for ur kindness and I really do not want to force u any way but the October 2019 github build was what i'm really rooting for.

**Comment by goldenmob72** [comment]
Dude, Not a lot of ppl have that certain build. Most ppl have the Updated version of PB, and not the outdated ones.

**Comment by saeed101286** [comment]
I understand. It's just from various sources I have seen the build i'm looking for seems perfect. 😁😁😁

**Comment by phobos2077** [comment]
This repo dates back to 2018. There's no such thing as "build" because repo contains reedy to use files already. Just pick a commit you want and download zip.

**Comment by scaryred24** [comment]
```
well unfortunately the build u put up for download is very unstable in that it crashes a few moments after starting 
```

Thats because its bleeding edge. Expect anything to go wrong without notice. 

```
Dude, Not a lot of ppl have that certain build. Most ppl have the Updated versions of PB, and not the outdated ones.
```

Correct because anything before current master is without support. You will be urged to update if something is not working and you are on an older build. 

```
There's no such thing as "build" because repo contains reedy to use files already.
```
Unless you see anything in the release tab there is no build. 

```
Just pick a commit you want and download zip.
```
I will only condone the most recent commit. Older commits are unsupported an as-is. We will not help you if it doesn't work. 


Anyways this thread has ran its course. Locked.
