### ISSUE TITLE
UAC rifle dupe glitch

### ISSUE THREAD

**Issue by 34-cyrpty** [pa1nki113r/Project_Brutality#444]
So i killed a zombieman while he was teleporting and did this 
![something](https://user-images.githubusercontent.com/52837547/89130442-1f020400-d505-11ea-90f3-8331b8a25ebc.PNG)

**Comment by JMartinez9820** [comment]
@34-cyrpty Do you have any way to reproduce this problem?

**Comment by 34-cyrpty** [comment]
i might try it but it wouldnt be easy

**Comment by JMartinez9820** [comment]
Unable to replicate this issue. Also closing due to the lack of responses.
