### ISSUE TITLE
Pump shotgun ammo clip counter is missing from the fullscreen HUD

### ISSUE THREAD

**Issue by vidaritos** [pa1nki113r/Project_Brutality#449]
The pump shotgun ammo counter seems to be missing from the right side HUD. Both the double barrel and the auto shotgun has this highlighted on the HUD. 

![Screenshot_Doom_20200805_085716](https://user-images.githubusercontent.com/31620802/89414512-cca22c80-d72a-11ea-9c38-514e9dbea3d8.png)
Double barrel shotgun shows 2 / 2 correctly

![Screenshot_Doom_20200805_085729](https://user-images.githubusercontent.com/31620802/89414533-d62b9480-d72a-11ea-94ee-051e85921b30.png)
Auto shotgun shows 12 / 12 correctly

![Screenshot_Doom_20200805_085734](https://user-images.githubusercontent.com/31620802/89414546-dcba0c00-d72a-11ea-9f24-8ac3b07e88d0.png)
Pump shotgun ammo should show 11 / 11

**Comment by scaryred24** [comment]
Will look into this. For now a temp solution would be to turn the alternative hud off.

**Comment by vidaritos** [comment]
I should also add, the total ammo count for shell type ammo is also missing. Those counters are highlighted for other weapons, such as cells and bullets

**Comment by JMartinez9820** [comment]
@vidaritos The HUD icon missing is an oversight, since SHTCA1 was removed. This should be an easy fix as it's defined in the shotgun code, but it's not game breaking and very minor.

**Comment by vidaritos** [comment]
Alright, so with my very limited understanding of Decorate scripting language, I did two things:

1. 

https://github.com/pa1nki113r/Project_Brutality/blob/e70fde7f3c02f2e513463d8a8c1f887e53152fb8/actors/Weapons/Slot3/SHOTGUN.dec#L1670
Changed _SHTCA1_ to _SHTCA0_

2. 
In this file https://github.com/pa1nki113r/Project_Brutality/blob/master/BMAP/Shotgun.txt
I added the line:
`brightmap sprite SHTCA0 {map "SPRITES/WEAPONS/Slot 3/PumpShotgun/Pickup/SHTCA0.png"}`

Result (Pump shotgun ammo is now highlighted on the fullscreen HUD on the right side)
![shotgun](https://user-images.githubusercontent.com/31620802/91497564-828e1000-e8be-11ea-9a44-3f633c343f1e.png)

This worked for me, but I'm not sure if this was the right way to do it. Also, I am not sure if the shotgun icon should stay the same if you pickup the magazine upgrade or if it should be replaced with 9SMUA0.png in https://github.com/pa1nki113r/Project_Brutality/tree/master/SPRITES/WEAPONS/Slot%203/PumpShotgun/Pickup ?

Counter for total shells in inventory is still missing from this HUD, though.

Hope this helps @scaryred24
