### ISSUE TITLE
That recoil tho.

### ISSUE THREAD

**Issue by 2463583** [pa1nki113r/Project_Brutality#453]
The recoil on some weapons and all dual wields is excessive. I cannot dual wield any weapon without them pointing at the sky the next instant. Please add a recoil slider in the options that can nullify the recoil please. And as a side note please add a sequential shot option in the menu. Tapping fire and alt on mobile is quite irksome. 

Thanking you

m_falcone

**Comment by JMartinez9820** [comment]
This is suggestion and not a bug. I would suggest putting this in the [Discord](https://discord.gg/2hJxXPc) server instead.

**Comment by JMartinez9820** [comment]
Also, mobile support is not a big guarantee for the time being. The team doesn't fully endorse Delta Touch as phones are not as powerful as PCs. If you feel like making some changes go ahead. Just create a fork of the repo and make sure to test any changes made. As for making options, you make a cvar for them. Check cvarinfo on how cvars were made for this.

**Comment by 2463583** [comment]
Sorry about that. I will post it as soon as I can on the discord server.
I'm still waiting for the bot to accept me.

**Comment by JMartinez9820** [comment]
If for some reason you can't join the Discord server, your account maybe too young to join

**Comment by 2463583** [comment]
How old does my account have to be in order to join the discord server.

**Comment by JMartinez9820** [comment]
Three days old approximately

**Comment by 2463583** [comment]
Thanks, I just made an account the day before yesterday.

**Comment by 2463583** [comment]
But what are cvars? I don't know the first thing about coding. Do I have to
edit a txt file or something? Because I don't have a computer. What do I
have to do?

**Comment by 2463583** [comment]
How can I negate the recoil.

**Comment by 2463583** [comment]
I have looked it up online and have seen that a certain line of text
(A_Recoil) needs to be edited but I cannot find it. Can you please help me.

**Comment by scaryred24** [comment]
As what was stated earlier this is only for bug reporting. Feature requests and coding help is not what this place is for. Thread closed.
