### ISSUE TITLE
Super Shotgun Design looks comical

### ISSUE THREAD

**Issue by swc132994** [pa1nki113r/Project_Brutality#456]
This is not a bug but I think the look of the Super Shotgun looks comical. It just doesn't look like a weapon that can be taken seriously especially with the skull and looks like it belongs in a comic convention.

![image](https://user-images.githubusercontent.com/10770202/89843887-4d46aa00-dbbd-11ea-9ad4-e494eca0e26d.png)

**Comment by JMartinez9820** [comment]
This is not an issue, the SSG design is fine to me imo. This alone is just a complete mockery

**Comment by popguy12** [comment]
why not make your own skin addon
also, QSG has a similar design

**Comment by goldenmob72** [comment]
We better not see something like this again. Moving on.

**Comment by scaryred24** [comment]
Unless you can present us something better to use, better bring this over to the [discord server](https://discord.gg/2hJxXPc) and discuss about there there instead.
