### ISSUE TITLE
Can't switch to upgraded pump shotgun

### ISSUE THREAD

**Issue by indiavenster** [pa1nki113r/Project_Brutality#46]
Once you pick up the pump shotgun upgrade (higher capacity) you can no longer switch to that weapon once you've switched away from it. The issue is not 100% consistent, but it only very rarely works.

**Comment by scaryred24** [comment]
You should be able to just by pressing the hotkey for the shotgun a few times. Not sure what could be causing that.

**Comment by JMartinez9820** [comment]
This issue has been fixed since the Shotgun overhaul. This issue can be closed.
