### ISSUE TITLE
Railgun engine crash

### ISSUE THREAD

**Issue by randompbguy** [pa1nki113r/Project_Brutality#462]
the new railgun crash the engine when you try to shoot without ammo and reserve

**Comment by Martinozz** [comment]
Seems that there might be a second outcome, where GZDoom freezes without a crash dump. In case of using the alt-fire of Railgun, it seems fine. If you have 0/0 cells the title won't crash, it happens only when there is less than 12 cells in magazine and no more cells to spare.

**Comment by JMartinez9820** [comment]
I was able to fix this bug in my pull request. Check pull #461 for more details.

**Comment by goldenmob72** [comment]
With that being that fixed in that PR, This issue is now closed
