### ISSUE TITLE
Unable to switch shell type. 

### ISSUE THREAD

**Issue by DaDude001** [pa1nki113r/Project_Brutality#472]
Forgot to add description.
Whenever I hold the weapon special key (spacebar is what i have it bound to)
nothing happens for the shotgun. No wheel, no shell switch animation, nothing.

**Comment by JMartinez9820** [comment]
@DaDude001 I have made a fix for this bug, check pull #470

**Comment by JMartinez9820** [comment]
Update: This bug is now fixed in the new commit to master and can now be closed.

**Comment by JMartinez9820** [comment]
This issue can be closed.
