### ISSUE TITLE
Suggestion: Use faster doomguy fatalities with either Berserk Packs or Demon Strength Runes (just one of the two)

### ISSUE THREAD

**Issue by CBecker2K** [pa1nki113r/Project_Brutality#473]
I had a thought that it might be cool to incorporate the faster fatality speeds (from pull #362) for either Berserk Packs or Demon Strength Runes (only one of the two) to give them a bit more separation / variation.

Not sure which one would be better suited to have the speed boost from a gameplay standpoint (if at all).

**Comment by JMartinez9820** [comment]
Suggestions don't belong here, this is for bug reports. I would recommend bringing this to the [Discord](https://discord.gg/2hJxXPc) server instead.

**Comment by CBecker2K** [comment]
I see issues with suggestion labels so I posted it here.
