### ISSUE TITLE
Errors part of loading the game

### ISSUE THREAD

**Issue by ProyectoG1224** [pa1nki113r/Project_Brutality#475]
I have loading errors and I don't know how to repair it, for example the exploding bullets from the shotgun, I already updated the GZdoom and I did everything but it doesn't load me. If I load the game but there is part of the mod that I do not think, an answer can help me please.

**Comment by JMartinez9820** [comment]
@ProyectoG1224 Can you please explain me your load order, and a screenshot please? If you're using an add-on, the devs do NOT recommend report bugs from add-ons. Bugs report with the use of add-ons are invalidated.

**Comment by ProyectoG1224** [comment]
Cuando cargo el juego me las me dan, y no consigo algunas cosas fatales, me
pueden dar una solución.

**Comment by JMartinez9820** [comment]
A majority of the startup warnings have been eliminated, however the A_CustomMissile deprecation (newly introduced), and some unknown inventory stuff still remain.

**Comment by JMartinez9820** [comment]
Most of the errors are now fixed, issue can now be closed.
