### ISSUE TITLE
Certain key bindings not saved

### ISSUE THREAD

**Issue by ak1dd** [pa1nki113r/Project_Brutality#48]
when playing solo I dont' want to accidentally hit the taunt or the rolling.   I go into the in-game menu, hit backspace for all the taunt and rolling options so they are blank.  Return to game, restart and they are back to defaults.   I can't find any other settings that are not saved correctly.

**Comment by scaryred24** [comment]
Make sure you have the ini file that is generated with gzdoom not set to read only and try again.

**Comment by ak1dd** [comment]
it isn't read only - and it is only the keys I mention that aren't saved.
