### ISSUE TITLE
Crashing to console upon picking up certain weapons

### ISSUE THREAD

**Issue by iceejake** [pa1nki113r/Project_Brutality#488]
My game crashes to the console with the attached error message. So far this has only happened with the SMG and the revolver. I can cheat with the "give all" command and add them in my inventory with no issue. But the act of actually picking them up from the ground causes the crash. Suggestions? I am playing on the most recent version of PB 3.0 and running GZDoom 4.4.2
![Screenshot (2)](https://user-images.githubusercontent.com/70847538/92326483-a7058d00-f020-11ea-8299-60107f8bca43.png)

**Comment by JMartinez9820** [comment]
@iceejake You're using an extremely outdated build of PB, please update! This bug has since been fixed. Once you update to the latest build master build this can be closed.

**Comment by JMartinez9820** [comment]
This issue can be closed, as it's from an outdated build.

**Comment by JMartinez9820** [comment]
This issue can be closed.
