### ISSUE TITLE
level enhancements

### ISSUE THREAD

**Issue by Mechanical-sanity** [pa1nki113r/Project_Brutality#49]

**Comment by Mechanical-sanity** [comment]
the level enhancements from BDv21 RC2b beta are not here... Just something I noticed, but hopefully it could be translated over here?

**Comment by Mechanical-sanity** [comment]
the level enhancements from BDv21 RC2b beta are not here... Just something I noticed, but hopefully it could be translated over here?

**Comment by TheMakelProject2** [comment]
Will not be implemented until full release.

**Comment by JMartinez9820** [comment]
All of BDv21's level enhancements or any other assets will not be implemented until BDv21 is fully released.

**Comment by scaryred24** [comment]
> 
> 
> All of BDv21's level enhancements or any other assets will not be implemented until BDv21 is fully released.

Not only that but the focus right now is not to fully implement this feature just yet. It will be at a later date.
