### ISSUE TITLE
 Flamethrower release error

### ISSUE THREAD

**Issue by ProyectoG1224** [pa1nki113r/Project_Brutality#491]
Hello, I need help, why doesn't the Mancubus demon give me the flame spear, or is it a configuration part and I don't know how to activate it? 
![a](https://user-images.githubusercontent.com/40685681/92518726-cbab6180-f1e6-11ea-869d-6b3f0aeec584.PNG)
![2](https://user-images.githubusercontent.com/40685681/92518727-cc43f800-f1e6-11ea-807f-1d0194f1abb7.PNG)

**Comment by vidaritos** [comment]
Use your fists/chainsaw/kick repeatedly on the body

**Comment by JMartinez9820** [comment]
@ProyectoG1224 Someone on Discord apparently had this issue too. My recommendation is to switch to GZDoom 4.3.3 or LZDoom 3.86 if that works, as the latest version is horrible and plagued with bugs and technical issues.

**Comment by JMartinez9820** [comment]
One more thing, check your gore settings as well (located in Project Brutality/Visual Settings/Gore and Debris Settings), that could be why as well. Nash Gore limits a value of gib spawns, which is what the Flame Cannon spawn is detected as. Increase the gib amount to a higher value if necessary.

**Comment by ProyectoG1224** [comment]
thanks for your help

**Comment by LawlietBRVL** [comment]
> Hello, I need help, why doesn't the Mancubus demon give me the flame spear, or is it a configuration part and I don't know how to activate it?
> ![a](https://user-images.githubusercontent.com/40685681/92518726-cbab6180-f1e6-11ea-869d-6b3f0aeec584.PNG)
> ![2](https://user-images.githubusercontent.com/40685681/92518727-cc43f800-f1e6-11ea-807f-1d0194f1abb7.PNG)

hud mod?

**Comment by JMartinez9820** [comment]
@LawlietBRVL Cats Visor. You can find it on ModDB.
