### ISSUE TITLE
Chainsaw sound occurs even if the weapon is thrown away

### ISSUE THREAD

**Issue by DemonSlayer1997** [pa1nki113r/Project_Brutality#495]
The sound of the chainsaw continues if the chainsaw is thrown away . Sound cuts out (if Doomguy shows his finger
https://www.youtube.com/watch?v=sH-5M6zqviY

**Comment by JMartinez9820** [comment]
Oversight. It's because the sound has a loop. Only way to fix this is adding an A_StopSound at a weapon's ready state, minor priority atm.

**Comment by JMartinez9820** [comment]
Fixed in latest commit

**Comment by D3X1KAXYZ** [comment]
Same thing seems occur with the railgun.
