### ISSUE TITLE
[improvements] A couple of ideas

### ISSUE THREAD

**Issue by marcofbbr** [pa1nki113r/Project_Brutality#496]
Hi,
 I wanted to provide with some ideas that in my opinion could be fun to add to this project. 
Please note that I am not a coder so I don't know how feasible it is to implement those things. Excuse me if my request are non-sense.
--1-- 
increase the "hide (shoot) and seek" factor for some of the monsters. One of the things I liked most of Half life , was meeting the marines. They were somehow organised , fast ,smart, stealth and they liked ambushes. Perhaps the idea should be copied somehow. 
--2--
Descent2 has also a thief (non attacking) robot stealing your weapons. This could become a character who follows  and attacks you (with the stolen weapons ) between the maps and it get  stronger and stronger if you don't spend some time trying to kill it. In Descent2 the bot was giving back some of the weapons only when killed but that always required some  effort as he was fast and evasive.
--3--
When I played Quake in the '90s I remember using a bot to train myself (offline) on specific maps for my death matches. Those bots were quite smart, using the same weapons and the game experience was similar to playing with  humans. Their skill could be adjusted. Perhaps you can "borrow" the code of those bots and use it in BD and reserve some areas of the map to fight against this hardcore bot in addition to the standard monsters?.It could be a nice surprise effect to deal with a strong opponent.. The skill of the bot ( precision, speed...etc ) could be related to the score the player at the end of the map for example. This could be mixed with the idea at point 2 and the thief might try to kill you at some point
http://easttown.co.uk/quake/reaper.html
http://easttown.co.uk/quake/zeus.html

**Comment by goldenmob72** [comment]
This is not an Issue, This is a Suggestion (s)
Please make suggestions in the Suggestions text channel in The Project Brutality Discord server
https://discord.gg/2hJxXPc
