### ISSUE TITLE
Super Grenade Launcher instant grenade detonation

### ISSUE THREAD

**Issue by DaWrecka** [pa1nki113r/Project_Brutality#499]
Steps to reproduce:
*) Start a coop game
*) Equip Super Grenade Launcher
*) Launch a grenade and detonate it using the alt-fire trigger such that the explosion kills you
After respawning, all grenades fired from the weapon will detonate instantly, right in the player's face.
This state persists across map changes.

Tested with PB 2020-08-31 on GZDoom 4.4.2

**Comment by Cacodemon345** [comment]
Right now, multiplayer/coop support has been kept a minor priority as Zandronum support was dropped for PB 3.0.

**Comment by JMartinez9820** [comment]
@DaWrecka I have fixed this in my pull request, #616. Check out my [branch](https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch) and test it out.
