### ISSUE TITLE
equipping quad shotgun shows dual

### ISSUE THREAD

**Issue by ak1dd** [pa1nki113r/Project_Brutality#508]
if you toggle through the shotgun stack after you get the quad shotgun the dual will show for a moment during the switch.

Related - why not allow selecting the dual?  You have to go through the extra step of setting double mode on the quad when the dual shotgun is easier to choose, works like the other "gun stack" toggling AND is very easy to determine what shotgun mode you are using.

**Comment by Leonellus2033** [comment]
It also happens with the deagle, Lmg and pulse cannon, it also happened with the unmaker but I think they solved it

**Comment by JMartinez9820** [comment]
Known error. Very minor and not game breaking, but this will be fixed later.

**Comment by ak1dd** [comment]
Thanks JMartinez.   It is minor.   Any chance you could leave the double barrel in the weapon rotation?  Why is it completely replaced with the quad and then you have to set the quad to dual fire-mode?   Seems it would be easier and clearer to allow the toggle to happen like the single-to-double.  Thanks.

**Comment by JMartinez9820** [comment]
@ak1dd It's due to dual wielding now being tied under one single script, rather than two separate scripts. Currently this is not a major priority at the moment.
