### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Mechanical-sanity** [pa1nki113r/Project_Brutality#51]

**Comment by Mechanical-sanity** [comment]
for whatever reason, PB is not running the best. Even in E1m1, The fps dips quite a bit. Is there a fix for this?

**Comment by TheMakelProject2** [comment]
Jesus christ. The amount of issues.

**Comment by TheMakelProject2** [comment]
> for whatever reason, PB is not running the best. Even in E1m1, The fps dips quite a bit. Is there a fix for this?

Maybe because your computer is bad? Try turning down some settings.

**Comment by scaryred24** [comment]
> 
> 
> for whatever reason, PB is not running the best. Even in E1m1, The fps dips quite a bit. Is there a fix for this?

Please provide your pc specs.

**Comment by Cacodemon345** [comment]
PB has been going down on performance. We are still finding a fix for the performance issue.

**Comment by scaryred24** [comment]
This is an ongoing issue that is being tackled throughout development. Will have to close this one.
