### ISSUE TITLE
Crash to console using specials wheel and grenade launcher

### ISSUE THREAD

**Issue by Kanareika** [pa1nki113r/Project_Brutality#514]
1. Select acid grenades on grenade launcher
2. Try to switch shotgun shell type or chaingun mode
3. Game crash to console with following text:

VM execution aborted: array access out of bounds. Max. index = 3, current index = 4
Called from PB_SpecialWheelHandler.RenderOverlay at
Project_Brutality-master.zip:zscript/pbwheel/ev_drawer_special.zsc, line 24

**Comment by JMartinez9820** [comment]
I have no issues when doing this. Which GZDoom version are you using? If you're using the latest version, I would suggest downgrading to GZDoom 4.3.3 or LZDoom 3.86. The latest GZDoom version is awful and is plagued with memory leak issues and other bugs.

**Comment by Kanareika** [comment]
GZDoom g4.3.3. No troubles in LZDoom.
![image](https://user-images.githubusercontent.com/10144329/93911236-92610e80-fd1b-11ea-8371-3fb7c9cc1e15.png)
