### ISSUE TITLE
Assault Rifle Glitch: Zooming in and then reloading with clip

### ISSUE THREAD

**Issue by AvienJ** [pa1nki113r/Project_Brutality#520]
With the assault rifle, if you zooming and then reload with a full clip it will play the unzoom animation but keep the zoomed-in FOV.

https://youtu.be/gpuRx7YC1Lo

**Comment by JMartinez9820** [comment]
Interesting. I'll take a look and see if this can be fixed or not, this is probably related to the holding cvar. Thanks for reporting.

**Comment by JMartinez9820** [comment]
@AvienJ Okay I just fixed it on my branch. Check pull #501.
