### ISSUE TITLE
Health regen not working 

### ISSUE THREAD

**Issue by jodianlord** [pa1nki113r/Project_Brutality#526]
Health regeneration option is no longer working.

The regeneration script previously present in SRC/cvars.txt is missing. By replacing ACS/cvars.o with an older version, I was able to get health regeneration working again.

**Comment by JMartinez9820** [comment]
@jodianlord Health Regeneration was scrapped, its option is still a remnant of some removed options. This option will be removed in pull #524, so don't worry. The old Health Regen was old, outdated and hacky, and other add-ons did it better, like this one. This issue can be closed if necessary.
https://forum.zdoom.org/viewtopic.php?style=12&f=37&t=47788
