### ISSUE TITLE
Auto reload gone?

### ISSUE THREAD

**Issue by Ph0rk0z** [pa1nki113r/Project_Brutality#528]
Maybe I'm taking crazy pills but it looks like latest download disabled auto reloading. So now I dual wield shotguns and if I don't manually reload they click.

**Comment by JMartinez9820** [comment]
Auto reload is still in the game, just not on the dual wielding due to new dual wield system in place. This will be fixed and tweaked upon later.

**Comment by Ph0rk0z** [comment]
Ok, that makes sense.
