### ISSUE TITLE
title screen on widescreen

### ISSUE THREAD

**Issue by ak1dd** [pa1nki113r/Project_Brutality#53]
this is a suggestion - because it works as is...  see the screenshot.  The embers fly all the way across the screen and it looks fantastic.   A minor suggestion, use a background image that uses the same color as the areas without the bitmap.  It would look like widescreen greatness.   Not going to gush on github, but PB is fantastic.
![2018-11-08 10_33_01-project brutality 3 0](https://user-images.githubusercontent.com/38289720/48219713-0d94c380-e342-11e8-958d-39fd28b552c7.png)

**Comment by scaryred24** [comment]
Unfortanetely somewhere along the lines of development of Gzdoom, with 3.3+, the title screen has been broken since. We are looking into the possiblity on fixing this but right now this is not top prioirty. You can expect a fix in the future.

**Comment by ak1dd** [comment]
Understood and thank you.  It might look really great if it was minimal with just a bitmap that had the logo and the embers blowing across the whole screen.   Anyway, appreciate the response.
