### ISSUE TITLE
Load times are insane

### ISSUE THREAD

**Issue by ExtraLargeCox** [pa1nki113r/Project_Brutality#530]
Load Times take from Two in a Half Minutes to Me having too restart The Computer.

**Comment by D3X1KAXYZ** [comment]
Check your rendering mode. you might be running in software instead of OpenGL or Vulkan.

**Comment by JMartinez9820** [comment]
That, or your computer specs are too weak. What are your PC specs?

**Comment by JMartinez9820** [comment]
Another suggestion I have to try using LZDoom instead of GZDoom. The latest GZDoom version is terrible has a lot of bugs, including memory leaks.

**Comment by TonyH1234** [comment]
You might have cache GL textures on. If so turn it off.

**Comment by D3X1KAXYZ** [comment]
This issue has been inactive for awhile. If you still have this issue feel free to reopen it or join us on discord: https://discord.gg/2hJxXPc
For now, i shall close this issue.

**Comment by Cacodemon345** [comment]
PB taking too much time to load on certain configurations is a known thing. You may consider moving PB to a SSD drive in the meanwhile.
