### ISSUE TITLE
Chainsaw and shotgun on buckshot keep swapping skins. 

### ISSUE THREAD

**Issue by Dan9001** [pa1nki113r/Project_Brutality#538]
The chainsaw keeps going from vanilla to PB skin constantly while it is idling, shotgun skin changes to vanilla when buckshot is selected.

**Comment by JMartinez9820** [comment]
@Dan9001 Are you loading a map pack? Make sure to always load map packs before PB. Failure to do so will cause sprite conflicts, as the Chainsaw and Shotgun share the same sprite name. This what a load order should look like.

* Maps
* Soundtracks or texture packs
* PB
* Add-ons, such as huds

**Comment by JMartinez9820** [comment]
This can be closed
