### ISSUE TITLE
PB multiplayer

### ISSUE THREAD

**Issue by ak1dd** [pa1nki113r/Project_Brutality#54]
set up local game - you get dropped from the game often.   Regularly you will not be able to switch weapons until you restart the game/server.  Key bindings regularly don't work.    Sorry to be vague but I am willing to try fixes if any of this helps.  Single player seems to be pretty close to done - but multiplayer is really unstable now.

**Comment by scaryred24** [comment]
Zandronum and multiplayer support has been dropped since early 2017 and we see no need to implement that. If you can get it working with Gzdoom, then good on you. Otherwise Project Brutality has shifted development to be more aimed towards singleplayer uses.

**Comment by Cacodemon345** [comment]
Multiplayer support is not going to be a thing unless Zandronum 4.0 is released. Besides GZDoom's netcode is shitty as hell.
