### ISSUE TITLE
Switching weapon and pressing weapon upgrade button while loading a savegame crashes LZDoom ( Access Violation )

### ISSUE THREAD

**Issue by SharlLegreg** [pa1nki113r/Project_Brutality#548]
Ways to reproduce : 

1. Grab some weapon with upgrades ( or enter Give All in Console )
2. Create a savegame.
3. Kill yourself
4. Respawn.
5, While the melting screen is in process, spam 'switch weapon' keys ( 1, 2, 3 ) and weapon upgrade key.
6. LZDoom would crash from Access Violation.

`Code: C0000005 (Access Violation - tried to read address 00007FF8F953DD84)
Address: 00007FF7BB29963C
Flags: 00000000
`
[CrashReportgit.zip](https://github.com/pa1nki113r/Project_Brutality/files/5586018/CrashReportgit.zip)

**Comment by SharlLegreg** [comment]
Extra infos ( from dxdiag ) : 

Windows 10 19041 Pro 64 bit
Intel i5-4300U Quadcore
8GB Ram
DirectX 12
Intel HD Graphics

**Comment by JMartinez9820** [comment]
@SharlLegreg I believe this may be a duplicate of #341. Make sure to look at any opened or closed issues before posting. Also, check this branch here, it's assumed to have fixed this and that issue.
https://github.com/pa1nki113r/Project_Brutality/tree/pdabranch

**Comment by SharlLegreg** [comment]
> @SharlLegreg I believe this may be a duplicate of #341. Make sure to look at any opened or closed issues before posting. Also, check this branch here, it's assumed to have fixed this and that issue.
> https://github.com/pa1nki113r/Project_Brutality/tree/pdabranch

I was using that branch. and I did not move the mouse at all just to be sure that wasn't the case.

**Comment by JMartinez9820** [comment]
My only other suggestion to change the screen wipe style to Burn, Crossfade or None. This can be found in the Display Settings, its called Screen Wipe Style.

**Comment by SharlLegreg** [comment]
alright, I tried it again, and I manage to pinpoint the problem I guess. this has a very high chance of success. also the burn, crossfade or none does not prevent the error, only 'lowers' the chance of it happening.

2. save the game with a weapon with the upgrade wheel thingy.
3. kill yourself.
4. load the save game FROM the Menu, not by pressing use.
5. spam weapon keys and upgrade weapon key.

bear in mind my programmable mouse ( which was the root of the problem in #341 ) was unplugged, so it has nothing to do with the mouse.

I also tested it in GZDoom. burn, crossfade did prevent it from happening ( for now ).

**Comment by JMartinez9820** [comment]
@SharlLegreg See if this issue persists in GZDoom GLES. LZDoom is no longer recommended by most players now, since GLES runs better than LZDoom at times.

**Comment by SharlLegreg** [comment]
> @SharlLegreg See if this issue persists in GZDoom GLES. LZDoom is no longer recommended by most players now, since GLES runs better than LZDoom at times.

Should i use the pdabranch fix or the latest GitHub build?

**Comment by JMartinez9820** [comment]
@SharlLegreg Latest Github build. PDABranch is outdated.

**Comment by SharlLegreg** [comment]
I believe it might be fixed. Can't say for sure tho; I'm on a different hardware spec and can't access the old hardware. But for now, I cant replicate the issue therefore I will close this issue until I got my old hardware and get it tested.
