### ISSUE TITLE
Activate and Toggle Equipment hotkeys do not function.

### ISSUE THREAD

**Issue by CaptPatrick01** [pa1nki113r/Project_Brutality#55]
(Master Branch) Pressing them only pastes 
P_StartScript: Unknown script "GrenadeHotkey"
and
P_StartScript: Unknown script "ProximityMineHotkey"
to the console. Leaving me unable to use my grenades.

**Comment by scaryred24** [comment]
Thanks for reporting that. We will be fixing that in a future build.

**Comment by scaryred24** [comment]
Issue kept open for far longer than I'd originally had anticipated. If one may let me know weather or not this is ongoing do open this back up again. Otherwise I'm closing it until it can be fixed at a later point in development.
