### ISSUE TITLE
Spent nailgun ammo does not move along with a moving platform

### ISSUE THREAD

**Issue by SharlLegreg** [pa1nki113r/Project_Brutality#550]
Ways to reproduce :

1. Find a moving platform either moving horizontally or vertically.
2. Shoot nailgun
3. Activate the platform
4. the spent nailgun ammo does not follow along with the platform
![Screenshot_Doom_20201125_171412](https://user-images.githubusercontent.com/63714563/100207301-6b54d200-2f42-11eb-8afc-2558e6dee915.png)

tbh it's a minor bug since spent nailgun ammo going to disappear anyway.

**Comment by goldenmob72** [comment]
@JMartinez9820 look into this when you can please.

**Comment by JMartinez9820** [comment]
Closing due to the lack of response.
