### ISSUE TITLE
Player is stuck in chase cam after a few fatalities

### ISSUE THREAD

**Issue by vidaritos** [pa1nki113r/Project_Brutality#553]
Video: [youtube clip](https://youtu.be/XT-MKHHKzP4?t=10)

It's not possible to disable it with the chasecam toggle (Options -> Customize Controls -> Other -> Chasecam)

GZDoom 4.5.0
PB 3.0, as of commit 417306e1b9380bfb6cd80e1007f27b4bd092998f

No other mods were used.

**Comment by JMartinez9820** [comment]
@vidaritos Try using my branch that's in my upcoming pr, #554. See if that fixed this issue or not.

**Comment by vidaritos** [comment]
Thanks, that did the trick, closing
