### ISSUE TITLE
Dropped Chaingun ammo

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#556]
Not sure if this is a bug or intentional. A dropped chaingun gives 50 ammo while an ammo box gives 25. 50 seems excessive, maybe should be 10 or 15?

**Comment by JMartinez9820** [comment]
Hmmm... Interesting. I'm thinking about reversing it, 25 or 20 given from just the Minigun, while the Rifle/Minigun Ammo box should give either 40, 45 or 50.

**Comment by secretagentjr** [comment]
the dropped chaingun ammo is meant to be 50. pa1n actually changed it but likely forgot to change the ammo boxes to the same amount

**Comment by TonyH1234** [comment]
The ammo boxes were always 50. Only recently changed to 25. You get less ammo with every other weapon compared to its ammo box. Chaingun should be the same.

**Comment by JMartinez9820** [comment]
Um, I checked the script for the Ammo box and the amount the boxes give the player is 50. Just like with the Minigun.

**Comment by TonyH1234** [comment]
You're right. I WAS getting half before. Strange. An earlier build maybe? I was even getting 6 instead of 12 shells from a box. I thought it was a deliberate change. Even so, I still think a dropped chaingun should give less ammo than a box to bring it in line with the other weapons.

**Comment by JMartinez9820** [comment]
@TonyH1234 How does this sound?
Minigun gives 30 rounds when picked up.
NormalClipBox gives 40 rounds when picked up.
NormalClipBoxBig gives 65 rounds when picked up.

Check pull #566 if you want to try it out.

**Comment by TonyH1234** [comment]
I think the boxes are fine. Maybe 25 for a minigun. Seems like a cheat when you kill a bunch of chaingun guys and you get 50 frm each one.
