### ISSUE TITLE
Icon for Armor in HUD does not change when picking up Megaarmor Power Up

### ISSUE THREAD

**Issue by GeoDash897** [pa1nki113r/Project_Brutality#567]
The armor icon in the HUD does not change when picking up a **Megaarmor** power up. 
I tested this on two maps using the most current master branch version of PB (Latest commit = **11/30/20**) and used **GZDoom 4.5.0**
* On **Map 06** of Extermination Day (I downloaded the pinned version in the community mods chat in the official discord server) 
*  On Map 13 of Doom 2. 
Both of them showed the same result.
**Map 06 of Extermination Day**
![Screenshot_Doom_20201209_164340](https://user-images.githubusercontent.com/55932902/101695037-03be7c80-3a42-11eb-8fc5-796403b0e495.png)
![Screenshot_Doom_20201209_164351](https://user-images.githubusercontent.com/55932902/101695075-12a52f00-3a42-11eb-88cf-89ad09653ea3.png)
![Screenshot_Doom_20201209_164359](https://user-images.githubusercontent.com/55932902/101695078-146ef280-3a42-11eb-8709-732e6a194821.png)

**Map 13 of Doom 2**
![Screenshot_Doom_20201209_165156](https://user-images.githubusercontent.com/55932902/101695124-22bd0e80-3a42-11eb-8f87-8729b5e4d7fd.png)
![Screenshot_Doom_20201209_165206](https://user-images.githubusercontent.com/55932902/101695132-2486d200-3a42-11eb-87fc-725d6ee76387.png)

This is different from previous versions of this mod where the HUD adapted to the Megaarmor. (I do not have screenshots of this, but I do remember it changing color).
Is this a bug/oversight or is it intentional?

**Comment by JMartinez9820** [comment]
Bug/Oversight. The HUD as of right now is a WIP, so some of the work related to icons hasn't been done yet.

**Comment by GeoDash897** [comment]
Thanks for the answer! Should I leave this issue open then?

**Comment by JMartinez9820** [comment]
I would leave this open until more work has been put into the HUD, or when the HUD is complete.

**Comment by GeoDash897** [comment]
I'll leave it up then.

**Comment by JMartinez9820** [comment]
This can now be closed due to the HUD overhaul, which has a percentage on how much resistance one of the armors has, along with the armor icon filling up based on that damage resistance percentage.
