### ISSUE TITLE
SSG dual wield.

### ISSUE THREAD

**Issue by TheMakelProject2** [pa1nki113r/Project_Brutality#57]
SSG dual wieldis fubar

**Comment by scaryred24** [comment]
That isnt telling us anything. When reporting issues like that, you need to explain what led to the problem. Dual SSG does have problems yes but claiming that its fucked up beyond all repair is just telling us that it can not be fixed and needs to be removed. I would like it the next time to tell us what went wrong the best to your ability and not tell us how to do our jobs. Thread closed.
