### ISSUE TITLE
No message for Not Being Able to Dual Wielding for DMR or Carbine

### ISSUE THREAD

**Issue by GeoDash897** [pa1nki113r/Project_Brutality#572]
Hello!
This is more-so a small oversight rather than a bug, but there is no message for not being able to dual wield the **UAC30 DMR or UAC41 Carbine** (even though you can with those two weapons).

I noticed this inconsistency when playing the latest master branch version of PB (last commit = **11/30/20**) on **GZDoom 4.5**.

**Dual Wields with Message**
![PB Dual Wield Messages](https://user-images.githubusercontent.com/55932902/101962244-abba7e00-3bd9-11eb-9033-ba973a4bc01a.gif)

**UAC30 DMR and UAC41 Carbine (No Message)**
![PB Dual Wield No Messages](https://user-images.githubusercontent.com/55932902/101962329-e02e3a00-3bd9-11eb-9d12-41a23f5d478f.gif)

**Comment by JMartinez9820** [comment]
Fixed on pull #566, also on my branch.

**Comment by GeoDash897** [comment]
Alright. I assume this issue will close once the pull request is accepted?

**Comment by JMartinez9820** [comment]
Yes. I will update my PR's description to make this issue close.

**Comment by GeoDash897** [comment]
Thanks!

**Comment by JMartinez9820** [comment]
Also, feel free to join the [PB Discord](https://discord.gg/2hJxXPc) if you feel like it. Just make sure that your account is set up to receive DMs from anyone, and that your account isn't too young. If that's the case, then you will have to wait for three days in order for your account to verify properly.

**Comment by JMartinez9820** [comment]
Due to a pull request (#575) that is going to modify the Carbine, I had to remove the "You need two carbines to dual wield" message for the Carbine. This was done to prevent a merge conflict, it should return in a future version once that pr is merged.
