### ISSUE TITLE
Cyberdemon does not freeze when hit with Freeze Ray

### ISSUE THREAD

**Issue by GeoDash897** [pa1nki113r/Project_Brutality#573]
Hello!
I played this on the latest master version of PB (latest commit = **11/30/20**) on **GZDoom 4..5**.
I not sure if this is supposed to happen or not, but the **Cyberdemon** does not freeze when dying by the **UAC Cryogenic Dispersion Rifle**.

![PB CyberDemon No Freeze](https://user-images.githubusercontent.com/55932902/101968120-79b21780-3beb-11eb-8e4b-f83b6d49aac5.gif)

I find this kind of strange since you *can* freeze the **Spider Mastermind**

![PB Spider Mastermind Freeze](https://user-images.githubusercontent.com/55932902/101968130-83d41600-3beb-11eb-92d4-3df9c8d020cd.png)

Is this due to how the **Spider Mastermind** falls over before it dies (allowing you to freeze it) compared to the Cyberdemon (who just explodes).

Is this supposed to happen or was it an oversight?

**Comment by JMartinez9820** [comment]
Cyberdemon doesn't have an ice death yet, and the Spider Mastermind doesn't either. Although it uses GZDoom's generic IceDeath on it's dying state. Like usual, not a priority until the team gets to overhauling the Cyberdemon and other boss monsters.

**Comment by JMartinez9820** [comment]
Fixed in the latest commit, can now be closed.

**Comment by JMartinez9820** [comment]
Now completely fixed in the latest update
