### ISSUE TITLE
Switching weapons or opening weapon upgrade selection or equiment crashes LZDoom improperly and softlocks the entire operating system 

### ISSUE THREAD

**Issue by SharlLegreg** [pa1nki113r/Project_Brutality#574]
This might be #341 duplicate, but this never happened before and only on the latest branch. Switching weapons OR opening weapon upgrade selection wheel or equiment crashes LZDoom improperly ( no crash message or crash report ). and softlocks the entire OS. I can't use my mouse, close programs etc, only the keyboard functional. The only way to restore it is to reboot the system. Also it had nothing to do with screen melting effects.

**Comment by JMartinez9820** [comment]
That's... Very bad. Is there a way that this can be reproduced? I was unable to replicate the other bugs. I would keep this open as it sounds very serious.

**Comment by JMartinez9820** [comment]
Also, which LZDoom version is being used?

**Comment by SharlLegreg** [comment]
LZD 3.85, No error on GZD 4.3.3. literally press ( spam would work better ) either weapon keys ( 1,2,3 etc. ) Or the weapon upgrade wheel or the select equiment wheel.

**Comment by SharlLegreg** [comment]
Edit : GZD will crash to console with GetPacket : NOT INITIALISED error or improperly crash to desktop with no crash report. However triggering it is hard.

**Comment by SharlLegreg** [comment]
Update : vm_jit nor does in_mouse 0 prevent the crashes, only in_mouse 1,2,3.

**Comment by Cacodemon345** [comment]
What's more concerning is that the bug report related to this crash in ZDoom Forums has been made on-hold, leaving it basically unfixed for a good amount of time.

**Comment by Cacodemon345** [comment]
Update: A couple of assertion bugs has been fixed; try pulling the latest build from GZDoom's GitHub. Click the green check icon that appears in the light blue bar above the file list, click "Details" on any of them, click Artifacts and then click "Visual Studio 64-bit Debug". Unpack the contents of the zip file over an existing GZDoom devbuild installation. See if the situation is improved.

**Comment by JMartinez9820** [comment]
@SharlLegreg See if this issue is solved in newer GZDoom versions, particularly 4.6.1 gles, 4.7.1, or dev builds. If you need more questions just ask me on Discord

**Comment by JMartinez9820** [comment]
Due lack of responses, this will be closed.
