### ISSUE TITLE
Weapon bobbing error

### ISSUE THREAD

**Issue by Mrinthehouse** [pa1nki113r/Project_Brutality#577]
When I load up the mod and start a game it will crash and give this error message
![Screen Shot 2020-12-17 at 8 25 04 PM](https://user-images.githubusercontent.com/76190080/102562904-0d7d5b00-40a6-11eb-92e5-7d6e266d12d6.png)
This started after I updated my computer but it doesn't effect Brutal Doom or any of the other addons I have so I don't know if that is what is causing it. If someone could tell me a fix or just tell me what is wrong I would really appreciate it because I really love this mod and want to play more of it

**Comment by JMartinez9820** [comment]
I would try using LZDoom, later GZDoom versions are known to do this for some odd reason. What are your PC specs btw?

**Comment by Mrinthehouse** [comment]
I am a mac scrub

**Comment by DonnieWest** [comment]
@Mrinthehouse out of curiosity, what's your `zm_offsetmaxrange`, `zm_offsetspeed` values set to? You can probably find them in your `gzdoom.ini` file

**Comment by DonnieWest** [comment]
@Mrinthehouse if you don't have them (or they're set to 0) try adding the defaults to your `gzdoom.ini`

```
zm_offsetmaxrange=30
zm_offsetspeed=75
```

And see if that fixes your issue

**Comment by Mrinthehouse** [comment]
Do you know where the file would be

**Comment by Mrinthehouse** [comment]
Or would I do that in GZDoom. Im not a huge computer person so I don't know these things

**Comment by DonnieWest** [comment]
@Mrinthehouse I'm not on Mac OS, so I can't be sure.

On Linux it's at `~/.config/gzdoom/gzdoom.ini`, so it's possible it's there for you too. It's possible you can find it by searching with Finder.

My personal favorite way is running `sudo find / -name "gzdoom.ini"` but you probably shouldn't be running superuser commands from randos on the internet :wink:

**Comment by Mrinthehouse** [comment]
Ok I found it. I'll try that after I finish something I'll be right back

**Comment by Mrinthehouse** [comment]
Ok opened the file and found all the code with zm_ but didn't see the ones you specified. If there is an equivalent or maybe I just missed it Idk
zm_adashboost=10
zm_adashfriction=1
zm_airdash=false
zm_autojump=true
zm_crouchslide=false
zm_crouchspeed=0.5
zm_cslideduration=13
zm_cslidestrength=2
zm_cslidetype=0
zm_dash=false
zm_dashboost=1.5
zm_dashheight=0.75
zm_doublejump=0
zm_doublejumpheight=1.2000000476837158
zm_dropprevention=false
zm_ejumpmultiplier=1
zm_elevatorjump=false
zm_friction=8
zm_hook=0
zm_hookboost=1.5
zm_jumpheight=5.5
zm_landing=false
zm_landingsens=6
zm_landingspeed=0.25
zm_ledgegrab=false
zm_maxgroundspeed=12
zm_maxhopspeed=28
zm_minlanding=0.5
zm_movetype=0
zm_multipledashes=0
zm_qslideaccel=6
zm_qslideduration=8
zm_rampjump=false
zm_rjumpmulti=1
zm_setgravity=0.5600000023841858
zm_speedometer=0
zm_strafemodifier=1
zm_walkspeed=0.699999988079071
zm_wjdoublejumprenew=false
zm_wjump=false
zm_wjumpboost=1.5
zm_wjumpheight=0.75
zm_wslide=false
zm_wslidevelz=0.8999999761581421

**Comment by JMartinez9820** [comment]
You can try using the GZDoom console instead. Just type what he has specified.

**Comment by Mrinthehouse** [comment]
Sorry my computer just died and I have no idea where the charger is. @JMartinez9820 I'll try that but if that doesn't work I'll just get LZDoom like you said. Thanks for your help

**Comment by DonnieWest** [comment]
@Mrinthehouse I'd actually be super curious if that ends up working. That'd point in the direction of a fixable bug and could help out future users of this mod

**Comment by Mrinthehouse** [comment]
@DonnieWest @JMartinez9820 The fixed worked perfectly. I've played through the first 3 levels of doom 2 with no issues at all. I found the gzdoom.ini at ~/Library/Preferences/ then scrolled down to the file. Then I just added those lines you said. Thanks again for your help I really appreciate it.

**Comment by DonnieWest** [comment]
@Mrinthehouse thanks!

@JMartinez9820 looks like the issue is here then https://github.com/pa1nki113r/Project_Brutality/blob/5cf733b226eea07d7d85167dd5669c876b2f2082/zscript/PlayerPawn.zc#L3441-L3459

I'm no ZScript dev, but it looks like we're not checking those variables for `null` or 0. Do we consider it a bug on our end if those default CVars aren't set or do we consider that a user error? If it's a bug, I'd be happy to submit a PR fixing it :)

**Comment by JMartinez9820** [comment]
I would say a bug. Go ahead and submit a PR if you like. Just do some testing before doing so, feel free to join the Discord server as well.

**Comment by DonnieWest** [comment]
@JMartinez9820 would just checking for 0 and changing them to the default CVar values be acceptable?

**Comment by JMartinez9820** [comment]
Anyway you think is acceptable and easier. Here is a link to the [PB Discord](https://discord.gg/2hJxXPc) server if you want it.

**Comment by DonnieWest** [comment]
@JMartinez9820 Thanks! I'm on there, I should probably log in more often :joy:

**Comment by JMartinez9820** [comment]
Btw, if you just made a Discord account, the server may kick you out for your account being too young. If this is the case, wait for three days. Also, make sure your Discord account is set up to receive DMs from all users, as a bot will send you a link for verification.
