### ISSUE TITLE
Suggestion : Two small improvements to all weapons in general to allow for better gun combos.

### ISSUE THREAD

**Issue by Dantido2** [pa1nki113r/Project_Brutality#578]
Alright, here are some of the problems I, a hardcore Doom Eternal's gun combo system fan, have found with this system in PB, and the solutions I have to fix them :
-Reloads. Reloading practically locks you from doing anything until it is over, which becomes a problem as reloading on this game is extremely frequent and auto-reloading can practically kill you on harder levels.
My solution is pretty simple : make it so you can cancel reloads by switching to another weapon. This'll fix those awkward moments when you are getting surrounded by pinkies and can't do anything because you decided to reload the minigun before switching to the quad shotgun.

-Certain animations in guns also lock you from switching to another weapon. These are, for example, the animation you get right after shooting with the hell tech rifle or the revving down of the minigun. While I get that the first one is probably done on purpose so gun combos need to be more dynamic and less "shoot, swap, repeat until you run out of ammo", the second one shouldn't lock you from switching to another weapon. That needs to be changed.

**Comment by Cacodemon345** [comment]
Suggestions doesn't belong here though. However, a similar suggestion was pinned in the Project Brutality Discord server.

**Comment by JMartinez9820** [comment]
Speaking of switching weapons while reloading, the pistol currently does that. But like what Cacodemon said, suggestions don't belong here.

**Comment by Dantido2** [comment]
I saw some suggestions in here. Thought this was the right place. Where should I post them?

**Comment by D3X1KAXYZ** [comment]
i know its been a month but incase you havent found the discord, this is where suggestions go. https://discord.gg/2hJxXPc
I shall now close this. Hope to see you there.^^
