### ISSUE TITLE
Suggestion : Lower self damage.

### ISSUE THREAD

**Issue by Dantido2** [pa1nki113r/Project_Brutality#579]
Do I really need to say something here? I'm sorry, I love PB as much as others, and it's absolutely thrilling to rip and tear with an enhanced version of the classic systems, but self damage really needs to be lowered quite a bit. 
It's extremely easy to get killed just because of a rocket hitting your cover. It's practically impossible to use the rocket launcher outside of very open spaces because of how easy it is to fly away to hell and beyond just because of a shot in the wrong direction.  Let me be clear, though, I don't want it to be fully removed. I just want it to be lowered to around 25-40 instead of over 100 HP.

**Comment by Dantido2** [comment]
(Yes, I'm already putting this post where it should be. I wasn't aware this wasn't the place for suggestions. My bad.)

**Comment by goldenmob72** [comment]
: /
This is a Suggestion, not an Issue. 
Make Suggestions in the PB Discord Server please, in #suggestions-for-pb
Closing
