### ISSUE TITLE
Glory kills?

### ISSUE THREAD

**Issue by Mechanical-sanity** [pa1nki113r/Project_Brutality#58]
are you guys going to add BD: black edition glory kills system? I think that is the only thing keeping this mod away from perfection: glory kills. If you guys add the Black edition glory kills, This mod would be the greatest there was and ever will be. If you guys do add glory kills, I would love it!

**Comment by ATeenWhoIsWorkingOnBDCME999** [comment]
If you have a suggestion, leave it on the PB discord. This is a place for reporting issues.

**Comment by Mechanical-sanity** [comment]
I cant say anything. I need permission on the discord

**Comment by JMartinez9820** [comment]
Go to #verification channel, then type ~>iam accepted

**Comment by Mechanical-sanity** [comment]
Thanks guys! Finally, a way to communicate  with the developers
