### ISSUE TITLE
Suggestion : Minigun shield!

### ISSUE THREAD

**Issue by Dantido2** [pa1nki113r/Project_Brutality#580]
It would be amazing to have the minigun shield from Doom Eternal on PB. It would make combat much easier (in a good way) as well as making the experience on the original WADs much better. 
I'm aware PB isn't Doom Eternal, but amongst all the weapon mods from it that aren't in PB, this one is a must-have.

**Comment by SharlLegreg** [comment]
Pretty sure suggestions go to the discord server. Suggestion isn't an "issue" and does not belong in the github issue. Neat idea tho

**Comment by goldenmob72** [comment]
Make Suggestions in the PB Discord Server please, in #suggestions-for-pb
