### ISSUE TITLE
Summon UpgradeSpawner: Not Working

### ISSUE THREAD

**Issue by Matty4818** [pa1nki113r/Project_Brutality#582]
Every time I try to use the Summon UpgradeSpawner command in my console, nothing happens? All the other commands work fine. What could be the problem? I’m using Project Brutality 3.0 with the Current GzDoom and my BFG edition Doom Wads. Please let me know what the problem could be. Thank you!

**Comment by JMartinez9820** [comment]
I think this is due to the recent change to the Backpack, with it now being called PB_Backpack. I'll took a look at this, and see what I can do. I do have a full list of the upgrade names that I will post later.

**Comment by Matty4818** [comment]
Thank you for the quick reply! I’m new to this site and made an account just to ask about this issue, since I couldn’t get any answers on Facebook, lol. Thank you very much for the feedback and let me know as soon as you can about this and the upgrade name list. Much appreciated!

**Comment by Matty4818** [comment]
Just an update on this problem. I played through the campaign on 2 different Doom 2 wads, just to see if I could find the upgrades for the weapons and none of them are anywhere to be found throughout the levels. I tried to change the weapon presets and still nothing. I made sure the option for disabling weapon upgrades was turned off and still no luck. Everything else works just fine but I still can’t get my upgraded weapons either way I try. ☹️

**Comment by D3X1KAXYZ** [comment]
best way to get upgrades is to play on chaotic random. hopefully when we overhaul the spawning system, this can be fixed. i do agree that upgrades are a bit too sparse on anything that isn't chaotic random.

**Comment by Matty4818** [comment]
Upgrade spawner is working again!

**Comment by JMartinez9820** [comment]
@Matty4818 If your issue is resolved, then this can be closed.

**Comment by JMartinez9820** [comment]
This issue can now be closed if it has been resolved on your end. Otherwise, I will close it through my PR, #604.
