### ISSUE TITLE
Ammo Dupe Glitch : Dropping an upgraded weapon ( maybe also normal weapons? ) type and picking it up  gives extra ammo

### ISSUE THREAD

**Issue by SharlLegreg** [pa1nki113r/Project_Brutality#586]
Basically, say we have UAC Compact LMG ( that Black Rifle Carbine upgrade ). Rn the rifle had 60 bullets in the drum, and 540 reserved

. Dropping the gun and picking it up gives you 20 extra ammo.

Video :

https://user-images.githubusercontent.com/63714563/102774886-cc978600-43c6-11eb-9958-5e9492219a36.mp4

**Comment by JMartinez9820** [comment]
Oversight due to the LMG being upgrade rather than just a pick up. This will be fixed when the LMG is overhauled.

**Comment by JMartinez9820** [comment]
Update: The extra ammo maybe impossible to fix due to the nature of Weapon.SisterWeapon, and how upgrades that replace weapons work.

**Comment by JMartinez9820** [comment]
Closing issue as it may be considered impossible to fix.
