### ISSUE TITLE
Shotgun ammo swap bug

### ISSUE THREAD

**Issue by neonvortex** [pa1nki113r/Project_Brutality#587]
When switching ammo types on the shotgun while the alternate ammo swap animation is enabled and the player has the shotgun magazine upgrade, only ten out of the maximum eleven shells will be loaded, causing a single shell to be deleted every time.

**Comment by JMartinez9820** [comment]
Intentional, as the shell ejected out of the shotgun after the animation completes can be picked up anytime. Otherwise ask Cemtex about it.
