### ISSUE TITLE
Swarmer and Electric pods NOT WORKING

### ISSUE THREAD

**Issue by Bones84** [pa1nki113r/Project_Brutality#59]
(master branch) The swarmer and electric pods don't work at all. You can't throw grenades after firing the smg with the lasser sight on

**Comment by the-ebola-wizard** [comment]
Sometimea when i press the use inventory item key on my mouse swapping to the demon rifle activates the swarmer pods

**Comment by JMartinez9820** [comment]
I can confirm that the Swarmers and Electric pods are now officially removed from the backpack spawner, as they were redundant to the inventory. This could mean that the Swarmers and Electric pods are going to be scrapped. This issue can be closed.
