### ISSUE TITLE
GZDoom 4.2.4 compatibility.

### ISSUE THREAD

**Issue by Matty4818** [pa1nki113r/Project_Brutality#590]
Is it possible to make this compatible with the older version(s) of GZDOOM? Specifically GZDOOM 4.2.1. PB 3.0 will only work on the current GZDOOM 4.5. for me and I’ve been having a few problems with the current version, so I just use 4.2.1 for all of my game mods and addons. Let me know if this is possible or not and I apologize if this issue has been brought up already. It would be a dream come true if it could run with the older versions. Let me know when you can! Thank you.

**Comment by popguy12** [comment]
PB works fine on 4.3.3, and its actually recommended to use 4.3.3 instead of 4.5, especially due to the new menu scaling stuff

**Comment by JMartinez9820** [comment]
Your best bet for an earlier version of GZDoom up to 4.3.3 is to get it  [here,](https://zdoom.org/files/gzdoom/bin/) or by downloading LZDoom. You may have downloaded PB when it got the GZDoom 4.5 exclusive Menu scaling, so redownload the master branch of PB if necessary.

**Comment by JMartinez9820** [comment]
@Matty4818 If you have anymore questions, I would suggest joining the [Discord](https://discord.gg/2hJxXPc) server for more information. Make sure you have DMs set up to receive messages from everyone, and that your account isn't new. If that is not the case, then wait approximately three days before joining the Discord server.

**Comment by goldenmob72** [comment]
Closing this, Re-open if neccesary
