### ISSUE TITLE
sperate revolver and Deagle

### ISSUE THREAD

**Issue by jonSP12** [pa1nki113r/Project_Brutality#595]
Making the desert eagle an upgrade of the revolver wasnt very good. They were my favourite weapons to play with... They are already upgraded with the dual weild

**Comment by D3X1KAXYZ** [comment]
That is where add-ons come into play. If you are a part of the PB public discord server, I posted an add-on that splits them into two separate weapons.

**Comment by Harvester1911** [comment]
could you do the same for the doom movie assault rifle? i havent been on discord in ages so i gotta join again

**Comment by D3X1KAXYZ** [comment]
> could you do the same for the doom movie assault rifle? i havent been on discord in ages so i gotta join again
> 

Yes. As a matter of fact I just added the feature to the keep Revolver addon. There is also a separate addon/patch which just separates the carbine and lmg. Its on the discord server.

**Comment by goldenmob72** [comment]
This is a suggestion more of a Issue. Closing
