### ISSUE TITLE
Traditon fists glitch

### ISSUE THREAD

**Issue by ATeenWhoIsWorkingOnBDCME999** [pa1nki113r/Project_Brutality#60]
Punched a shotgun guy on map02 with the traditional class and all my weapons disappeared.

**Comment by scaryred24** [comment]
Thanks for reporting that.

**Comment by Cacodemon345** [comment]
How to reproduce?

**Comment by JMartinez9820** [comment]
@ATeenWhoIsWorkingOnBDCME999 @Cacodemon345 @scaryred24 Traditional mode has been officially scrapped. This issue can be closed.
