### ISSUE TITLE
Movement freezing during kick/punch combos.

### ISSUE THREAD

**Issue by Matty4818** [pa1nki113r/Project_Brutality#605]
Not sure if this has been brought up before or not. I was doing some punching and kicking combos on enemies and then all of the sudden my character will freeze and I cant move forward! All of the enemies will continue attacking me while I am trying to get unstuck and I will die. The game itself is not freezing, its just my character after I do kick/punch combos. It also happens when I'm using Berserk and want to do fatalities, I will do some kick/punch combos and then my character will freeze in place, after about 10 seconds of wiggling the controls around, I can move again. What could this be? Everything is current and up to date & I have all new keyboard, mouse, controller, etc., so I don't think its on my end. Any help/opinions would be great. Thank you!

**Comment by JMartinez9820** [comment]
@Matty4818 This has been a known issue since melee attacks were overhauled. Unfortunately, I haven't found anyway of what causes this or any way to fix it. So the only way for now is to do random combos to break out of movement, or wait for an official fix to arrive.

**Comment by Matty4818** [comment]
Alright, thank you for the info! I don’t play it as much as BDV21 so it’s not a big deal for me, I just thought you guys should know so it can be fixed. Thank you!

**Comment by Mechanical-sanity** [comment]
> @Matty4818 This has been a known issue since melee attacks were overhauled. Unfortunately, I haven't found anyway of what causes this or any way to fix it. So the only way for now is to do random combos to break out of movement, or wait for an official fix to arrive.

Actually, this can be replicated by constantly punching and kicking at the ground. After a few combos, it should happen

**Comment by JMartinez9820** [comment]
This issue can be reopened: as this still persists currently.
