### ISSUE TITLE
Suggestion issue: link to discord in README.MD

### ISSUE THREAD

**Issue by D3X1KAXYZ** [pa1nki113r/Project_Brutality#617]
If you don't want people making suggestions here under issues, shouldn't this be stated in the Readme file?
If you want people to post suggestions on discord, shouldn't there be a link to said discord server?
Also on a minor note, why does the suggestion tag exist when suggestions shouldn't be posted here?
Just curious.

**Comment by JMartinez9820** [comment]
Aren't you a collaborator? You should be able to modify or remove tags. Also, I think Galdoc's setup video should also be in the Readme. I can easily add the discord server along with Galdoc's video on it once I'm done with class

**Comment by goldenmob72** [comment]
This is like 3rd or 5th GitHub issue i've had to close today, Post Suggestions in the PB Discord Server
Seriously, It is not hard, it's very easy and simple.

Closing

**Comment by D3X1KAXYZ** [comment]
Yes I am i am just curious about its existence. If it has no purpose, then yeah I should be able to remove it. However I am currently not on my computer so...
_just now realized that the app isn't the only way to access github. derp lmao_
