### ISSUE TITLE
I can't use the leech

### ISSUE THREAD

**Issue by Eldust65** [pa1nki113r/Project_Brutality#618]
I cannot equip the leech grenade because I get the error of: leech not available in the upper corner of the screen

**Comment by JMartinez9820** [comment]
The Leech is only available when you collect it from Demon Tech Troopers when the spawn it in a rare occasion upon death. Summon leechgrenade is the console command if you want to summon it. This issue is invalid.

**Comment by Eldust65** [comment]
But when I take it from the enemy nothing happens, even when I open the equipment wheel, maybe it's a bug?
