### ISSUE TITLE
Revolver weapon switch issue

### ISSUE THREAD

**Issue by sanscriptum** [pa1nki113r/Project_Brutality#63]
As far as I know, this has been an issue since January test version. Basically have a "Revolver replaces pistol" option on, then try to switch to the revolver, and when attempting to switch to any other weapon, revolver becomes kinda "sticky" and won't allow it unless you start mashing weapon switch keys. It works fine otherwise without the option.

**Comment by sanscriptum** [comment]
Also just to throw it out there, for some reason RELOADER is not functioning properly so I can't reload weapons on demand. Some weapons do reload though (mp40, super plasma rifle after a shot). Updated to the latest gzdoom 3.6.0, used default settings, nothing. January test version works just fine.

**Comment by ATeenWhoIsWorkingOnBDCME999** [comment]
Reloading is now binder to the source ports reload function.

**Comment by sanscriptum** [comment]
Ah, I see. Not really straightforward though, because RELOADER works fine in brutal mode, but not in PB mode. Binding R to "+reload -reload" solves it.

**Comment by sanscriptum** [comment]
New issue I've found - Jetpack effect is not disabled after Revenant transformation expires. Also when a black pinky kills you and eats you, it turns into a regular pinky during the animation.

**Comment by sanscriptum** [comment]
Issues with UNRELOADER - Nailgun and M2 Plasmarifle unload correctly, but then lock up the weapon system so you can't shoot or reload or do anything really, other than walk and throw grenades. M2 can be fixed by swapping grenade type, but nailgun stays stuck forever.  
Regular plasma rifle also acts weird as you seemingly drop it on the ground and then you can't do anything at all, even throw grenades or kick.
Cryogun is a bit weird when you try to unload with pistol active.

**Comment by JMartinez9820** [comment]
This issue can be closed as the Reloader calls have been officially scrapped, and now inherits GZDoom's default reload keys.
