### ISSUE TITLE
Feature to switch to last weapon used like doom 2016

### ISSUE THREAD

**Issue by maxlaughter** [pa1nki113r/Project_Brutality#630]
This feature would Help a Lot for people who are tired of pressing number buttons for switching weapons

**Comment by D3X1KAXYZ** [comment]
Hi there ^^
We do appreciate your feedback, however we are not taking suggestions via issues. We have a channel in the public discord server for suggestions. https://discord.gg/2hJxXPc
I shall now close this. Hope to see you there.^^

**Comment by popguy12** [comment]
i do want to add though, i made sure that Gearbox by m8f (https://github.com/mmaulwurff/gearbox/) works perfectly with PB, unless a recent update to it broken it in some way, it doesnt have a "last weapon" thing, but it has a bindable weapon wheel and a HL1 styled box selection system
