### ISSUE TITLE
Carbine: Incorrectly-tinted sprites.

### ISSUE THREAD

**Issue by Shockwave508** [pa1nki113r/Project_Brutality#631]
Oversight, regarding the Carbine: Quite a few sprites show this weapon in a far-brighter tint than what is usually present.

Affected Sprites...
-All Draw sprites.
-DualCarbine/Switch: CB00A0-CB00D0
-All Kicking sprites.
-Reload: 4A20A0-4A20G0, 4A22G0-4A22N0
-Reload/Left: 4B20G0, 4B22G0, 4B22H0
-Respect: 4A11A0-4A11G0, 481AS0-481AX0
-All Special sprites.

**Comment by popguy12** [comment]
yea, this isnt something that can be simply summed up to shading, the sprites are visibly black in one set and green in another

**Comment by JMartinez9820** [comment]
Fixed in Carbine re-overhaul
