### ISSUE TITLE
Discord server issue

### ISSUE THREAD

**Issue by BooPoP89** [pa1nki113r/Project_Brutality#635]
The bot won't send a verification link and I can not dm the mods cause it wont let me, my discord in the server is BooPoP#4093

**Comment by JMartinez9820** [comment]
@BooPoP89 This is not an issue. Do you have you DMs set up to receive messages from everyone? Make sure to have your DMs set up to receive messages from everyone in the server. If you just created a new Discord account, you won't be able to join the server until your account is 3 days old. The PB server has a bot that automatically kicks users if their account is younger than 3 days old, mostly to prevent spam accounts, raid accounts and alt accounts of banned users from joining the server.
