### ISSUE TITLE
Bugs when dual wielding and reloading

### ISSUE THREAD

**Issue by nemesis-vampy** [pa1nki113r/Project_Brutality#639]
Several weapons behave incorrectly when both dual wielding and reloading:

- The auto shotgun begins the reload animation even if both guns are full.
- The revolver and pistol reload both guns even if only one is fired.
- The SMG and DMR reload both guns if just the left weapon is fired. Just firing the right weapon works correctly.

**Comment by JMartinez9820** [comment]
All of these little oversights are known and will be fixed later.

**Comment by JMartinez9820** [comment]
Update 5/20/21:
DMR and SMG reload on dual wield fixed.

**Comment by JMartinez9820** [comment]
@nemesis-vampy All of these might be fixed in the latest staging commit now, so this can be closed

**Comment by popguy12** [comment]
Revolver will probably be kept, but i can see about fixing, gonna close it for now
