### ISSUE TITLE
Questzdoom snap turn issue

### ISSUE THREAD

**Issue by HUNGfLO** [pa1nki113r/Project_Brutality#640]
Hi there, im new here so hopefully im doing this right, but im trying to use your mod on the oculus quest 2 and when I load into game and try to snap turn the camera rotates and becomes disoriented from the players normals wasd movement.  Hope to hear back as id love to try out the mod.  Thanks.

**Comment by HUNGfLO** [comment]
Sry, maybe wasd isnt the correct way to explain, but the left stick controls forward, back and strafes and the right stick left and right is turn/snap turn.

**Comment by JMartinez9820** [comment]
QuestZDoom is not officially supported by th PB Team, and future support is not a guarantee. It might b ZMovement, as ZMovement is designed for Keyboard. Controller support isn't a guarantee of either.
