### ISSUE TITLE
about multiplayer PB 3.0

### ISSUE THREAD

**Issue by Nghiep4eye** [pa1nki113r/Project_Brutality#641]
I found out about multiplayer coop PB 3.0 master currently work very well with GZDOOM + ZDL. But it out of sync when you or your friends press special weapons wheel and equipment wheel buttons, me and my friends play test for couple hours it work perfectly with ultimate doom visor and glory kills if you dont press that 2 buttons, please fix it and multiplayer coop will be perfect. 

ect: in network options,i turn off all options and extratics is none and play coop dont have out of sync.

**Comment by JMartinez9820** [comment]
Multiplayer is not guaranteed for the future as GZDoom has terrible netcode.

**Comment by Nghiep4eye** [comment]
True that GZDOOM has terrible netcode, but it nice when play via LAN, ect Hamachi, i want to give it a try this mod fun as hell when coop, the gore the graphic please consider it, me and my pals play coop with out any problems but missing those weapons wheel and equipment make the game not complete, i dont know much about coding but i love and appreciate the effort you put to the mods, best mods ever.

**Comment by popguy12** [comment]
theres really not much that can be done currently, your best bet would be the old 2018 stable build, that works with multiplayer

**Comment by rautamiekka** [comment]
What about Zandronum ?

**Comment by JMartinez9820** [comment]
Zandronum is way too outdated and will not be a possiblity. To be honest, this issue should be closed with the invalid/will not fix tags added.

**Comment by rautamiekka** [comment]
No point in me hanging around here then. A massive shame, PB is better than BD.
