### ISSUE TITLE
Super Shotgun’s firing sound cuts off early.

### ISSUE THREAD

**Issue by Matty4818** [pa1nki113r/Project_Brutality#643]
The Super Shotgun’s firing sound cuts off too early. Some times when you shoot it will work just fine and fade out properly and after a couple times it will cut off way too early right after you fire it. This only happens with the SSG, not the upgraded Quad Shotgun. Not sure if this has been brought up before, so if it has then my apologies. Just giving you a heads up so it can be eventually fixed. Thank you!

**Comment by JMartinez9820** [comment]
@Matty4818 To be fixed on my branch. The beginning of the reload state had an A_WeaponReady state, which may have caused that. Although I might just remove that A_WeaponReady entirely.

**Comment by JMartinez9820** [comment]
I just simply fixed by adding the WRF_NOFIRE flag. Check my pull request, #636, or check my branch, JMartinezBranch.
