### ISSUE TITLE
The screen becomes dark after being shot

### ISSUE THREAD

**Issue by wonghang** [pa1nki113r/Project_Brutality#646]
I am new to Project Brutality and I am recently playing it on Doom 2.
Sometimes, if I was shot, the screen would become darker and darker and finally I cannot see anything.
If I start a new game or use "changemap", the brightness will become normal again.

Is that a feature (the player's eye was damaged?) or bug?

![dark situation](https://user-images.githubusercontent.com/11483902/114304000-d971ee00-9b0b-11eb-943a-d84da900ec39.png)
![normal situation](https://user-images.githubusercontent.com/11483902/114304009-df67cf00-9b0b-11eb-832f-d4b69eb5e9dd.png)

I am running on 

GZDoom g4.5.0 - 2020-10-31 10:07:33 +0100 - SDL version
The Project Brutality is downloaded from GitHub master branch.

I am using "OpenGL renderer (hardware accelerated)" and Sector light mode is "Bright"

**Comment by SharlLegreg** [comment]
This is akward. I faced this before, except i was resurrecting myself while the black fade animation is playing. It would return to normal after 1-2 minutes. Didnt know this can happen without dying

**Comment by JMartinez9820** [comment]
The fading to black thing is intended when you die, but it seems that it's affecting some people too without dying. Thank you very much for the report. I'll possibly look at this when I can. I'm planning on make a patch to disable the fade to black script upon death, but it will not be implemented on my branch.

**Comment by wonghang** [comment]
Oh I might understand what happened then. I was once died and I ran the command `resurrect' to resurrect myself. I think I was still in "dying mode". If I get shot in "dying mode", my screen becomes darker and darker...

**Comment by Cacodemon345** [comment]
Does it affect Multiplayer?

**Comment by JMartinez9820** [comment]
Closing due to lack of responses for almost over a year.
