### ISSUE TITLE
Index out of Bounds

### ISSUE THREAD

**Issue by RealRexen** [pa1nki113r/Project_Brutality#647]
Was in the middle of using the nailgun and switching modes when I got a vm abort, it doesn't allows happen and seems to be random but tends to happen with the weapon
![Screenshot_Doom_20210413_143758](https://user-images.githubusercontent.com/18408903/114625077-924c4000-9c66-11eb-9087-56acb8d0a3d0.png)

**Comment by JMartinez9820** [comment]
Known issue regarding the ev core ZScript code. However, there hasn't been a fix for this yet. I would see if this issue persists on LZDoom

**Comment by popguy12** [comment]
this issue is known, and still present, still gotta look into it
