### ISSUE TITLE
Divide By Zero in Script 24008

### ISSUE THREAD

**Issue by DisneyStarWarsisNonCanonHeresy** [pa1nki113r/Project_Brutality#65]
Using UDV v2.12b. Everything meshes well, but when pulling out the pump shotgun, the ammo count and weapon list in the hud vanishes.

**Comment by ATeenWhoIsWorkingOnBDCME999** [comment]
Currently udv is not up to date with pb 3.0

**Comment by scaryred24** [comment]
Ultimate Doom Visor's development has halted as something seems to always break when a new test variant comes out. Rather than going to fix it for every release, saegiru has decided to only update it when 3.0 stable comes around. This isn't a problem on our end but rather his. Thread closed.
