### ISSUE TITLE
i can't even run it

### ISSUE THREAD

**Issue by helpmepleaseplspls** [pa1nki113r/Project_Brutality#653]
The whole thing doesn't work, when i drag it to the gzoom.exe it just runs normally, and unpacking doesn't work, because the file is 'damaged' downloaded three times already and doesn't work. please help

**Comment by Xeno1979** [comment]
don’t unpack! just drag the zip file into gzdoom

**Comment by helpmepleaseplspls** [comment]
> don’t unpack! just drag the zip file into gzdoom

if I do that it will launch gzdoom normally without the mod

**Comment by JMartinez9820** [comment]
@helpmepleaseplspls Just use a mod loader like ZDL, ZDE, SSGL, or Doom Runner. The [Discord](https://discord.gg/2hJxXPc) server should be able to help you out if you're having trouble. If your issue is solved there, you can close this issue. Otherwise, feel free to DM me

**Comment by JMartinez9820** [comment]
Due to the lack of response within the last 3 months, this issue will be closed soon.
