### ISSUE TITLE
Suggestion:  rename "Hungry Pinky Demons" to "Satiated Pinky Demons"

### ISSUE THREAD

**Issue by SabinStargem** [pa1nki113r/Project_Brutality#659]
When configuring the abilities of monsters, the option "Hungry Pinky Demons", stands out.  This is because the toggles are No/Yes.  The other options have to be set to "No" to permit abilities, but the name for the Pinky specialty implies that it needs a "Yes" to enable the ability.

I think renaming the option to "Satiated Pinky Demons" would be less confusing.

**Comment by JMartinez9820** [comment]
@SabinStargem If you're going to possibly rename this, I would highly recommend making a pull request instead of an issue if you know how to use Github,

**Comment by SabinStargem** [comment]
> 
> 
> @SabinStargem If you're going to possibly rename this, I would highly recommend making a pull request instead of an issue if you know how to use Github.

Don't really know how to use Github, let alone to code.  Guess I should have titled the issue "Suggestion", instead of Clarification?

**Comment by JMartinez9820** [comment]
Suggestions don't belong on Github Issues, I would suggest bringing it to the [Discord](https://discord.gg/2hJxXPc) server instead

**Comment by goldenmob72** [comment]
> Suggestions don't belong on Github Issues, I would suggest bringing it to the [Discord](https://discord.gg/2hJxXPc) server instead

Quite right, Closing Issue.
