### ISSUE TITLE
Dragons breath upgrade for pump shotgun

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#660]
As I recall dragons breath shells used to cause damage to you when shooting an enemy too close. But with recent updates this no longer happens. Walking through fire caused by the shotgun or shooting at walls too close also causes no damage to the player. In my opinion the weapon is overpowered but this makes it more of a cheat.

**Comment by rautamiekka** [comment]
Agree, having no Player damage gets cheaty.

**Comment by JMartinez9820** [comment]
@rautamiekka and @TonyH1234 I plan to nerf the Dragon's Breath shells when I can. I wanted to decrease the pellet count to five, but when I talked with Secret the 10 pellet count was intentional. I'm going to see what I can do to bring back the self-damage to the player.

**Comment by JMartinez9820** [comment]
@TonyH1234 and @rautamiekka I was able to restore the self-damage from the dragon's breath particles and I tried to nerf the Dragon's Breath mode. If y'all want to test it here is my branch to test it on: https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch

**Comment by TonyH1234** [comment]
Tested it. Self damage is back, but still seems too powerful.

**Comment by JMartinez9820** [comment]
It's a bit intentional to be powerful due to how the damage works. I can nerf it if necessary, although due to the limitations of A_Explode it will be a bit more difficult

**Comment by JMartinez9820** [comment]
@TonyH1234 Update to my branch: Projectile count decreased from 8 to 6. I won't decrease it anymore due to limitations of damage values and a developer's wish to keep it more spread based like Buckshot.

**Comment by TonyH1234** [comment]
Perhaps you could make it spawn more rarely? Seems to spawn as much as the regular shotgun.  Perhaps also increase the player self damage especially near enemies and walls, similar to Dox's addon for Brutal Doom. One careless shot near a wall or a monster and it's instant death. As it is now once you get this weapon, it makes all the other weapons pointless.

**Comment by WolVexus** [comment]
What spawn preset are you using? I think one of the higher tier presets
might be causing the abundance.

**Comment by TonyH1234** [comment]
Using tier 4. Was using tier 1 for a while. I wanted more variety of enemies.

**Comment by WolVexus** [comment]
If you're comfortable with it, give Deathwish or Chaotic Random a try.

Deathwish I believe is everything high tier but I could be wrong and
Chaotic Random is, well, everything is random. You could hit the jackpot on
Map01 or be completely screwed over.

**Comment by TonyH1234** [comment]
I have a suggestion. Once you get the magazine upgrade you will never want to use buckshot or slugs again. Why not have dragons breath shells as a separate ammo type and make them extremely rare?

**Comment by WolVexus** [comment]
To be 100% honest with you, even with the upgrade I seldomly ever use the
shells. I prefer slugs to take care of individual fodder while saving the
shells for midtier+ monsters. Buckshot, it never really grew on me so I
always immediately switch to slugs. That's just how I play though, but I'll
definitely bring it up!

**Comment by TonyH1234** [comment]
I was using the glorykill addon. It was overriding the changes you made to shotgun.dec. That's why I didn't notice any difference in the dragons breath damage.

**Comment by JMartinez9820** [comment]
@TonyH1234 Please don't use Glory Kill or any add-ons on other branches, as they were designed for master. Issues regarding add-ons will not be logged and should be taken to the Discord server instead. Did you try my changes without Glory Kill
