### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by kinkock** [pa1nki113r/Project_Brutality#662]
I would like an option to completely disable weapon bobbing in the mod because it does not fit in with the ADS feature on several weapons.

I would also like alternate animations and weapon hud textures for replacing the ADS iron sights and scope pictures with source port crosshair's, plus I would like options to disable specific phrases as I find some like "get the marine" to be cringey.

**Comment by Cacodemon345** [comment]
Feature requests don't belong here, only in the Discord server.
