### ISSUE TITLE
3d Models don't rotate

### ISSUE THREAD

**Issue by kinkock** [pa1nki113r/Project_Brutality#663]
The 3d voxel based models you put into the game all face the same direction, which looks weird.

They should either have random angles set or have a floating rotation animation applied to them.

**Comment by JMartinez9820** [comment]
@kinkock I recommend you contact Popguy or D3X1K AXYZ if want this to be fixed. The voxels are still a work in progress, so their angles are just placeholders.

**Comment by popguy12** [comment]
the models are setup to face the direction the actor is pointed in, the angle
so maybe _spawned_ voxels could have a random angle applied, but dropped weapons from enemies or the player dropping them wouldnt make too much sense

**Comment by popguy12** [comment]
building onto this, something seems to be up with the weapons that get tossed by enemies on some deaths
mainly the DTech rifle i think is the only one that supports this currently, but the voxel doesnt seem to be rotating alongside the sprite

**Comment by D3X1KAXYZ** [comment]
> building onto this, something seems to be up with the weapons that get tossed by enemies on some deaths mainly the DTech rifle i think is the only one that supports this currently, but the voxel doesnt seem to be rotating alongside the sprite

It seems I forgot to set the `USEACTORROLL` flag for the TossedHellRifle model definition. A simple enough fix though.

**Comment by D3X1KAXYZ** [comment]
Your wish has been granted, its a simple add-on that i just threw together. This one is built for [commit 2a5efa6 (merge date: 1-17-22)](https://github.com/pa1nki113r/Project_Brutality/commit/2a5efa637f2954758ad15eaed4982be84f093bd7) which depending on when(and/or if) you see this, may or may not be the current build.
[PBVP_Quake 3 Style(PB 1-17-22).zip](https://github.com/pa1nki113r/Project_Brutality/files/7886712/PBVP_Quake.3.Style.PB.1-17-22.zip)
Any updates to the addon may be found over on discord (both the pb public server and V5-addons server) as well as the pb website.
Depending on how the addon does, I may expand upon it. with this i shall close this issue.
