### ISSUE TITLE
Missing HUD features

### ISSUE THREAD

**Issue by Shockwave508** [pa1nki113r/Project_Brutality#669]
1) The armor icon doesn't differentiate between different armor types (helmet/green/red/blue).
2) Visible middling/low-health warnings/colored bars need to be implemented.
3a) Dual-Wield ammo bars need to be added, as does appropriate firemode icons for applicable weapons.
3b) Certain weapons like the Cryogenic Repeater and Meatshield(s) need ammo bars for the Pistol/DMR.
3c) Revenant Missile Launchers lack an ammo bar/munition count.
4) Powerup timers need to be added, where needed.
5) Time/Kills/Items/Secrets readout.
6) Frag Grenades have visible munitions count, yet Stun Grenades and Proximity Mines do not.
7) For certain mapsets with underwater/airless environments, an Air Supply bar needs to be added.

**Comment by JMartinez9820** [comment]
Most of these have been added now, so this can be closed.
