### ISSUE TITLE
Delta Touch cant launch PB instead vanilla doom

### ISSUE THREAD

**Issue by Euxieryli** [pa1nki113r/Project_Brutality#675]
How could this happen, my delta touch cant even launch PB but instead launch vanilla doom, also i replaced zip to pk3 many times even redownloaded it but still doesnt work, worked before but now doesnt when download new update

**Comment by JMartinez9820** [comment]
@Euxieryli Make sure the mod is load after a map set if you're loading a mapset. Otherwise, show pictures of your load order. If you need further, then you can join the [Discord](https://discord.gg/2hJxXPc) server

**Comment by Euxieryli** [comment]
Nothing much, just putting my PB only in it

![Screenshot_2021-07-20-12-29-07-459_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/75726950/126266928-782c9393-c6f3-4328-8907-f9d22770e950.jpg)

And then

![Screenshot_2021-07-20-12-28-50-171_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/75726950/126266979-55ee19c4-47a3-44e2-be49-d98d77468bec.jpg)

**Comment by JMartinez9820** [comment]
See if my [Mediafire](https://www.mediafire.com/file/94oky56it5gvlup/Project_Brutality-master.zip/file) link helps.

**Comment by Cacodemon345** [comment]
Did you look at the logs? Delta Touch won't load mods if they are corrupted files.

**Comment by Euxieryli** [comment]
> See if my [Mediafire](https://www.mediafire.com/file/94oky56it5gvlup/Project_Brutality-master.zip/file) link helps. Redownload PB with the MediaFire link above (click the blue MediaFire button)

Oh it worked now, asome

**Comment by Euxieryli** [comment]
Not sure why it doesnt work on github but work on mediafire
