### ISSUE TITLE
I just downloaded the new version and this error is happening in delta touch, how to solve it?

### ISSUE THREAD

**Issue by LawlietBRVL** [pa1nki113r/Project_Brutality#676]
![Screenshot_2021-07-20-10-08-22-156_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/37804276/126330848-5575f7e6-189f-477c-bab8-e67cdaf89c52.jpg)
#

**Comment by JMartinez9820** [comment]
Known error but currently no fix at the moment.

**Comment by JMartinez9820** [comment]
Try disabling weapon bob if you can find it. I believe it's in the PB settings

**Comment by tunbridgep** [comment]
I'm going to try and tackle that division by zero bug tonight, although I won't be able to test it.

I'll have a PR up within 12 hours

**Comment by LawlietBRVL** [comment]
![Screenshot_2021-07-20-21-17-44-585_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/37804276/126411089-a67cd0ca-74f0-406b-88d2-97ffb424677b.jpg)
Guys I loaded the mod on lzdoom and there was no error, but actually on gzdoom this error is occurring.  At the moment thanks for the help!

**Comment by JMartinez9820** [comment]
@LawlietBRVL Late response, but if your issue is considered resolved, it can be closed. Otherwise, keep it open if you need further help.
