### ISSUE TITLE
Player would still receive "Brutality Bonus" even tho the inflictor does not originate from the player. ( Intentional? )

### ISSUE THREAD

**Issue by SharlLegreg** [pa1nki113r/Project_Brutality#679]
I have no way to replicate this "bug" consistently due to the billion variables and timings, but I can confirm that if you wound an enemy to that "Brutality Bonus" window and another monster came and kill that wounded enemy, the player would receive the "Brutality Bonus". The best way to replicate this is to have a shotgunner ( best the quad shotgun guy ) is directly behind the wounded enemy and you're in front of the wounded enemy.

Very very minor issue and probably low priority.

**Comment by JMartinez9820** [comment]
@SharlLegreg Very minority priority. Brutal Doom did this too. In the future we plan to replace the crappy old Cruelty Bonus system with a much better made system later on

**Comment by JMartinez9820** [comment]
Closing due to no response.
