### ISSUE TITLE
Problems when starting

### ISSUE THREAD

**Issue by xPrimo** [pa1nki113r/Project_Brutality#680]
I'm new to this, but I'm almost sure that I followed all the steps to start the "Project Brutality" but for some reason after about 5 minutes of play the image hangs and I only hear what happens, the only way to solve it is by restarting my PC, I don't know if it's my problem or is there a way to optimize it

**Comment by JMartinez9820** [comment]
@xPrimo Which GZDoom version are you using and what are your PC specs? I would also try LZDoom or GZDoom GLES if you're having issues. If you have Precache GL Textures, turn them off. It is located in Options/Display Options/Texture Options
LZDoom: https://zdoom.org/downloads
GZDoom GLES: https://github.com/drdteam/gzdoom-gles/releases/tag/gles4.6.0b

**Comment by popguy12** [comment]
im pretty sure that this issue is driver based, most common on lower end PCs or laptops
definitely try either LZDooM or the GLES option in GZ

**Comment by JMartinez9820** [comment]
Closing issue due to the lack of a response.
