### ISSUE TITLE
Persistent Dash GFX Even When You Are Dead.

### ISSUE THREAD

**Issue by SharlLegreg** [pa1nki113r/Project_Brutality#682]
Minor Bug. Observed on EDAY01 on the secret area with the instant death fan. Dashing into the fan will cause you to die, as expected, but the dashing "woosh" GFX at the edges of the screen still remains.

**Comment by JMartinez9820** [comment]
@SharlLegreg The dash graphic only disappears when the player is on the ground. This is a very minor bug and isn't game-breaking, so this won't be taken care of until later. One way of "fixing" this is to disable the dash graphic effect.
