### ISSUE TITLE
There's a black stripe on my sreen

### ISSUE THREAD

**Issue by Joao054** [pa1nki113r/Project_Brutality#689]
![20210806_201234_mfnr](https://user-images.githubusercontent.com/88591666/128607673-b6f98d5b-843b-4251-b9dc-71e31e4a1551.jpg)

**Comment by JMartinez9820** [comment]
@Joao054 
That black stripe is proposed to be a possible dash meter. In the future, we plan to implement a dash cooldown system and the dash meter will be used for that purpose. Just ignore this for now or use another HUD like HXRTC HUD. It's on the Discord server if you need it. If you're not on the Discord server, I can post HXRTC HUD here.

**Comment by Joao054** [comment]
yeah, i'm not on the discord server

**Comment by Joao054** [comment]
but when you guys add this new feature with the dash cooldown, am i going to still face this problem?

cuz then, instead of being just an annoyance, will be a real problem, cuz then i won't be able to see the dash meter

**Comment by JMartinez9820** [comment]
@Joao054 
It turns out that it was just an error on the health/armor bar part. I have now fixed this on my build for now until it gets reused again. Here is a link to my build if you want to use it. 
https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch

**Comment by Joao054** [comment]
for some odd reason, it didn't work, when i open it with gzdoom, and when i click play, it opens the vanilla doom, like if i didn't dragged any mod

**Comment by Joao054** [comment]
i also tried to drag both of them

**Comment by JMartinez9820** [comment]
I recommend using a mod launcher like ZDL. Drag and drop tends to not work well. If that doesn't work, then I'll put up a Mediafire link of my branch here.
Here is the discord server if you need it: https://discord.gg/2hJxXPc

**Comment by Joao054** [comment]
i tried with doom mod manager, but it's the same thing, but when i open the default pb, it works

**Comment by JMartinez9820** [comment]
Try downloading my branch off of this: https://www.mediafire.com/file/27oej5ttmycb9yb/Project_Brutality-JMartinezBranch.zip/file

**Comment by Joao054** [comment]
it worked, the black stripe is not there anymore, thanks

**Comment by Joao054** [comment]
also another thing that i want to point out is that, when i downloaded the default pb, it also didn't work, but when i downloaded the default pb via mediafire, it worked
