### ISSUE TITLE
GZDoom reports "Unknown texture"

### ISSUE THREAD

**Issue by Javic36** [pa1nki113r/Project_Brutality#690]
Downloaded the archive last night. Downloaded and installed GZDoom 4.6.1. Using ZDL to launch. When I run PB as instructed, Project Brutality doesn't run; I just get vanilla Doom. So following the lead of the PB 2.0 PK3, I unzipped and repacked the archive to get rid of the "Project_Brutality-master" folder at the top level. I named the repacked archive "Project Brutality 3.0.pk3". Now, judging by the start-up time, GZDoom is at least loading the archive. But GZDoom soon fails with this message:

Script error, "Project Brutality 3.0.pk3:animdefs" line 153:
Unknown texture FHDS01

I'm running on 64-bit Win 7. No other mods. I'd ask for help on the Discord, but all I get when I go there is an empty screen with the message "Messages Failed to Load". (FWIW I use *many* other Discord servers and they all work fine.)

Here's the entire GZDoom log:

OS: Windows 7 (NT 6.1) Build 7601
    S
M_LoadDefaults: Load system defaults.
Using program directory for storage
W_Init: Init WADfiles.
 adding D:/WinXPGames/Doom et al/GZDoom - 4.6.1 x64/gzdoom.pk3, 634 lumps
 adding D:/WinXPGames/Doom et al/GZDoom - 4.6.1 x64/game_support.pk3, 2514 lumps
 adding D:/WinXPGames/Doom et al/Game WADs/DOOM2.WAD, 2956 lumps
 adding D:/WinXPGames/Doom et al/GZDoom - 4.6.1 x64/game_widescreen_gfx.pk3, 121 lumps
 adding D:/WinXPGames/Doom et al/Project Brutality/Project Brutality 3.0.pk3, 30554 lumps
I_Init: Setting up machine state.
CPU speed: 2665 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i5 CPU 750 @ 2.67GHz
  Family 6, Model 30, Stepping 5
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 HyperThreading
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device OpenAL Soft on Speakers (Creative SB Audigy 2 ZS (WDM))
  EFX enabled
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ANIMDEFS: Can't find DASHSCREEN

Execution could not continue.

Script error, "Project Brutality 3.0.pk3:animdefs" line 153:
Unknown texture FHDS01

**Comment by JMartinez9820** [comment]
@Javic36 If you actually repackaged the 2.03 file with 3.0's files, that's probably why. Please do not try something like this. If you need further help, try asking in the [Discord](https://discord.gg/2hJxXPc} Try downloading from this Mediafire link I've made.
https://www.mediafire.com/file/94oky56it5gvlup/Project_Brutality-master.zip/file

**Comment by JMartinez9820** [comment]
@Javic36 If you actually repackaged the 2.03 file with 3.0's files, that's probably why. Please do not try something like this. If you need further help, try asking in the [Discord](https://discord.gg/2hJxXPc) server. Try downloading from this Mediafire link I've made.
https://www.mediafire.com/file/94oky56it5gvlup/Project_Brutality-master.zip/file

**Comment by JMartinez9820** [comment]
For some reason, Github doesn't work on some user's ends. It may be your internet connection or ISP that is messing up. However, please notify me on here or on Discord if PB updates, as the Mediafire link will be rendered obsolete. This issue is scheduled to be closed by my pull request when it gets merged

**Comment by Javic36** [comment]
For reasons unknown, I'm not able to use the Discord server. I point my browser to the URL, click on Accept Invite, it takes me to the page, and all I see is a big (mostly) empty space with the words "Messages Failed to Load". All my other Discord servers work as expected. Sorry, I know this is off-topic, but without Discord access, where do you go for help with a particular Discord?

**Comment by JMartinez9820** [comment]
If you just created a Discord account, your account is probably too young. Also, make sure that you have your DMs set to receive messages from everyone, because a bot will send you a DM. If you're probably on like the Brutal Doom Discord server I can probably help you through DM there.

**Comment by Javic36** [comment]
I've had a Discord account for a few years now, and the DM setting allows messages. I have no problem accessing other Discord servers. What's also weird is that at the PB server, #main-pb-chat doesn't appear in the list at left. The only item there is "IMPORTANT STUFF" which contains #rules, #faq, and #pb-builds-download, all of which I can access. FWIW I tried it from both Chrome and Firefox; the behavior's the same with both.

Is there some place on Discord where I can go to get help with Discord itself?

**Comment by JMartinez9820** [comment]
Did you get a message from the bot? Because you should get a message from the bot. If not, message me on Discord DMs (JMartinez2098#6276), or message one of the PB Discord moderators. I'll probably be on the Brutal Doom Discord server to help you out.

**Comment by Javic36** [comment]
No, I didn't get any DM. Sent you a friend request on Discord so we can chat. Thanks. And BTW where is the Brutal Doom Discord? Invites I found with Google yield "Invalid Invite".

**Comment by JMartinez9820** [comment]
I'm on discord now, and I accepted your friend request. If you need further help, you can ask some of the mods like popguy

**Comment by Mxhamza** [comment]
Hi. Why don't you try dragging and dropping the project _brutality_master
zip file directly to gzdoom. That's how I play it,and it runs perfectly
fine. No problems
