### ISSUE TITLE
Super shotgun custom crosshair is just a blurry dot

### ISSUE THREAD

**Issue by lumbo7332** [pa1nki113r/Project_Brutality#694]
Is this intentional? I'm using the latest version from the master branch.
![20210919_18h00m31s_grim](https://user-images.githubusercontent.com/20866468/133948963-0c6749df-d1ae-4c72-9796-dbe5e63b740a.png)

**Comment by JMartinez9820** [comment]
@lumbo7332 Are you using a custom crosshair mod by any chance? Certain custom crosshair mods may conflict with PB's current crosshairs, and make sure to also turn of the default crosshair option in order for the weapon specified crosshairs to work properly.

**Comment by JMartinez9820** [comment]
If you can, you can post your load order so I can if you're using any add-ons

**Comment by lumbo7332** [comment]
> Are you using a custom crosshair mod by any chance?

No but, I am using Ultimate Doom Visor. Although my crosshair is set to `None`.

> make sure to also turn of the default crosshair option in the HUD settings

If I turn the crosshair option to `Off`, the custom crosshairs don't show up either.

> If you can, you can post your load order so I can if you're using any add-ons

Sure.
```
Project_Brutality-master.pk3
UDV_v2.13_A_BASE.pk3
UDV_v2.13_D_MISC_FONT_A_RestoreOriginal.pk3
UDV_v2.13_D_MISC_FONT_B_DisableMenuFont.pk3
```

**Comment by JMartinez9820** [comment]
UDV is extremely outdated as of right now. I highly recommend using other HUDs like HXRTC HUD, which can be found in the Discord server. Cats Visor works too although it's a bit outdated in terms of the weapons, which I do plan to update only on the Discord server.

**Comment by lumbo7332** [comment]
Cool. Which channel can I find it?

**Comment by JMartinez9820** [comment]
> Cool. Which channel can I find it?

Community add-ons

**Comment by lumbo7332** [comment]
Thanks!

**Comment by lumbo7332** [comment]
Yeah. That fixes it.

**Comment by JMartinez9820** [comment]
If your issue is solved, then it can be closed.

**Comment by lumbo7332** [comment]
My bad. Could have sworn I did.
