### ISSUE TITLE
Improve demon AI

### ISSUE THREAD

**Issue by lumbo7332** [pa1nki113r/Project_Brutality#695]
I was thinking it would be really cool to have the demons have a higher level of intelligence. Things like getting into to cover to reload, laying down suppressive fire, flanking you.

I also saw some ideas here: https://forum.zdoom.org/viewtopic.php?t=55336

**Comment by JMartinez9820** [comment]
@lumbo7332 Suggestions do not belong in github issues, they should be put into the Discord server instead. Monster AI will be improved once their overhauls come in to place.

**Comment by lumbo7332** [comment]
Ah sorry.
