### ISSUE TITLE
GZDoom 4.7.0 + Project Brutality 3.0: missing Axe

### ISSUE THREAD

**Issue by ikir83** [pa1nki113r/Project_Brutality#703]
Hello.

Trying GZDoom 4.7.0 + Project Brutality 3.0
Everything seems to running smooth but zombie scientist have missing animations and when they drop melee axe, the axe is invisible even if you use it but you can use it.

I think it is a Project Brutality issue but since I see nobody talking about it I decided to post here.

When I start the game I get this:

LoadActors: Load actor definitions.
Script warning, "Project_Brutality-master.pk3:actors/weapons/slot1/axe.dec" line 35:
Icon 'AXE0A0' for 'PB_Axe' not found

Script warning, "Project_Brutality-master.pk3:actors/weapons/extra.dec" line 13:
Icon 'MP40I0' for 'DualMP40Ammo' not found

Script warning, "Project_Brutality-master.pk3:actors/weapons/extra.dec" line 611:
Icon 'MP40I0' for 'MP40Ammo' not found

Script warning, "Project_Brutality-master.pk3:actors/weapons/extra.dec" line 1867:
Icon 'HBUSD0' for 'BuzzsawAmmo' not found

**Comment by ikir83** [comment]
Sorry it was just a issue with auto-decompress downloaded zip and recompress later. I've downloaded the archive again and now it works

**Comment by JMartinez9820** [comment]
@ikir83 If your issue is resolved then it can be closed
