### ISSUE TITLE
Performance drop on some levels after kernel upgrade

### ISSUE THREAD

**Issue by Vladimir-csp** [pa1nki113r/Project_Brutality#705]
Hi!
I'm experiencing huge performance drop (slideshow grade) on some levels with PB after kernel upgrade from 5.10 to 5.14.
Example is map15 of Cchest2.wad
GZDoom 5.7.0, AMD Ryzen 3 5300U, AMD RENOIR (DRM 3.42.0, 5.14.0-1-amd64, LLVM 12.0.1) (0x164c).
No performance issues whatsoever were observed while on 5.10. or on 5.14 without PB and with Brutal Doom for comparison.
There is no apparent drop while the game is paused, menu animations are smooth, so it is most probably not related to graphics. Also I haven't found any performance issues in any other apps yet.

**Comment by JMartinez9820** [comment]
Hello, I have some recommendations in attempt to fix this.
1. Try using LZDoom 3.88. Although made for lower end PCs, it works a lot better than regular GZDoom most of the time. LZDoom can be found on the GZDoom download website under Alternative.
2. Use GZDoom 4.6.1 GLES. This is another GZDoom version that adds the GLES renderer. Although it runs better, shaders are disabled as a result though. GZDoom GLES can be found here: https://github.com/drdteam/gzdoom-gles/releases/tag/gles4.6.1

**Comment by Karl-515** [comment]
GLES is already implemented on the latest GZDooM version so you don't need to use a different one. Also, make sure that your GZDooM is always updated.

**Comment by Vladimir-csp** [comment]
I have the latest GZDoom, changing renderer to GLES (or any other) does not help at all.
LZDoom is also affected.
It seems that the problem is not related to graphics at all. Some gameplay-related CPU bound task becomes insanely ineffective on linux 5.14.

**Comment by JMartinez9820** [comment]
I would probably suggest reporting this to the GZDoom devs or Linux devs. Otherwise downgrading to Linux 5.10 is the other choice.

**Comment by JMartinez9820** [comment]
This could also be as a result of some recent code changes to PB, unfortunately this may not be fixed since some of our devs don't encourage Linux to be used.

**Comment by Karl-515** [comment]
This might not even be GZDooM's or PB's fault.  As someone who uses the latest kernel version (atleast what my distribution allows), My overall performance increased greatly when I switched from Vulkan to GLES, allowing me to finally hit 60 frames and above.

**Comment by Vladimir-csp** [comment]
https://github.com/coelckers/gzdoom/issues/1479
strace provided a possible lead

**Comment by Vladimir-csp** [comment]
Dug a bit deeper
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995997
Definitely not a PB problem
