### ISSUE TITLE
VM execution aborted: Invalid class RevenantPlayer in function call to PlayerPawnBase.StateFunction.0. PlayerPawnBase expected

### ISSUE THREAD

**Issue by sebastianpanetta** [pa1nki113r/Project_Brutality#715]
When picking up red demon rune:

VM execution aborted: Invalid class RevenantPlayer in function call to PlayerPawnBase.StateFunction.0. PlayerPawnBase expected

When picking up green demon rune:

VM execution aborted: Invalid class BaronPlayer in function call to PlayerPawnBase.StateFunction.0. PlayerPawnBase expected

Using GZDoom v 4.7.0

**Comment by JMartinez9820** [comment]
@sebastianpanetta Duplicate of #706. Demon Runes are going to be completely removed when pull #701 is merged.

**Comment by JMartinez9820** [comment]
For now use this patch and load it after PB: https://mega.nz/file/bzIm1Z5C#Ge6kwjAzTaxlBhPOlKQuFZvULI-K8Gk_CeGPTlRPIVo

**Comment by sebastianpanetta** [comment]
Thank you very much and sorry for the duplicate

**Comment by JMartinez9820** [comment]
@sebastianpanetta This issue can be closed as #701 has been merged.
