### ISSUE TITLE
Issue with zspecops zombie sprites and nazi's sound

### ISSUE THREAD

**Issue by Swimbrine** [pa1nki113r/Project_Brutality#727]
There was an instance where the zspecops sprites reverted to shotgunner sprites when the zspecops did a melee attack

Also the nazi would occasionally do zombieman grunts

**Comment by popguy12** [comment]
not all sprites and animations are done for some enemies, so they use the sprites setup in the base enemy it inherits from.

nazis are gonna get overhauled at some point, so no need to worry about that too much
