### ISSUE TITLE
grenade launcher upgrade not working?

### ISSUE THREAD

**Issue by Swimbrine** [pa1nki113r/Project_Brutality#728]
I encountered an upgrade for the grenade launcher but it didn't do anything.

**Comment by Swimbrine** [comment]
Sorry this took so long, but the thing is stupidly hard to come by! It's in game name is the DMR Grenade Launcher and it's sprite looks like an assault rifle with a grenade attachment... personally I think its a cool concept!
![Annotation 2021-11-24 053243](https://user-images.githubusercontent.com/94902113/143228972-a0abb9bc-f202-4ad4-8b73-ab9057fd5509.png)

![Annotation 2021-11-24 053304](https://user-images.githubusercontent.com/94902113/143228989-0278a384-0f51-4ef6-860a-af755c29814a.png)

**Comment by tedthedragon** [comment]
The GL upgrade has to be selected via the weapon special menu right now to do anything unlike some other upgrades. I've not had any issues with it.

**Comment by Swimbrine** [comment]
Ah! Yeah, it works, my bad!
