### ISSUE TITLE
PB 2.03 GZDoom "out-of-sync" Plutonia multiplayer coop

### ISSUE THREAD

**Issue by willnwhite** [pa1nki113r/Project_Brutality#733]
On level 30 (last level) of The Plutonia Experiment, in multiplayer coop, when the second player teleports through into the second room, the players go out-of-sync (the "out-of-sync" message appears). There's no issue without PB.

**Comment by tedthedragon** [comment]
This github isn't for 2.03 nor do we support co-op to the fullest extent. We haven't updated 2.03 since 2016 and that isn't changing any time soon either.

**Comment by willnwhite** [comment]
Sorry. If you don’t mind, could you point me in the right direction? I couldn’t find anything on https://www.moddb.com/mods/brutal-doom/addons/project-brutality or projectbrutality.com.
