### ISSUE TITLE
Project-Brutality-Master: no reload button

### ISSUE THREAD

**Issue by MajorPovis64** [pa1nki113r/Project_Brutality#734]
I downloaded the new version of P.B. and I thought it was really amazing, again the team behind the game's production did a great job, but there was a detail that I would say is fatal for gameplay in general, which was the lack of a button to reload weapons. I looked in all the control and command options and I didn't find it. I don't know if it's a bug, but at least for me it doesn't have a command to reload weapons. That's pretty uncomfortable in a way and I hope the producers will take a look or do something about it, that's it. Thanks for listening.

**Comment by tedthedragon** [comment]
We just use GZDoom's built in reloader. It's under Options -> Controls -> Action Controls -> Weapon Reload.

**Comment by MajorPovis64** [comment]
OH YES, TRUTH, FORGIVE MY LACK OF ATTENTION. Thanks ;)

**Comment by JMartinez9820** [comment]
This can be closed if resolved
