### ISSUE TITLE
Dual deagle draw bugged animation

### ISSUE THREAD

**Issue by sebastianpanetta** [pa1nki113r/Project_Brutality#737]
When selecting dual deagles draw animation occurs twice

**Comment by JMartinez9820** [comment]
A video showing this would be appreciated

**Comment by sebastianpanetta** [comment]
https://drive.google.com/file/d/1XbvcHa3kmZRu3PBbSRcMW0v71PvYIMHO/view?usp=sharing

**Comment by sebastianpanetta** [comment]
Having a closer look I'm not sure if the draw animation is playing twice, or it's intended to be that way and that "ready" sound is playing twice, let me know what you think

**Comment by sebastianpanetta** [comment]
> A video showing this would be appreciated. Also are you using master or another branch

Using master branch

**Comment by JMartinez9820** [comment]
> Having a closer look I'm not sure if the draw animation is playing twice, or it's intended to be that way and that "ready" sound is playing twice, let me know what you think

@sebastianpanetta The Ready/Select sound being played twice is intentional. Other weapons that dual wield do that as well.

**Comment by sebastianpanetta** [comment]
Perfect, thanks for the info, closing the issue then!
