### ISSUE TITLE
Rocker Launcher Lock On Mode

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#778]
There's an issue with the lock on mode for the rocket launcher, this mode doesn't works for the Spidermastermind variants, because when you lock 1,2 or 3 rockets on the spider, the rockets go nowhere, they go to otherside but no to the lock on target, this issue was also on previous builds.

Tested on latest Pb Build (Chrismas Update), with GZDoom 4.7.1 x64 and ZDL 3-1.1 without mods or addons.

**Comment by JMartinez9820** [comment]
The Spider Mastermind has a very hacky hitbox connected on to it called Spiders Hitbox, that's why it screws it. This is not a priority at the moment and will possibly be fixed when this monster is overhauled.

**Comment by JMartinez9820** [comment]
This issue will be closed for the time being until a fix is possibly made, or possibly not.
