### ISSUE TITLE
The "Weapon Respect Animations" option is broken

### ISSUE THREAD

**Issue by Mollusksux** [pa1nki113r/Project_Brutality#779]
The "Weapon Respect Animations" option is broken in  the PB settings, i've been bothered with the "Weapon Respect Animation while playing TNT: Evulution Map 9, the long Animations sometimes gets me annoyed because the Animations blocked my vision, any way to fix this bug? And also can we adjust the Doomguy wearing helmet speed?

![Screenshot_2021-12-27-09-04-44-37_e6009d95a270125ca6c92f670edc6cea](https://user-images.githubusercontent.com/92102444/147427132-c3d747d2-3bd1-46ee-b0aa-c7c7730f9370.jpg)

![Screenshot_2021-12-27-09-05-00-69_e6009d95a270125ca6c92f670edc6cea](https://user-images.githubusercontent.com/92102444/147427145-c5596075-e184-4905-ad2a-38b2bdbe4e79.jpg)

**Comment by JMartinez9820** [comment]
@Mollusksux This is because of the new Weapon Respect function called PB_RespectIfNeeded, which is a function where if the Weapon Respect token is not taken, is plays the respect animation. On some weapons it doesn't work because that function is not in place. This will be fixed after the DMR/HDMR additions are complete.

**Comment by JMartinez9820** [comment]
Edit: Recent changes broke it as we seem to have the one steps forward, two steps back issue again. I'll fix this as quickly as i can.

**Comment by JMartinez9820** [comment]
And it's fixed. Here is my branch if you want it fixed. Will also be fixed in pull #775.
https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch

**Comment by Mollusksux** [comment]
Thanks @JMartinez9820!
