### ISSUE TITLE
shotgun loop

### ISSUE THREAD

**Issue by Artagon96** [pa1nki113r/Project_Brutality#78]
shotgun stuck in loop when change shells between buckshot and slug

**Comment by scaryred24** [comment]
Can you replicate the problem on video?

**Comment by DisneyStarWarsisNonCanonHeresy** [comment]
He keeps switching ammo type automatically when raising and lowering the sight. Until getting the Dragons Breath/magazine upgrade.

**Comment by VR48** [comment]
I am having same issue.

**Comment by VR48** [comment]
The rep was updated 5 days ago, but I downloaded it yesterday and still had the issue.  Doom 2 wad loaded up, when using shotgun to aim, then when aiming off, shotgun switches ammo type for me everytime.  If you have chambers empty in shotgun and reload, it takes aiming off and reloads, but doesn't switch shells, which is fine.  Its only when you do a pure aim on, aim off toggle.

**Comment by Cacodemon345** [comment]
Wait until the Repo is updated again and merged with my PR.

**Comment by VR48** [comment]
Ok.  Thank you.

**Comment by VR48** [comment]
Tested.  The issue has been fixed.  Great work!
