### ISSUE TITLE
Jumping over liquids splashes while player is in the air

### ISSUE THREAD

**Issue by sebastianpanetta** [pa1nki113r/Project_Brutality#784]
While jumping over any liquid a "splash" happens while player is still in the air, not when landing

**Comment by JMartinez9820** [comment]
Unfortunately that might be an issue with ZMovement, this won't be fixed in my opinion because we may consider removing splashes entirely from the mod, since other mods can do splashes better,

**Comment by sebastianpanetta** [comment]
I think you are right about that, it would be better to remove splashes entirely, thanks for your quick answer, closing the issue then
