### ISSUE TITLE
Visual artifact - black cube, white line, no visible medkit

### ISSUE THREAD

**Issue by Denisiz** [pa1nki113r/Project_Brutality#786]
Hi, after update i see lettle black cube on screen. After little research:
1. this artifact in menu and HUD and etc.
2. cube tilting just same like as moved weapon sprite with weapons and player halds after turn left-right (for example).
3. Tryed change some HUD or gameplay options, but...

Screen:
https://ibb.co/QK73wVR

**Comment by JMartinez9820** [comment]
@Denisiz Please post a video as a photo won't help out much

**Comment by Denisiz** [comment]
Well, ok
Load order uses original doom2.wad and PB
..\gzdoom.exe -file Project_Brutality-master.zip
black cude change to white line 
  (last time been added custom wad in -file order after PB), but also now can't see medkit's (doom now hardcore, lol):
  https://drive.google.com/file/d/1weHnYYss9jllFTtueIG7Vbe23QebXoiH/view?usp=sharing
  
  For prev rev zip all been ok

**Comment by JMartinez9820** [comment]
Try doing this in the console to fix medkits:

pb_SmartScavenger 0
pb_SmartScavengerHealth 0
pb_HealthPackColor 0
pb_EnableCarryableHealth 0
pb_SmartScavengerNoFade 0

You may need to start a new game for these to take effect. If these don't work, you might have to delete your GZDoom ini file, which will basically reset your settings

**Comment by Denisiz** [comment]
Entered one by one and restart in-game session - no result
restart .exe - no effect, exscept black cude now is gray

Looks like now my game copy is cursed to be more difficult)
(Nightmare, Corruption cards mod, dont see medkit)

i try clean install (fresh gzdoom 4.7.1, last ver PB, no custom settings, no custom wad) - medkit visible

After i'm add Ccards mod and custom wad - all works. But all settings a default (ok, 10 min and all seems ok, some settings been removed like as Smart Scavenger, i see) - so it case resolved like "Clean install"

But i,m little sad - savegame's, what i'm copied before in folder with clean install - dont work (no see in load menu)
=\

**Comment by JMartinez9820** [comment]
This sounds like either graphics card or graphics driver issue, or some add-on is messing up. We plan to scrap Smart Scav entirely from the mod, as there are newer mods that have succeeded Smart Scavenger that work better. Did you try loading without add-ons or mapsets? Also, can you make a video when you can please?

**Comment by Denisiz** [comment]
Видеокарты GTX1050ti 2021 года производства. на видео ранее (ссылка выше) я как раз пробовал только PB мод и стандартный doom2.wad и был артефакт как белая линия вверху слева, и не видно аптечек.

Любопытно, хоть я их и не видел, и применил эти настройки в консоли, но слышал распаковку как при Smart Scavenger.

Сейчас все работает как надо, потому если нужны какие либо данные - можем связаться онлайн с демо экрана, и соберем журналы системы или игры, если кейс нужен.
GTX1050Ti graphics cards manufactured in 2021. on the video earlier (link above) I just tried only the PB mod and the standard doom2.wad and there was an artifact like a white line at the top left, and no first aid kits are visible.

It's curious, even though I didn't see them, and applied these settings in the console, but I heard the unpacking as with Smart Scavenger.

Now everything is working as it should, because if any data is needed, we can contact the demo screen online, and collect the logs of the system or the game, if the case is needed.
