### ISSUE TITLE
Manual Reload , Dual wield . Grenades Binds Bug-Brutal Doom v21 Class

### ISSUE THREAD

**Issue by goldenmobster** [pa1nki113r/Project_Brutality#79]
-The weapons can't be manually reloaded , which means that the reload key or bind doesn't work
-Grenade key or bind doesn't work/function 
-Dual Wield key doesn't work/function

These happen on the Brutal Doom v21 Class

**Comment by scaryred24** [comment]
Our main focus right now is the project brutality class but we will certainly look into other classes as well.

**Comment by goldenmobster** [comment]
Yes

**Comment by Cacodemon345** [comment]
BDv21 class is being tossed out, so no real point in this issue.
