### ISSUE TITLE
Dual pistol fire misbehavior

### ISSUE THREAD

**Issue by sebastianpanetta** [pa1nki113r/Project_Brutality#791]
When firing with dual pistols with Dual Wield Fire Mode = Single Button and not holding fire but instead rapidly clicking to shoot, left pistol fires most of the time and right pistol fires only once in a while (like 5 or more times left to 1 times right)

Video here:

https://drive.google.com/file/d/133R64ulGejwlLPqyzZIprcEXTUbSac4n/view?usp=sharing

**Comment by JMartinez9820** [comment]
It's because of the tic count for the burst fire, i may reduce it to prevent this, will be fixed in a little bit. When using the Single Button, the mouse button is normally supposed to be held when the single button option is on

**Comment by sebastianpanetta** [comment]
Perfect, thank you very much
