### ISSUE TITLE
Title screen not showing correctly when higher fov

### ISSUE THREAD

**Issue by sebastianpanetta** [pa1nki113r/Project_Brutality#792]
Title screen shows like this when using a higher fov than normal (e.g. 120)

![image](https://user-images.githubusercontent.com/49350896/148311682-e90bf8e3-4655-43b9-a214-dbc9527f3312.png)

**Comment by popguy12** [comment]
yea thats known, just part of how the titlemap works, honestly the titlemap needs to be redone anyways

**Comment by sebastianpanetta** [comment]
Thank you for your response, if it's known then I'm closing the issue
