### ISSUE TITLE
When grabbing enemy and throwing weapon always change to pistols

### ISSUE THREAD

**Issue by sebastianpanetta** [pa1nki113r/Project_Brutality#794]
When grabbing an enemy and throwing the body, current weapon changes to pistols regardless of the weapon selected before grabbing

**Comment by JMartinez9820** [comment]
Will be fixed when we find a way that can log last weapon selected by the player that it can change too instead of the Pistol. I know that using ACS is one way, but right now we're trying to mostly do ZScript for the time being.

**Comment by sebastianpanetta** [comment]
I don't know that much about ACS or ZScript, only the basics, but in the Gearbox Weapon Wheel plugin there's a function for selecting "last weapon", maybe adapting that could help? Let me know what you think

**Comment by JMartinez9820** [comment]
This can be closed due to the barrel update
