### ISSUE TITLE
Game freezes when using Dual-Wield weapons

### ISSUE THREAD

**Issue by Nightmarekiller84** [pa1nki113r/Project_Brutality#796]
When I am using dual-wield Revolvers and my clips are empty and in my ammo have only 1 bullet left, when it will start reloading it will freeze(not crash). In the very worst case scenario my OS will freeze and not even crt+alt+del will work and have to restart my PC. I remember this problem to happen also in the earlier versions too and I think there is also another similar mention somewhere here. This also can happen with the Desert Eagle.
I am using gzdoom 4.5.0

**Comment by JMartinez9820** [comment]
Any ways to replicate this? What are you PC specs?

**Comment by Nightmarekiller84** [comment]
Processor: Intel Core i7-2700k CPU @3.50GHz
RAM: 8GB
Windows 7 Ultimate
Nvidia GeForce 980 GTX

**Comment by Nightmarekiller84** [comment]
I double checked and it seems the freezing happens when you have ONLY 1 ammo left and try to reload while having dual-wield Revolvers AND Desert Eagles.

**Comment by Nightmarekiller84** [comment]
![Uploading Screenshot_Doom_20220111_223227.png…]()

**Comment by Nightmarekiller84** [comment]
![Screenshot_Doom_20220111_223227](https://user-images.githubusercontent.com/97555507/149017120-7bf2737f-006f-49fb-8114-a59db27789bb.png)

**Comment by JMartinez9820** [comment]
I'll take a look at this now. Shouldn't be too hard to fix, because one of the A_JumpIfInventory functions needs to have a 2, since the revolver and deagle reload takes up twice the amount of ammo.

**Comment by Nightmarekiller84** [comment]
I learned recently on how to use Slade 3, so maybe I could fix this on my own but I am still a newbie ;)

**Comment by JMartinez9820** [comment]
@Nightmarekiller84 Just fixed it now on my branch. If you don't want to use my branch then I can post a patch on here or on the Discord server.
https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch

**Comment by Nightmarekiller84** [comment]
And ironically by luck I discovered that the Dual-Wield Super Shotgun can cause freezing if you have no ammo left at all and keep holding the fire button.

**Comment by Nightmarekiller84** [comment]
> @Nightmarekiller84 Just fixed it now on my branch. If you don't want to use my branch then I can post a patch on here or on the Discord server. https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch



> And ironically by luck I discovered that the Dual-Wield Super Shotgun can cause freezing if you have no ammo left at all and keep holding the primary fire button or the secondary fire button.
