### ISSUE TITLE
MagCaco invisible when frozen

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#799]
MagCaco disappears when frozen. Missing sprites maybe?

**Comment by JMartinez9820** [comment]
Yes it's missing sprites, apparently I guess Pope of Dope forgot to add the sprites because he had them on a build he was working on. I'll see if I can find them because iirc Kamil made some of the frozen monsters that are missing

**Comment by TonyH1234** [comment]
Found more missing sprites. The Infernus (Bruiser Demon?) is also invisible when frozen.
