### ISSUE TITLE
Ice shard and kill counter

### ISSUE THREAD

**Issue by HavocParker** [pa1nki113r/Project_Brutality#807]
When i play PB with 𝗘𝘅𝘁𝗲𝗿𝗺𝗶𝗻𝗮𝘁𝗶𝗼𝗻 𝗗𝗮𝘆, the ice shard from frozen barrel count toward to kill counter, making 100% kill run impossible.

**Comment by D3X1KAXYZ** [comment]
Does this only happen with the **BD campaign**?

**Comment by D3X1KAXYZ** [comment]
I believe this is a known issue with a fix coming soon (tm)

**Comment by JMartinez9820** [comment]
@HavocParker @D3X1KAXYZ 
This was now fixed in the latest commit iirc.

**Comment by D3X1KAXYZ** [comment]
> @HavocParker @D3X1KAXYZ 
> This was now fixed in the latest commit iirc.

I didn't see dopes branch among the list of merges before.
So yeah this should be fixed, I shall close this
