### ISSUE TITLE
Semi-Invincible Imps

### ISSUE THREAD

**Issue by B0ltCatcher** [pa1nki113r/Project_Brutality#808]
Finally! I've been encountering this glitch for years and I've finally figured it out. When an Imp (of any type, standard or dark) is knocked over and stands back up, it seems to lose its bullet-based hitboxes, but is still vulnerable to splash damage.

I've repeatedly encountered this glitch in a custom monsters-only version, but that shouldn't matter, as this only occurs with the imps and not with other monsters (that I have seen, at least).

**Comment by VR48** [comment]
This must explain why the imp is sometimes invulnerable to infighting damage.  I generated OBLIGE maps with lots of enemies and encountered 2 or 3 imps with this issue that survive knockdown from nearby infight grenade explosions.

**Comment by JMartinez9820** [comment]
Imps will be overhauled later on so hopefully this issue will also be fixed on their overhauls

**Comment by JMartinez9820** [comment]
Going to close this for now.
