### ISSUE TITLE
(Custom Fork) Monsters-Only version crashes at intermission screen for any level past E1M2 or Map04

### ISSUE THREAD

**Issue by B0ltCatcher** [pa1nki113r/Project_Brutality#809]
Let me know if I should move/remove this, but is there somewhere specific should I ask questions related to my custom Monsters Only version of PB? For that matter, where should I upload it for public Beta testing? I initially only made it for myself so it's been pretty mangled from the base version (a lot of one-off changes to avoid decorate errors that added up over time), but it's still a cool and surprisingly compatible mod that I think others might enjoy as a fun diversion.

My only *major* issue is related to inter-map freezing that occurs with E1M3+ and Map04+; if I try to load either these maps or any map after it, the game will freeze/crash at the intermission screen before the level starts, and I'm going nuts trying to figure out why. I had to remove a lot of scripts/actors in order to get it to run at all, but those removals don't affect the maps that launch properly, only when a new map is launched. This seems to be based on the map number, as it occurs with both Vanilla maps and map packs that use the same map names. When I loaded E1M3 in vanilla PB, I get an error message of "Line 933's right edge is unconnected" so that's my only clue, but I don't encounter that error with any of the other maps that encounter the same issue so that isn't much help- might be a complete red herring. I've tried removing the Dynamic levels but that didn't change anything, so I'm at a complete loss. The Smartscav scripts are also missing (not reimplemented yet, removed for max vanilla-compatability) but I don't see how that would make a difference?

I know how little information I'm providing, but is there anything obvious going on under the hood on later maps that doesn't happen on E1M1/E1M2 or Map01-03? Also, please let me know how/where to upload the .zip of the MO version, creating a new fork doesn't seem to let me.

Edit: In Doom 2 the glitch kicks on Map04, not Map05. Test on GZDoom 4.6.1 and 4.7.1.

**Comment by JMartinez9820** [comment]
@B0ltCatcher We will not accept any bug reports on the Monsters Only version. The Monsters Only version is likely based on a very outdated version of the PB monsters.

**Comment by B0ltCatcher** [comment]
No no no, it's my own 'monsters only' version of the current version of Project Brutality. I specifically made it in response to the flaws in the OG (2017) PB3MO. Hence why it works exponentially better (not to flatter myself).

**Comment by JMartinez9820** [comment]
Still, we won't accept any bug reports on custom forks.

**Comment by B0ltCatcher** [comment]
Got it, but where could/should I get input on patching the glitch I described? I'm trying to get some pointers to fix it myself, not to report it for someone else to fix. I've tried to resolve it on my own but I can't even figure out where the error is located. I don't want to have that thread in the wrong place but I didn't see anywhere more relevant.
