### ISSUE TITLE
M1 Plasma Gun and Configure Monster Abilities

### ISSUE THREAD

**Issue by Nightmarekiller84** [pa1nki113r/Project_Brutality#813]
1) M1 Plasma Gun:

a) The alt-fire of the plasma gun is to shoot a charged attack costing 12 cells, but for what ever reason if I try to use the alt-fire when only having 12-13 cells it won't shoot(when you are out of reserve ammo) or it will reload.

b) This one is peculiar and I like it but still I will report it just in case. When you empty a clip using primary fire and after the weapon reloads, you can use the alt-fire key attack INSTANTLY, no charging animation at all.

2) Configure Monster Abilities:

a)  In the Configure Monster Abilities, there is an option to disable the zombie men throwing grenades at you, frankly that option never work for me, normal and shotgun zombie men still throw grenades at me.

**Comment by JMartinez9820** [comment]
1. Known since either 2.03 or earlier 3.0 builds.
2. Most of these toggle use outdated ACS scripts, which will be fixed later to use GetCvar from Decorate.

**Comment by JMartinez9820** [comment]
Update:
1. The M1 Plasma altfire not shooting when having 12 or 13 cells is a new issue that I am now fixing. The reloading when less is intentional though. The instant charge can be fixed by using A_ClearReFire, which I just fixed on my branch.
2. Like I mentioned above.

**Comment by Nightmarekiller84** [comment]
Thanks as always

**Comment by SchnozBott** [comment]
'No Zombie Grenades' toggle still not working, and they seem to throw grenades whenever possible now

**Comment by JMartinez9820** [comment]
@SchnozBott 
Not a top priority right now, this will be fixed possibly way later since monster overhaul hasn't been done yet.

**Comment by SchnozBott** [comment]
@JMartinez9820 Current version is virtually unplayable with the current zombieman grenade spam behavior, but at least I have an old version until a fix gets made eventually

**Comment by JMartinez9820** [comment]
@SchnozBott I saw your comment and you said that it's unplayable, well if that's the case then use my branch since the hand grenades for the enemies or nerfed. I tried to nerf it as much as I could because I didn't want the grenades to deal a wet fart worth of damage (basically low damage).
https://github.com/pa1nki113r/Project_Brutality/tree/JMartinezBranchOfficial

**Comment by SchnozBott** [comment]
@JMartinez9820 Thanks I'll try it, just didn't wanna get one shotted over and over in early maps of doom2 that I normally breeze through. Sorry I realized shortly after that my reply was overly bitchy so I tried to make it go away lol.

**Comment by popguy12** [comment]
i think this has been fixed since yea, ill be closing this, lemme know if its still cropping up
