### ISSUE TITLE
Monster teleport bug involving scripting

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#815]
Just played a really cool map involving many special effects and scripting (MMDCXIV-Debut). But I had to play it with Brutal Doom Platinum to finish it. With PB I got stuck at the blue key. Picking it up runs a script which triggers 13 monsters to teleport into the area. You are suppose to kill them all to unlock the door to progress. Only 2 teleported, I killed them but the others didn't teleport, so I got stuck. This has happened in other maps I've played with similar situations.

**Comment by JMartinez9820** [comment]
To be honest, this isn't a top priority at the moment. I think you're better off reporting this to the map author rather than us. We will possibly deal with this later, this isn't a priority at the moment.

**Comment by TonyH1234** [comment]
Fair enough, no hurry. Just thought I would point it out in case you weren't aware of it.

**Comment by popguy12** [comment]
might be fixed now with the spawner overhauls, ill close the issue but lemme know if it still happens
