### ISSUE TITLE
Infinite Imp one leg dancing and Lost Soul

### ISSUE THREAD

**Issue by Nightmarekiller84** [pa1nki113r/Project_Brutality#816]
![Screenshot_Doom_20220125_172232](https://user-images.githubusercontent.com/97555507/151007409-96544ae2-5cb1-4da4-81be-8481053acf8b.png)

1) In this specific animation were the Imp is trying to stay standing with 1 leg is ..............infinite LOL. I don't know if this is intentional.
Note that this happens to all the Imp variants.

2) For whatever mysterious reason, when I am using Deagle or Revolver to shoot at a Lost Soul, it requires 2 bullets to finish it off while the Phantasm variant requires only 1 bullet. Does the normal Lost Soul have more Health pool and the Phantasm has lower in return for it's aggressiveness ?

**Comment by JMartinez9820** [comment]
Personally idk why the imp thing happens, I may consider doing the death timer method, which loops until the death timer inventory is completed. Much better than adding it 100 times. As for the lost soul, I'm probably going to decrease it health so it matches with the Phantasm.

**Comment by Nightmarekiller84** [comment]
I discovered that this is actually NOT a bug, the cause is notarget LOL
sorry for the trouble please close this subject
