### ISSUE TITLE
.zip compile is damaged

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [pa1nki113r/Project_Brutality#819]

**Comment by D3X1KAXYZ** [comment]
Try running the .zip file as if it were a pk3

**Comment by Ganbare-Lucifer** [comment]
actors, zscript and brightmap folders are corrupted.

Repairing the file doesn't even fix it.

**Comment by D3X1KAXYZ** [comment]
You'll need to re-download the file then

**Comment by Ganbare-Lucifer** [comment]
I tried, still doesn't work

**Comment by D3X1KAXYZ** [comment]
Don't extract the file. Just open it with gzdoom

**Comment by JMartinez9820** [comment]
This is NOT an issue and will be closed. One method you can also try doing is download GitHub Desktop and cloning the repository from here. I will also update the MediaFire link and repost it here.

**Comment by DemonSlayer1997** [comment]
https://www.mediafire.com/file/nu3074lbk0lmjfd/Project_Brutality_%2528Compressed%2529.pk3/file
Happy gaming dude ^^

**Comment by JMartinez9820** [comment]
https://www.mediafire.com/file/7ubb1d1kbv9r6ol/Project_Brutality-master.zip/file
See if this works

**Comment by JMartinez9820** [comment]
@Ganbare-Lucifer Did the Github link fix your problem
