### ISSUE TITLE
Como ativar os cheats  PB 3

### ISSUE THREAD

**Issue by Bantumin** [pa1nki113r/Project_Brutality#820]
Oi alguém pode me ajudar a habilitar as trapaças no PB 3? diz que não esta habilitado ou algo assim...

**Comment by D3X1KAXYZ** [comment]
> en su mayoría hablamos inglés, por lo que esto es una traducción automática. si pudiera usar inglés en el futuro (incluso si se traduce automáticamente) sería muy apreciado. ^^

PB 3.0 does not disable cheats anymore.
Either you are using a really old build (in which you should update) or another addon is disabling cheats
you can re-enable cheats at any time by opening the console (by pressing "~") and typing `sv_cheats 1`.
you will need to start a new game after doing so

if you are using a launch such as ssgl, doom runner, zdl, zde, etc..., you can type `+sv_cheats 1` into the additional parameters/ command line arguments

alternatively you can create a text file, type `sv_cheats 1` into it, then save it in your gzdoom folder as `autoexec.cfg`
this will make gzdoom launch with cheats turned on by default.

hope this helps

**Comment by D3X1KAXYZ** [comment]
Since this is not an active PB bug i shall close this issue. If you need more assistance with this issue, you can join the pb community server or zdoom server on discord, check the zdoom wiki, or check out/ask the zdoom forums.
