### ISSUE TITLE
Cant download (i think im stupid)

### ISSUE THREAD

**Issue by BOMB-DROPER** [pa1nki113r/Project_Brutality#825]
I am unable to download the ZIP file, it will let me download the files individually but not the whole thing

**Comment by DemonSlayer1997** [comment]
> I am unable to download the ZIP file, it will let me download the files individually but not the whole thing

https://www.mediafire.com/file/nu3074lbk0lmjfd/Project_Brutality_%2528Compressed%2529.pk3/file

**Comment by DemonSlayer1997** [comment]
> I am unable to download the ZIP file, it will let me download the files individually but not the whole thing

I have already taken care of users who have this problem. Have a nice game ^^
