### ISSUE TITLE
Crash when using weapon special wheel

### ISSUE THREAD

**Issue by RadSuit** [pa1nki113r/Project_Brutality#826]
[Console report](https://i.imgur.com/wL3EbaS.png)

**Comment by JMartinez9820** [comment]
This is a known issue but currently no way of fixing it. And iirc, this might be a duplicate issue, so please look at closed or open issues before posting.

**Comment by Darkneece** [comment]
I believe this is a walk around.

at
zscript\PbWheel\ev_drawer_special.zsc : 24
and
zscript\PbWheel\ev_core_special.zsc : 1418

`int curSelMod = wheelShow[currentSelection];`
change to
`int curSelMod;
if (currentSelection >= wheelShow.Size()) {
	curSelMod = wheelShow[0];
} else {
	curSelMod = wheelShow[currentSelection];
}`

At least it prevents crash.
