### ISSUE TITLE
When dragging the ZIP file to gzdoom.exe, it just runs regular Doom and not Project Brutality

### ISSUE THREAD

**Issue by MarselTheLynx** [pa1nki113r/Project_Brutality#829]

**Comment by MarselTheLynx** [comment]
> Would recommend a front-end mod loader then. ZDL - a simple but flexible loader, quite well known  DoomRunner - as flexible as zdl, but has a lot more configuration options  SSGL - a loader with a focus on personalization. Not as flexible, but great for more casual mod players and newcomers Links to these can be found in the readme

I tried ZDL, but it's still the same problem

**Comment by Cacodemon345** [comment]
@MarselTheLynx Does it print the name of the ZIP file on startup?

**Comment by MarselTheLynx** [comment]
> @MarselTheLynx Does it print the name of the ZIP file on startup?

It doesn't

**Comment by JMartinez9820** [comment]
closing due to no response. Please reopen this if this issue still persists.
