### ISSUE TITLE
Some thing wrong with "Revenant code"

### ISSUE THREAD

**Issue by Somie98** [pa1nki113r/Project_Brutality#848]
Hey guy i just found a bug on "revenant" when i kill him with LMG of hit scan weapon his body spread of half when his body part is still alive i kill him and got this bug and crash to console "https://www.mediafire.com/view/uc1raxot4jn5liq/bandicam_2022-02-20_21-52-06-823.jpg/file#"

**Comment by JMartinez9820** [comment]
Unable to replicate this issue. Please have some instructions on how to reproduce this.

**Comment by JMartinez9820** [comment]
Closing issue due to lack of response and that this issue was unable to be replicated.
