### ISSUE TITLE
Pistol ADS Bugs with Weapons

### ISSUE THREAD

**Issue by GeoDash897** [pa1nki113r/Project_Brutality#872]
Hello! It's been a while since I've posted something here!
This occurs on the most current master branch version of Project Brutality (last commit = **2/24/22**) on **GZDoom 4.7.1**

There are various bugs when switching to a different weapon after aiming down sights (ADS) with the Pistol.
I decided to group them together since they were very similar to each other:

If this is a duplicate, I will close this issue if need be.

## Bug 1: Switching from ADS Pistol to any weapon
Switching from ADS Pistol to **any weapon** and then back to Pistol again will zoom in the FOV of the player as if they were still ADS (even though they are not).

**Method to perform this bug:**
  1. ADS with Pistol
  2. Swap to a different weapon **without returning from Pistol's ADS**
  3. Swap back to the Pistol

You should notice that despite being out of ADS for the pistol the FOV is still zoomed in.

https://user-images.githubusercontent.com/55932902/155832119-51e59930-8550-460a-91b0-ecce2efdd1c9.mp4

## Bug 2: Switching from ADS Pistol to DMR
Switching from ADS Pistol to the **DMR** will make the player ADS with the DMR automatically even if they weren't ADS beforehand. 
Alongside this, the player FOV when ADS in this bugged state matches the Pistol's ADS, not the DMR's ADS.
The ADS Pistol switch to any weapon for the Pistol from before is still in effect.

**Method to perform this bug:**
  1. ADS with Pistol
  2. Swap to the DMR

https://user-images.githubusercontent.com/55932902/155832740-1cc295d2-d189-4b9d-976c-cc49d459a4b3.mp4

## Bug 3: Switching from ADS Pistol to MP40
Switching from ADS Pistol to the **MP40** and trying to ADS will make the MP40 bug out and quickly enter and exit ADS.
The ADS Pistol switch to any weapon bug for the Pistol from before is still in effect.

**Method to perform this bug:**
  1. ADS with Pistol
  2. Swap to the MP40
  3. ADS with MP40

https://user-images.githubusercontent.com/55932902/155833029-dde12036-20ad-4cd8-8e16-3b24dd12d087.mp4

**Comment by JMartinez9820** [comment]
To be fixed in #870

**Comment by JMartinez9820** [comment]
Update: Fixed in PB_Staging as well.
