### ISSUE TITLE
game crashing when launching the game

### ISSUE THREAD

**Issue by pootishoovy** [pa1nki113r/Project_Brutality#878]
im using the lastest version of gzdoom and project brutality and i get this error:
Script error, "D:/SteamLibrary/steamapps/common/Ultimate Doom/Project_Brutality-master/:zscript.zc" line 68:
Include script lump zscript/PBVP/PBVP.zc not found
no addons or whatever

**Comment by JMartinez9820** [comment]
@pootishoovy Which GZDoom version are you using?

**Comment by pootishoovy** [comment]
@JMartinez9820 4.7.1

**Comment by JMartinez9820** [comment]
My suggestion is to retry downloading PB, make sure you doing have anything conflicting with the mod. If that doesn't work, then I'll post a Google Drive link here

**Comment by pootishoovy** [comment]
@JMartinez9820 ok

**Comment by pootishoovy** [comment]
still giving me the error

**Comment by pootishoovy** [comment]
and i dont have anything that conflicates with the mod

**Comment by pootishoovy** [comment]
@JMartinez9820 now im getting Script error, "D:/SteamLibrary/steamapps/common/Ultimate Doom/base/Project_Brutality-master/:cvarinfo" line 1:
cvar 'py_weaponwheel_freeze' already exists

**Comment by JMartinez9820** [comment]
Make sure you're not using the pywheel add-on

**Comment by pootishoovy** [comment]
nope, not using the pywheel addon

**Comment by pootishoovy** [comment]
im not even using any addon @JMartinez9820

**Comment by JMartinez9820** [comment]
I don't even know what to do then. Here is what I would try doing:
- Redownload PB from here: https://drive.google.com/file/d/1d8ses842nLnI7qD1qPUHa6eD6Q4wEB3x/view?usp=sharing
- Fresh reinstall of GZDoom (delete all GZDoom files and reinstall again)

If none of this gets resolved, I will close this.
