### ISSUE TITLE
dmr doing same damage as upgraded dmr, too OP (2 shots to kill zombieman, shotgunguy, imp etc)

### ISSUE THREAD

**Issue by duc83** [pa1nki113r/Project_Brutality#884]
i started playing and realised the dmr doing a lot more damage than it should

**Comment by Nightmarekiller84** [comment]
It's already being mentioned and fixed, re-donwnload the newest version please

**Comment by JMartinez9820** [comment]
Closing issue, fixed on my build and Staging
