### ISSUE TITLE
Rip and Tear! Holding enemy head loop bug

### ISSUE THREAD

**Issue by VR48** [pa1nki113r/Project_Brutality#89]
When using rip & tear while enraged with bare hands, the fatality sneak attack on enemy marine (tested against shotgun enemy only so far) presents a bug where holding enemy head for throwing keeps loop-switching against bare hand sprite and head holding sprite.  Head throwing does work and stops the loop bug.

**Comment by forkoz** [comment]
yep confirm this on build from last month. will have to check this month.

**Comment by JMartinez9820** [comment]
This bug is still not fixed in newest version

**Comment by JMartinez9820** [comment]
This issue is now fixed in the latest commit, can now be closed.
