### ISSUE TITLE
Picking up second HDMR causes held item to revert to standard DMR sprites

### ISSUE THREAD

**Issue by DaWrecka** [pa1nki113r/Project_Brutality#891]
Using repo as of 2022-03-07 and GZDoom 4.7.1

https://user-images.githubusercontent.com/61927940/157083639-81416a65-865a-443a-af9f-84d7f8a3f0f5.mp4

**Comment by JMartinez9820** [comment]
Make sure that you are not using add-ons because it might conflict with the HDMR

**Comment by DaWrecka** [comment]
The only "addons" (in quotes because I'm using that term loosely) I'm using in the above video are DoomMetalVol4.wad, and Doom Complete. But I'll try with just Doom2.wad and no DoomMetal.

**Comment by DaWrecka** [comment]
Tried with just Doom2.wad and no addons at all besides Project Brutality; same behaviour.

However, there has been a development. Specifically; I've learned this only happens when sv_unlimited_pickup is set to true. If set to false, you can pick up a second HDMR without the issue triggering.

**Comment by JMartinez9820** [comment]
Closing for now
