### ISSUE TITLE
Mantling just fails sometimes

### ISSUE THREAD

**Issue by DaWrecka** [pa1nki113r/Project_Brutality#892]
But only sometimes... this recording was started after I successfully climbed up that one ledge multiple times. I've not yet been able to identify a pattern. Once this happens, only being killed will reset this behaviour. (which obviously only works in coop)

https://user-images.githubusercontent.com/61927940/157090694-f9aee355-4885-423a-80b6-554cd5d074dd.mp4

**Comment by JMartinez9820** [comment]
I remember hylian having a similar problem too, unfortunately I won't fix this due to the complex of zscript.

**Comment by Barbatuile** [comment]
Hello @DaWrecka !

I have raised a similar case yesterday, this is due to sv_unlimited_pickup, you most likely play with it set to 1 just like me.
If you disable it, ledge grab will not freeze.

**Comment by JMartinez9820** [comment]
To be fixed in #948
