### ISSUE TITLE
Reloading LMG while ammo is full/near full results in lost ammo

### ISSUE THREAD

**Issue by DaWrecka** [pa1nki113r/Project_Brutality#894]
Procedure:

- Have full or nearly-full heavy ammo
- Reload, unload, or change ammo types on the LMG
- During the animation, ammo in the LMG's magazine is unloaded into main ammo pool, which cannot hold it and so the ammo is lost.
- LMG magazine is reloaded from ammo pool.

Example; 800 heavy ammo in reserve, 75 ammo in LMG mag, change ammo type with weapon special.
LMG mag is emptied to 0 during animation, which tries to put the ammo in reserve - but reserve is already full.
LMG mag is then refilled; LMG mag now holds 75 ammo, with 725 rounds in reserve.

**Comment by JMartinez9820** [comment]
Fixed in PB_Staging:
https://github.com/pa1nki113r/Project_Brutality/tree/PB_Staging
