### ISSUE TITLE
Plasma rifle: Unload clip bug

### ISSUE THREAD

**Issue by VR48** [pa1nki113r/Project_Brutality#90]
Unloading a clip with plasma rifle hides the gun and disables you from firing or switching to another.  Weapon sprite disappears as well.

This bug wasn't previously there 2 versions ago.

**Comment by Cacodemon345** [comment]
It's a issue with how the unloading system works. It's a mess.

**Comment by VR48** [comment]
Double plasma rifle unloading works fine.  Single doesn't.  Thanks for letting me know.
