### ISSUE TITLE
game breaks when jumping or falling

### ISSUE THREAD

**Issue by neguschungus** [pa1nki113r/Project_Brutality#903]
![unknown](https://user-images.githubusercontent.com/96950067/158905532-fe142e42-fef3-4068-9ea1-72a5f38f1084.png)

**Comment by JMartinez9820** [comment]
Try these:
1. Go into the visual settings and check to see if you can mess around with the weapon bob settings
2. Delete the GZDoom.ini file

**Comment by D3X1KAXYZ** [comment]
alternatively, enter `zm_offsetmaxrange 10` into the console
or change the following option
![image](https://user-images.githubusercontent.com/18036439/158907698-5c650eb5-6fa8-4050-8ca2-3d6a43e20790.png)
