### ISSUE TITLE
hitboxes on enemys' wack, imps being invincible on chest area, zombiemen and chaingunguys invincible on heads 

### ISSUE THREAD

**Issue by duc83** [pa1nki113r/Project_Brutality#905]
when i played pb 3.0 and used dmr on imps (had this problem for while but just coped), on elevated planes where the imp would be above me, i'd shoot at it but wouldn't do damage; the blood would spurt but no damage. and this'd be the same for zombiemen and chaingunguys when they would crouch and shoot and, with the dmr, couldn't do damage to them until they uncrouched and their hitbox showed.  
it feels like theres no hitboxes on the zombie guys' heads and with imps no hitboxes on their chest area.

**Comment by JMartinez9820** [comment]
Please provide a description on your issue please. Failure to do so within 24 hours will result in this issue being closed.

**Comment by JMartinez9820** [comment]
Along with instructions on reproducing this issue.

**Comment by duc83** [comment]
like right under where the imp's head is, it wont deal damage and when shooting up to one (elevated surface), i hit there and it does no damage).  
like when i have berserk and am punching imps,  i punch at there chest area because eye-level and it dont register the hit and the imp just keeps scratching me

**Comment by RandomTNT** [comment]
Developer Speak: He uses berserk, does a hit on the middle area of imps hitbox, but it doesnt register
