### ISSUE TITLE
Decor destructibility

### ISSUE THREAD

**Issue by WarFoxy** [pa1nki113r/Project_Brutality#906]
#726 
Currently there is a thing that a machete hit on any decoration (impaled marines, etc) looks like a spark, which is stupid. Removal of decor destructibility is a major step back. Please consider reverting this change or making it optional.

**Comment by D3X1KAXYZ** [comment]
Not really a bug. I do believe there are plans to redo that stuff, however, we are currently focused on guns, monsters, and core gamplay at the moment. Things like this will most likely come later.
For more information regarding why features get removed,
<a href="https://github.com/pa1nki113r/Project_Brutality/wiki/_FAQ#i-dont-like-insert-new-featurespriteetc-here-why-did-you-remove-insert-old-featuresprite-setetc-here-please-bring-insert-old-featuresprite-setetc-here-back"> check out the new wiki.</a>

**Comment by JMartinez9820** [comment]
This issue will be closed and marked as invalid.
