### ISSUE TITLE
error code when using winRAR to open zip file: ! C:\Users\liamj\Downloads\Project_Brutality-master (1).zip: Unexpected end of archive

### ISSUE THREAD

**Issue by slippedonaknot** [pa1nki113r/Project_Brutality#908]

**Comment by JMartinez9820** [comment]
@slippedonaknot You did need to extract the file to play PB, you just load it with GZDoom by basically treating the .zip as a .pk3

**Comment by JMartinez9820** [comment]
@slippedonaknot You don't need to extract the file to play PB, you just load it with GZDoom by basically treating the .zip as a .pk3

**Comment by JMartinez9820** [comment]
If you're having issues, use this link:
https://drive.google.com/file/d/1d8ses842nLnI7qD1qPUHa6eD6Q4wEB3x/view

**Comment by slippedonaknot** [comment]
thanks for telling me how to do this!
