### ISSUE TITLE
Dropping or throwing barrels causing a crash. A_Lower called without valid caller. Weapon expected.

### ISSUE THREAD

**Issue by CaptPatrick01** [pa1nki113r/Project_Brutality#91]
![vm](https://user-images.githubusercontent.com/29268823/50565876-4c168100-0ce8-11e9-992c-8bda1d3d0b5b.jpg)

**Comment by Cacodemon345** [comment]
I have no idea what happens here. But it looks like some sort of strict check in GZDoom 3.7.0.

**Comment by Patarzachash** [comment]
When I get this crash, GzDoom just stops responding.

**Comment by MekBoss** [comment]
As from screenshot, a_lower function called from something which is not a weapon, I suspect inventory item.
So before call it you need to check is that "something" is a weapon.

**Comment by JackieDog** [comment]
I got the same error (GzDoom 3.7.2). Seems to happen when you grab a barrel with anything other than your fists.
- Punching a barrel to pick it up and then throwing / putting it down - OK
- Pressing the “Use/Open” key **while using fists** to pick up the barrel and then throwing / putting it down - OK
- Pressing the “Use/Open” key **while having equipped any weapon** to pick up the barrel and then throwing / putting it down - CRASH

**Comment by Cacodemon345** [comment]
This issue should be fixed though.

**Comment by scaryred24** [comment]
Apparently not as it reared its ugly head up again as #205 shows.

**Comment by pa1nki113r** [comment]
Can confirm this has been fixed.
