### ISSUE TITLE
PC Runs out of memory

### ISSUE THREAD

**Issue by Anananel** [pa1nki113r/Project_Brutality#916]
I'm completely unable to play, because as soon as I enter the level it
 a) in case of Vulkan, freezes and crashes with a message that "device ran out of memory"
 b) in case of OpenGL, freezes and completely kills my PC (I saw dying screams of Mem Reduct, that said that I had >90% RAM busy)
I don't have a bad PC, in fact, even my old PC from 2011 ran it perfectly. My PC specs are:
 Windows 10 Enterprise x64
 Intel Core i3-10100F
 ASUS GeForce GTX 1050 Ti 6GB
 8 GB DDR4 RAM
Doom is located on HDD.
I tried it without any post-processing - no changes.
I'm using latest stable GZDoom from official website.

**Comment by JMartinez9820** [comment]
Try using this version of GZDoom:
https://github.com/drdteam/gzdoom-gles/releases/tag/gles4.6.1

Another option would be using the GLES render. Although it will break certain shaders. Although GZDoom unfortunately is known for memory leaks and all. My only suggestion is to possibly get a new PC if it's that old.

**Comment by Cacodemon345** [comment]
That system is newer than what I got, and with that 6GB VRAM it shouldn't crash.

Do you have any HD texture packs loaded?

**Comment by Anananel** [comment]
> Another option would be using the GLES render

I used it on my old PC. I know all its disabled features. I think it's really my only option now.

> My only suggestion is to possibly get a new PC if it's that old

I bought it a week ago.

> ..and with that 6GB VRAM it shouldn't crash.

Exactly what I think. It's very strange.

> Do you have any HD texture packs loaded?

Absolutely no other PWAD except Project Brutality

**Comment by RoqueDeicide** [comment]
For what it's worth, I'm on gzDoom 4.8.2 with gles and I noticed something interesting with memory usage: when I start the game, ram usage gets over 4GB, but if I save the game, reload doom and load the save game, I get only about 1GB memory usage. I have a bunch of options, like animations and monsters disabled, in case that matters.

**Comment by DemonSlayer1997** [comment]
Try disabling the swap file in Windows and see what happens + there is also a lot of shit from Microsoft in the new Windows. My PC is Intel G3220 and GTX 750 TI 2GB , 8 GB RAM , Windows 7 + I use HD Stuff + maximum settings and fast mode + discord and browser work in the background and OBS at the same time. I experienced the problem only with Vulkan no more. But I know that Vulkan in GZDoom has had problems with a RAM leak for a long time+ Not the most stable rendering. I also use GZDoom 4.8.2 :)

**Comment by Anananel** [comment]
Suddenly, it worked! I haven't tried for a while, and now it just works. After thinking what I could've done, I realized that
1. I've updated to Windows 11
2. I've finally updated my nVidia Game Ready drivers
2 is probably the one. Thanks for all help, most likely it was my stupidity.

**Comment by DemonSlayer1997** [comment]
> I'm completely unable to play, because as soon as I enter the level it a) in case of Vulkan, freezes and crashes with a message that "device ran out of memory" b) in case of OpenGL, freezes and completely kills my PC (I saw dying screams of Mem Reduct, that said that I had >90% RAM busy) I don't have a bad PC, in fact, even my old PC from 2011 ran it perfectly. My PC specs are: Windows 10 Enterprise x64 Intel Core i3-10100F ASUS GeForce GTX 1050 Ti 6GB 8 GB DDR4 RAM Doom is located on HDD. I tried it without any post-processing - no changes. I'm using latest stable GZDoom from official website.

Yo. I think I remembered how to solve this problem with Vulkan - I configured the memory in the BIOS. Peripherals - The amount of memory for the needs of the video subsystem (in my case it is 1024) , the total amount of memory DUMT (Max) 🙂
With such values, I had no problems playing Sunlust, After Doom, Eviternity with Vulkan + browser and discord worked in the background :)
