### ISSUE TITLE
Unmaker upgrade disables daedabus slime

### ISSUE THREAD

**Issue by evanultra01** [pa1nki113r/Project_Brutality#927]
The unmaker, being an upgrade to the Mancubus flame cannon, should inherit the acid mode from the weapon it is upgrading imo.

**Comment by JMartinez9820** [comment]
@evanultra01 In the future, the flame cannon is going to be removed in favor a flamethrower that will have similar functionality of the flame cannon, while the unmaker will become separate. Unmaker isn't a priority in this case, as new designs are going to be made for it.

**Comment by evanultra01** [comment]
Good to hear.
