### ISSUE TITLE
Broken unload on M1, M2, and Nailgun

### ISSUE THREAD

**Issue by JMartinez9820** [pa1nki113r/Project_Brutality#93]
When you unload the M1 Plasma, M2 Plasma or Nailgun, other weapons are no longer usable and can't be switched, forcing the player to restart.

**Comment by brainthinks** [comment]
I also experienced this with the shotgun

**Comment by JMartinez9820** [comment]
Is there a way I can replicate that issue you are having with the shotgun?

**Comment by crosive** [comment]
anytime I try to unload the shotgun with slugs it sticks on reloading.  so far, regular shells seems to work.  It seems to work fine with all shells with the upgrade as well.

**Comment by MekBoss** [comment]
Does PB really need unloading?

**Comment by crosive** [comment]
I use it often.  Especially on the shotguns before you can find a backpack.

**Comment by tunbridgep** [comment]
Reloading is a very useful feature. I hope it stays. Being able to unload all your ammo when you pick up a "better" version of a weapon (shotgun to autoshotgun, etc) is very useful on higher difficulties because I keep running out of ammo otherwise.

**Comment by JMartinez9820** [comment]
Issues are now
