### ISSUE TITLE
carbine and rifle so weak all of the sudden

### ISSUE THREAD

**Issue by duc83** [pa1nki113r/Project_Brutality#930]
i dont know if this was intentional or if its just me but it feels like the dmr and carbine do a lot less damage and i find myself reloading a lot more to kill. i feel like this was to show the new mag drop for the carbine but that seems too far-fetched lol 

im playing the latest jmartinez branch

**Comment by duc83** [comment]
i think either fix hitboxes where zombiemen can actually get hit in the face, make it so dmr and carbine drop more ammo, or fix the damage 

thaknskks

**Comment by JMartinez9820** [comment]
I intentionally decreased the DMRs damage on zoomed because of a bug that it actually dealt more damage compared to hip fire. As for the Carbine, I did not touch it's damage values and the mag drop is fine to me. An empty magazine usually drops after completely emptying it.

**Comment by JMartinez9820** [comment]
I also didn't touch most of DMR damage, just the zoomed damage if unupgraded. HDMR remains the same.

**Comment by duc83** [comment]
oh ok, i dont know now.
thanks for the info :)
