### ISSUE TITLE
shotgun has same spread as combat shotgun

### ISSUE THREAD

**Issue by duc83** [pa1nki113r/Project_Brutality#931]
the shotgun damage and spread and range is the exact same as the combat shotgun, so now theres basically no point in using the normal shotgun exept for slugs and dragons breath, also ADS. i thought the shotgun just had less spread, more range and did damage which made it an actual weapon in the arsenal, different from the combat shotgun.

**Comment by duc83** [comment]
using the jmartinez branch on gzdoom

**Comment by JMartinez9820** [comment]
@duc83 Once again, the pump shotgun spread is changed to match with the Autoshotgun. In real life, buckshot spread is after randomized and isn't good for long range. It also potentially made slugs pointless because of the lack of spread.

**Comment by duc83** [comment]
oke, thank youuuuu i understand
