### ISSUE TITLE
GZDoom stops responding

### ISSUE THREAD

**Issue by AU0Fan** [pa1nki113r/Project_Brutality#932]
I just can't play.

**Comment by JMartinez9820** [comment]
> I just can't play.

A simple "I just can't play" doesn't explain your issue. What GZDoom version are you using?

**Comment by AU0Fan** [comment]
> > I just can't play.
> 
> A simple "I just can't play" doesn't explain your issue. What GZDoom version are you using?

I use 4.7.1.

**Comment by JMartinez9820** [comment]
Try using 4.6.1 GLES or LZDoom. I'll put links as soon as I find it. Also put your PC specs on here if you can.

**Comment by JMartinez9820** [comment]
Due to the lack of a response, this will be closed.
