### ISSUE TITLE
Rocket Launcher Laser Seeking mode rocket stuck in air

### ISSUE THREAD

**Issue by Hadrix420** [pa1nki113r/Project_Brutality#94]
Ever since version 3.7.0 of GZDoom something was changed and now when you shoot a rocket out of the rocket launcher while the laser seeking mode is activated the rocket freezes at the position you shot it out at. The rocket itself is still animated.
The bug is reproducible retrospectively in PB 2.03, latest public test, and this github version.
Is there anything you can do to fix this or is this something to be fixed by GZDoom devs?
EDIT: I have been informed on the GZDoom forum that some of the latest dev builds have addressed the underlying issue, making my ticket pointless, sorry for the spam.

**Comment by transcendreamer** [comment]
Confirm! Rockets are hanging with laser seeking mode on. I reproduced that bug on REQUIEM.WAD.

**Comment by scaryred24** [comment]
Been confirmed that its broken even with GZDoom 3.7.1 as well. It's a problem with GZDoom. Just recently they pushed a change to their dev reverting a change thus [fixing the problem as seen in coelckers/gzdoom/pull/697. Wait for this fix to drop for the next potential stable build of GZDoom and hopefully we won't see this problem again.
