### ISSUE TITLE
Is it possible to make my own mod based on PB?

### ISSUE THREAD

**Issue by Celatoss42** [pa1nki113r/Project_Brutality#942]
Hope this question may not be that offending.I really like PB. The amazing smooth sprite animation and many detail effects are so impressed.Thus I want to conbine them with my another favorite game.

I'm now working on a MetalSlug-style mod, and I want to use weapon sprites from ProjectBrutality. There are a few changes of actions, many changes of projectiles and firing effects, which make these weapons acting like in original Metal Slug games.
Actually there are many more things based on PB. I wonder if I need to get the permission of all PB modders? Or I can just post a copyrights info?
Or it's forbidden to do so?

Sorry for my weird expression. I'm not a native English speaker. Hope I've made it clear. 
And sorry for asking here, I don't know any other ways to contact PB's creators. I tried Discord but due to some Network issues of my country, it was hard to login in. I can see nothing in the PB official channel.

**Comment by Celatoss42** [comment]
Thanks for reply.
So how can I contact these artists? There's no e-mail in Credits file.
Creating my own sprites is of cause a better choice. Problem is this mod was made to combine two games. Without these excellent sprites it will lose a lot of fun.

**Comment by Celatoss42** [comment]
> Usage of PBs sprites varies on a gun to gun basis, and since we dont have full credits done yet i dont think its recommended however you can still ask around for specific guns and whether the artists are alright with them being used, on top of that though, i think its hopefully a partial plan to have the full sheets of the weapons released alongside the full release, just for cases like this, or if people really wanna go out of their way to reanimate the entirety of the roster to not have the artistic animation style PB has

Thanks for reply.
So how can I contact these artists? There's no e-mail in Credits file.
Creating my own sprites is of cause a better choice. Problem is this mod was made to combine two games. Without these excellent sprites it will lose a lot of fun.

**Comment by popguy12** [comment]
would probably wanna see about joining the discord server, most of the artists can be contacted there

**Comment by JMartinez9820** [comment]
@Celatoss42 
Here is a link to the Discord server if you need it:
https://discord.gg/2hJxXPc

This thread will be closed for now.
