### ISSUE TITLE
Mancubus Flamethrower Secondary Fire Sound Bug

### ISSUE THREAD

**Issue by BigJohnexe** [pa1nki113r/Project_Brutality#944]
In the latest version of Project Brutality, if you use the secondary fire of the Mancubus flamethrower on any enemy, the sound of the fire sound effect stays on repeat until the player completes the level. The bugged sound is ear screeching and I have found no way to resolve this issue, making the secondary fire of the weapon seemingly unplayable unless if I want to hear the sound for the rest of the level.

I have tried to reset the sound in the audio settings in GZDoom, but I was unsuccessful in fixing the issue on my own.

Note when I was having this issue, I used the latest version of Project Brutality on the latest version of GZDoom. No other mods nor maps were used.

**Comment by JMartinez9820** [comment]
To be fixed in a later version when the Flame Cannon will be replaced by a new Flamethrower weapon that was showcased on the Discord server

**Comment by JMartinez9820** [comment]
@BigJohnexe 
Fixed in GZDoom 4.8.2
