### ISSUE TITLE
Character freeze when climbing high obstacle

### ISSUE THREAD

**Issue by Barbatuile** [pa1nki113r/Project_Brutality#949]
Hello,

I am on GZDoom g4.8.0, and the latest build of Project Brutality 3.0. I have noticed that when climbing something at double-jump height (i.e in E1M1, the elevated ground with the green armor to the left of starting point, if climbing this instead of taking the stairs) there is 1 chance in approximately 4 that the character remains frozen in below position:

![Screenshot_Doom_20220705_002534](https://user-images.githubusercontent.com/108702102/177225386-ba1465d3-d505-4d74-b896-bd587a60dc2d.png)

I can look around but not change weapon nor move. I have tried using the Kill then Resurrect command, it restores my ability to change weapons and shoot/reload etc., but not to move, as if it somehow was setting the PROP_FROZEN and would not remove it. I have checked Player.dec to see if it could be anything missing in the states, but I have a previous version of PB where this bug doesn't occur and the Jump, Clamber, InAir and Land states are similar so I do not know what has changed.

Thank you for your attention.

**Comment by Barbatuile** [comment]
Update: Upon further testing under different circumstances, it appears that sv_unlimited_pickup has an impact on this behaviour, as I was unable to recreate the issue with this cvar set to 0

**Comment by JMartinez9820** [comment]
@Barbatuile 
We have been getting reports that sv_unlimited_pickup 1 is affecting certain gameplay and adding more bugs, but unfortunately we may not be able to fix this issue and possibly because of limitations between GZDoom and mod code. My only suggestion is to NOT use sv_unlimited_pickup. This will not be fixed for the time being.

**Comment by Barbatuile** [comment]
Hello @JMartinez9820 !

Thank you for your prompt answer. I've noticed indeed there are lots of actors with inventory being limited to 1 such as "Grabbing_A_Ledge" to define behaviours based on whether they are in inventory or not. I can understand how having more than one in Inventory can break some behaviours. I'll try to work my local files to see if I could tackle this by swapping the "A_TakeInventory" with some "A_SetInventory" to 0 instead, although in that specific case I believe the attribution happens in the ACS and not in the Decorate.

If of any interest, I'll happily share the outcome with you.. Have a good day!

**Comment by JMartinez9820** [comment]
And the changes are pushed to my branch. If you want to try it here it is:
https://github.com/pa1nki113r/Project_Brutality/tree/JMartinezBranchOfficial
