### ISSUE TITLE
MG42 Lag

### ISSUE THREAD

**Issue by Somie98** [pa1nki113r/Project_Brutality#959]
Hello Mantinez can you fix MG42 LAG bug please, short burst is okay but long burst lag like hell and get a FPS drop ???

**Comment by JMartinez9820** [comment]
@Somie98 Not a top priority at the moment, it's likely that I will never fix this because of PB's nature and due to PC spec differences. Post your PC specs here and maybe I'll see it later, but not now.

**Comment by JMartinez9820** [comment]
Also, post a video if you can.

**Comment by JMartinez9820** [comment]
Due to no response, this issue will be closed.
