### ISSUE TITLE
DOOM PROJECT BRUTALITY CRASHES

### ISSUE THREAD

**Issue by KingSeryr** [pa1nki113r/Project_Brutality#961]
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 1: Class ExplosiveCaseSpawn has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 12: Class SSGExplosiveCaseSpawner has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 252: Class DanmakuCaseSpawn has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 263: Class SSGDanmakuCaseSpawner has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 504: Class ShotgunCasingSSG2 has unknown base class ShotgunCasing2
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 517: Class ShotgunCasingSSG3 has unknown base class ShotgunCasing3
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 556: Class SSGCaseSpawner2 has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 572: Class SSGCaseSpawner3 has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 589: Class SSGCaseSpawner4 has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 605: Class SSGCaseSpawner5 has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 621: Class WPhosphorusCaseSpawn has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 632: Class SSGWPhosphorusCaseSpawner has unknown base class RifleCaseSpawn
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 1: ExplosiveCaseSpawn: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 12: SSGExplosiveCaseSpawner: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 252: DanmakuCaseSpawn: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 263: SSGDanmakuCaseSpawner: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 504: ShotgunCasingSSG2: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 517: ShotgunCasingSSG3: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 556: SSGCaseSpawner2: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 572: SSGCaseSpawner3: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 589: SSGCaseSpawner4: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 605: SSGCaseSpawner5: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 621: WPhosphorusCaseSpawn: States can only be defined for actors.
PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript/effects/casingscssg.txt, line 632: SSGWPhosphorusCaseSpawner: States can only be defined for actors.

Execution could not continue.

24 errors, 0 warnings while compiling PB_3.0_-_Commader_SSG_27.02.22.pk3:zscript.zc

**Comment by KingSeryr** [comment]
Help please.

**Comment by JMartinez9820** [comment]
@KingSeryr We will not take add-on reports here. Please report this in community add-ons on the Discord server instead.

**Comment by KingSeryr** [comment]
Oh, okay.
