### ISSUE TITLE
All bugs found on gitbuild by me

### ISSUE THREAD

**Issue by Saad356** [pa1nki113r/Project_Brutality#97]
1..infinite head loop bug(very common)
2..Nailgun bug(always)
whenever I select the nailgun,the inspect animation comes up
and this animation plays in an infinite loop while dryfiring(firing after out of ammo)
3..Execution bug(rare)
whenever i execute a pinky,the model is replaced by the zombieman model
4..Last stand bug(common)
Whenever I try to kill a scientist(axe model),and he goes in his last stand(where he screams in pain),i shoot at his head and it doesn't explode..It becomes indestructible
5..Weapon sprite bug(always)
New guns and some old guns have missing bottoms
6..DualSSG bug(unblievably rare)
(how do i explain this)
When I have dual SSG equipped
in 1 case, the animation broke...
the animation of shoooting would not begin and would stay as an image.Even bobbing didnt work
You could not change to other weapons in anyway as well
7..rocket launcher laser guide bug(common)
When I fire the rocket launcher with laser guidance,the rocket hangs in one place and does not move at all
switching weapons isn't even possible
8..Dual carbine bug(always)
Dual carbine doesnt work
I have turned on restore dual carbine but it still slects firemodes.
9..Fps issue( always)
When I play with brutal doom..I have around 60 to 80 fps average
But on PB its 40-60 average with sudden lag spikes as well
10..Pickup sprites issue(always)
Many guns have no pickup sprites like,SMG,Upgradeshotgun,etc.
Thats all.

**Comment by JMartinez9820** [comment]
Some of these bugs have already been reported.

**Comment by JMartinez9820** [comment]
1. IDK what causes that.
2. Very minor bug that doesn't break the game, should be fixed later on
3. Not sure
4. Not sure what does that but I have seen it too
5. Most likely a problem with Zscript's offsets or weapon offsets
6.  Do you steps to replicate the issue
7. GZDoom 3.7.x problem. I recommend downgrade to an earlier version like 3.6.0.
I will explain more later.

**Comment by Cacodemon345** [comment]
8. New Dual Carbine is still yet to be done.
9. We still have no idea what causes that issue.
10. Some weapon pickup sprites have messed-up offsets.

**Comment by Havcom** [comment]
About of DualSSG bug:
You need to take two double-barreled shotguns and, during a jump, catch on any ledge so that Doomgay will clutch his hands. After that, the weapon animation breaks down.

There is also a bug in which when picking up an improvement for an ordinary Shotgun, allowing it to be recharged by the clip, I cannot change weapons through the mouse's wheel while this shotgun is in the hands. Need to change weapons on the keyboard

**Comment by JMartinez9820** [comment]
Every single one of these has been resolved except dual carbine and dual SSG. The lag spikes are due to PB's monster spawner system, which will be upgraded to the ZScript system in the future. This issue can be closed for now, as no one as made a post since last year.

**Comment by scaryred24** [comment]
Unless this comes up again, consider this report closed.
