### ISSUE TITLE
Blood bloom covering screen

### ISSUE THREAD

**Issue by Dr-Intolerance** [pa1nki113r/Project_Brutality#972]
It happens with explosions.
![Screenshot_Doom_20221025_163720](https://user-images.githubusercontent.com/35609330/197896454-1d9648f4-d19a-4b01-ae14-86fc644bbf55.png)

**Comment by JMartinez9820** [comment]
@Dr-Intolerance 
If you're using Software mode, please change it to OpenGL, OpenGL ES, or Vulkan. Also, please update your version as it has gotten an update.

**Comment by Dr-Intolerance** [comment]
Is this "Preferred Rendering API"? It's OpenGL. "Renderer Mode" is True Color SW Renderer. The other options are too slow or add a blinding opaque effect to muzzle smoke.

**Comment by Dr-Intolerance** [comment]
Is this "Preferred Rendering API"? It's OpenGL. "Renderer Mode" is True Color SW Renderer. The other options are too slow or add a blinding opaque effect to muzzle smoke.
_____
Hardware Accelerated does immediately remove the bloom, but my laptop sucks at playing the game quickly.

**Comment by JMartinez9820** [comment]
@Dr-Intolerance 
What are your PC's specs? Also, I highly recommend disabling True Color SW Renderer.

**Comment by Dr-Intolerance** [comment]
I have an integrated cpu and graphics card on a very "sketchy" laptop that has seen a couple of wipes and is likely missing drivers. It's seven years old at the least. I'm getting better performance, well "different" performance though better on SoftPoly, while on Hardware.
_____
I do find now that Hardware with OpenGL ES is the best performing and I haven't had a single "blood bloom" error on Hardware. I do like the older aesthetic of OpenGL ES too. I suppose there are less gore effects as compared to TC SW Renderer with OpenGL, but this is the best it's run on this laptop.

Is Project not supporting the TC SW renderer? The other software renderer is even more terrible without errors such as the one shown, what with the effect of muzzle smoke as if being in musketeer era rifles.

**Comment by JMartinez9820** [comment]
We don't support software mode at all, in fact other mods don't support software too. Also, if your PC is really that bad, it's best to just get a new one. Closing thread.
