### ISSUE TITLE
Left-click and right-click place barrels onto the floor

### ISSUE THREAD

**Issue by Dr-Intolerance** [pa1nki113r/Project_Brutality#973]
The wiki mentions left-click will throw a barrel, yet both mouse buttons place the barrel back down onto the floor.

**Comment by JMartinez9820** [comment]
@Dr-Intolerance 
This was due a change with the barrels, if you don't have berserk, you will not be able to throw barrels. You need berserk to throw barrels.

**Comment by Dr-Intolerance** [comment]
Thanks for clarifying that. This may not be the place for suggestions. Is there a forum? I notice that having health boosted to the high 200s seems to give greater strength to fists, so perhaps barrel throwing could be allowed above 250 health. :)

Thanks for your time Martinez.

**Comment by JMartinez9820** [comment]
@Dr-Intolerance 
You can join the Discord server here:
https://discord.gg/2hJxXPc
