### ISSUE TITLE
Error with a script while launch

### ISSUE THREAD

**Issue by RASamot** [pa1nki113r/Project_Brutality#974]
When I launch the Project Brutality with latest versions using the Doom 2 Steam version (not Unity and obviously using ZDL and GZ), an error appears:

Execution could not continue.

Script error, "Project_Brutality-master.zip:actors/weapons/slot1/axe.dec" line 104:
Invalid parameter 'pb_weaptokenswitch'

Any help?

**Comment by JMartinez9820** [comment]
@RASamot 
If you're using an add-on, please remove all add-ons. Every single add-on is outdated due to a code change with all weapons.

**Comment by RASamot** [comment]
@JMartinez9820  Thank you
