### ISSUE TITLE
when I started the new version of pb 3.0 I found the absence of taunts. also control buttons are reset after exit

### ISSUE THREAD

**Issue by DungeonMaster555** [pa1nki113r/Project_Brutality#975]
when I launched the new version of pb 3.0, I found the absence of mocks and flying control, what's the matter?
will there be a reworking of other monsters and weapons, for example, the same submachine gun, carbine and triple minigun? And also what will happen to the taunt system? it was nice to give the middle finger to the icon of sin and shoot a black hole.

**Comment by JMartinez9820** [comment]
Taunts we're removed because they didn't fit PB's standards and we're really stupid

**Comment by DungeonMaster555** [comment]
> Насмешки мы убрали, потому что они не соответствовали стандартам PB, были слишком детскими и больше не подходили PB.

Thanks for the answer, well, for me personally, teasing a cyberdemon or raising a fist up at the end of a level was a kind of highlight of the brutality of the project
