### ISSUE TITLE
Setup on Linux w/ gzdoom??

### ISSUE THREAD

**Issue by Paulie420** [pa1nki113r/Project_Brutality#977]
I *had* this installed and running on an old system, but I just can't remember how to set it up. My 'brutal doom' is in /usr/share/games/brutal-doom, and the .ini file points there. I've copied over doom.wad and doom2.wad, and 'Brutal Doom' runs, using gzdoom - but I forget how to use and play with the Project Brutality add-ons.
Any Linux users mind reminding me again?? THANKS pa1nki113r, I know how rad these add-ons are. :P I also have the brutal doom starter pack; maybe I'm doing it all wrong? :package:

**Comment by generic-name-guy** [comment]
Download ZDL here: https://github.com/lcferrum/qzdl
You have to set up the GZDoom executable location, i think it's either in /opt/ or the games folder.

**Comment by Slider-Whistle** [comment]
Git clone it or download the zip as directed, then simply pass the whole directory (or zip file) as a -file argument

**Comment by tuhypermadre** [comment]
Hey I have a much better solution but you have to do ctrl-h when in personal folder:
1.Go to .local/gzdoom and there put the project brutality compressed file(i have a folder for mods, another for addons, etc.. but for that you have to manipulate the file in .local/gzdoom/directories.something_idk)
2.Then in your personal folder again go to .bashrc and write this:
``alias project_brutality='gzdoom -name_of_the_project_brutality_mod_file -addon1* -addon2*'``
3.Save it and run a terminal, run this command:
``project_brutality``
4.Play

I think this is by far the better solution.
