### ISSUE TITLE
when you put kill in the console the game crash 

### ISSUE THREAD

**Issue by hellknight99** [pa1nki113r/Project_Brutality#98]
Gzdoom 3.7.1 

e1m1 - Hangar

]sv_Cheats 1
sv_cheats will be changed for next game.
]kill

Execution could not continue.

JIT: sfunc->NumArgs != argsPos || regd > sfunc->NumRegD || regf > sfunc->NumRegF || rega > sfunc->NumRegA

**Comment by scaryred24** [comment]
Please upgrade to GZDoom 3.7.2. Just tested it on that and could not get the game to crash out.

**Comment by MekBoss** [comment]
Actually this is gzdoom bug. Some function got miscompiled with JIT at gzdoom start.
Use -vm_jit 0 command to prevent it.

**Comment by MekBoss** [comment]
For future references
https://forum.zdoom.org/viewtopic.php?f=2&t=63450

**Comment by MekBoss** [comment]
It can be closed, since gzdoom bug was fixed.
