### ISSUE TITLE
Kicking a crawling Zombieman or Shotgun Guy crashes GZDoom

### ISSUE THREAD

**Issue by JMartinez9820** [pa1nki113r/Project_Brutality#99]
Kicking a crawling Zombieman or Shotgun Guy (when their leg is shot off) crashes GZDoom. I'm serious. Not sure if it happens to others, but it does to me. I'm wondering why this happens.

**Comment by secretagentjr** [comment]
that doesn't happen to me, but for some reason sometimes when i die from a shotgunguy, sometimes my game crashes. it's also the same JIT error message everytime

**Comment by scaryred24** [comment]
Are you not using the latest build of GZDoom? If you are, can you trace back as far back before this bug ever appeared? I would like to know what variants are affected by this crash.

**Comment by secretagentjr** [comment]
im using 3.7.2, and it doesn't always happen every single time i die, it seems to just happen randomly when i die

**Comment by Havcom** [comment]
Personally, I use version 3.5.0 for a long time (I'm too lazy to update))) and for more than a year now that I have been playing PB, I haven't had any crashes and departures yet.

**Comment by JasonM2396** [comment]
I have tested it with every GZDoom version that works with PB and I have been getting the same crash. 3.6.0, 3.4.0, QZDoom 2.1.0. I guess its just my computer or something.

**Comment by JMartinez9820** [comment]
I have tested it with every GZDoom version that works with PB and I have been getting the same crash. 3.6.0, 3.4.0, and QZDoom 2.1.0, same result. I guess its just my computer or something.

**Comment by scaryred24** [comment]
The source port locking up is not normal at all. I've only had this happen a few times in the past. Something tells me that we need to go back to an even earlier build. I'm not liking this at all.

**Comment by JMartinez9820** [comment]
I can confirm that is bug seems to be no more for me now. I guess a Windows update or something fixed it. Closing this issue for now.

**Comment by JMartinez9820** [comment]
Update: It seems to happen with Berserk
