### ISSUE TITLE
Rocket Launcher Bug?

### ISSUE THREAD

**Issue by FrostBiteA426** [pa1nki113r/Project_Brutality#990]
I've been having an issue where when I hit zombiemen with a rocket my game freezes and I have to task-kill. Is anyone else having this issue?

**Comment by JMartinez9820** [comment]
@FrostBiteA426 
Redownload master~ This should be fixed. If not, then download Staging or my branch (JMartinezBranchOfficial)

**Comment by FrostBiteA426** [comment]
> Download Staging or my branch (JMartinezBranchOfficial), it's fixed there

Downloaded from your page, still had the same issue. Played Plutonia Experiment and got to map 05, directly rocketed a chaingunner and it froze just like it did before.

https://user-images.githubusercontent.com/119650687/205243522-8f66a8d9-79b8-40f2-8153-36f117e547aa.mp4

I'm not sure if I downloaded it correctly because I'm new to GitHub, but I went to the main page, clicked "code" and clicked download ZIP and that worked for me the last time I downloaded this mod.

**Comment by JMartinez9820** [comment]
Try downloading my branch again, because it should be fixed there unless something got reverted

**Comment by JMartinez9820** [comment]
https://github.com/pa1nki113r/Project_Brutality/tree/JMartinezBranchOfficial

**Comment by JMartinez9820** [comment]
@FrostBiteA426 
Due to the lack of a response, this will be closed. Try downloading my new branch, JMBranch_Staging, to see if that fixes your issue.
