### ISSUE TITLE
Cyber Paladin unknown class

### ISSUE THREAD

**Issue by Catpowerman** [pa1nki113r/Project_Brutality#994]
Here's the log:
https://mega.nz/file/m9MEyLBJ#n-m3ex3L-GA128HVC2XaDxDi7F-nJy8g9CNnpCWPksI

**Comment by JMartinez9820** [comment]
@Catpowerman It's because you're using a McDonald's load of add-ons. Remove ALL add-ons, as this is likely an add-on issue, not a PB issue.

**Comment by Catpowerman** [comment]
For what I've seen, it's the actor declaration

**Comment by Catpowerman** [comment]
GScript error, "Project_Brutality-master.zip:gldefs"G line 1705:
GWarning: dynamic lights attached to non-existent actor PB_CyberPaladin

This shows the problem, the pb_cyberpaladin is inexistent

**Comment by JMartinez9820** [comment]
@Catpowerman It's likely because you're using a McDonald's ass load of add-ons. Remove ALL add-ons, as this is likely an add-on issue, not a PB issue.

**Comment by Catpowerman** [comment]
But i don't have a mod that alters the monsters

**Comment by Catpowerman** [comment]
Just weapon mods

**Comment by JMartinez9820** [comment]
Remove EVERY SINGLE add-on.

**Comment by Catpowerman** [comment]
Ok

**Comment by JMartinez9820** [comment]
Because PB_CyberPaladin exists in the game, no issues. Make sure that you're using the latest build of PB, I recommend my branch, JMBranch_Staging.

**Comment by Catpowerman** [comment]
This Will take a while

**Comment by Catpowerman** [comment]
I downloaded it today

**Comment by Catpowerman** [comment]
Is wadsmoosh a problem?

**Comment by Catpowerman** [comment]
Another problem i have is with glory kill
It give an decorate error

**Comment by Catpowerman** [comment]
Yeah, it's the mods
Thanks for the help 👍
